### ISSUE TITLE
Make running a sample faster in the rake task

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1015]
I just did my round of `rake samples` - as we do `system "bin/shoes #{sample_name}"` we pay the (significant) startup cost for EVERY sample - all 85 of them :( Takes pretty long... making it faster would be really nice.

If we just `require 'shoes'` and then `load` the samples it could be faster, although then we don't have a real isolation when running the samples... although I think there was some kind of argument to load...

Wouldn't it be nice... :)

**Comment by jasonrclark** [comment]
That's a great idea. I would frequently use a faster solution, even if it loses some isolation.

Along those lines too, would be super-nice to have something that runs the samples against the gem installed copy of Shoes as well. I hacked up a batch file for it locally to test on Windows against the installed version, but would be awesome to have it built-in.

**Comment by PragTob** [comment]
A naive implementation using `load` does not work due to....

```
Java::OrgEclipseSwt::SWTException: Invalid thread access
java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:526)
RUBY.initialize_shell(/home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/app.rb:196)
```

I guess when quitting the app we don't shut it down correctly or SWT simply dislikes starting new apps in the same process. Probably worth ivnestigating.

**Comment by jasonrclark** [comment]
I found similar problem in poking at this--if the sample file that we load is the first/main app, then things get really cranky when we shut down.

In lieu of that, though, I spun up this little Shoes app (hacky, copies some stuff from Rakefile for the moment) which gets the effect we want of fast loading samples. Single keypress loads the next sample, with the super+w (Apple+w on the Mac) to shut the spawned windows. Will try this out with my next round of sample testing as it is much, much faster.

```
Shoes.app do
  title "Press a key to load next sample", align: "center"

  def samples_from_file(filename)
    samples = File.read("samples/#{filename}").lines
    samples.map { |s| s.sub(/#.*$/, '') }.map(&:strip).select { |s| s != '' }.map { |s| "samples/#{s}" }
  end

  def working_samples
    samples = samples_from_file "README"
    puts "#{samples.size} samples are known to work"
    samples
  end

  Shoes::InternalApp.add_global_keypress(:super_w) do
    Shoes.apps.last.quit
  end

  samples = working_samples
  keypress do |*args|
    quit if samples.empty?

    load samples.shift
  end
end
```

**Comment by jasonrclark** [comment]
That approach had some side-effect issues that made it less useful than it originally appeared. Implemented a real, slightly-slower-but-fast-enough option with #1439 and wired into the main Rake tasks.
