### ISSUE TITLE
Investigate increase in packaging size

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1019]
With the updated 0.3.0 furoshiki, the size of packaging went up slightly from where the tests were confirming it. I tweaked that (7f2ca0f) to get the release `pre3` finished, but we should look into the size increase and confirm whether or not we're okay with it.

**Comment by gmcnaughton** [comment]
I'm not sure whether this is related, but I'm seeing that the `ignore:` array in `app.yaml` is no longer being respected when packaging with `shoes -p swt:jar .`  Directories which get excluded from the jar under pre2 are not excluded under pre3, resulting in a large increase in output jar size.

**Comment by PragTob** [comment]
seems to be solved once shoes/furoshiki#17 is sorted out :)

**Comment by jasonrclark** [comment]
So new packaging is a little larger, but between shoes/furoshiki#18 and shoes/furoshiki#19, I'm feeling confident that we're as slim as we can get at the moment. Will close this out once those PR's are both landed.

**Comment by PragTob** [comment]
:) PRs landed, so I'll do what Jason suggested!
