### ISSUE TITLE
Downloading doesn't work from an http:// URL that redirects to an https:// URL

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#1026]
As originally reported in #911, and made more visible to users in #1025. We should handle this case without raising an exception. Probably requires either custom http handler or incorporating an external http lib. Would be great to coordinate with asset downloading in shoes/furoshiki as well.

**Comment by PragTob** [comment]
For reference, the code in furoshiki is here: https://github.com/shoes/furoshiki/blob/master/lib/furoshiki/jar_app.rb#L104-L131

the `download_following_redirects` code, dunno if that's the same problem but it'd be nice if the same library could work for both or we rolled our own mini thingie that the two of them then share.

**Comment by jasonrclark** [comment]
One thought on an external http library for this would be Typhoeus. It does run on JRuby and has a streaming mode which might let us do progress (https://github.com/typhoeus/typhoeus#streaming-the-response-body)

**Comment by PragTob** [comment]
I like typhoeus, but I'm not quite sure if libcurl is installed on Windows and hence if it is compatible :) Also that's dependency + ffi.

I recently used [hurley](https://github.com/lostisland/hurley) which basically wants to be a successor to faraday, right now it has no dependencies and just uses stdlib.. no idea if it solves our problems, though :(

**Comment by jasonrclark** [comment]
Ah, super valid point @PragTob. I spend my days thinking about cross-Ruby-version compatibility, but we don't normally have to consider Windows. Might be worth a quick test next time I'm on my Windows machine, but I won't be surprised if it's :boom:
