### ISSUE TITLE
Packager won't ignore directories

### ISSUE THREAD

**Issue by gmcnaughton** [shoes/shoes4#1041]
I can't convince the **pre3** jar packager to ignore directories that the **pre2** packager used to ignore.  My directory structure looks like this:

    app.yaml
    app/myapp.rb
    static/...

`app.yaml` includes the following:
```yaml
ignore:
  - 'pkg'
  - 'static'
```
When I package with `shoes -p swt:jar .` the first time, it creates a `pkg/myapp.jar` which contains the files under `static` (under **pre2** they were properly ignored and excluded from the jar).

Running the same command again results in a jar that contains everything under `static`, as well as a copy of the first jar!  In fact sometimes the jar appears to try to contain itself, and keeps packaging forever, creating an ever-growing jar (until I ctrl-c).

**Edit:** this is under jruby-1.7.19, shoes 4.0.0.pre3, java 1.8.0-b132, Mac OSX 10.9.5

**Comment by wasnotrice** [comment]
Thanks for the report. Will investigate!

**Comment by PragTob** [comment]
Thank you very much for the detailed report :heart: 

We'll investigate and make sure to fix it for pre4! :)

**Comment by gmcnaughton** [comment]
Cool, thanks for taking a look!

I think the issue is in `Furoshiki::Configuration#to_warbler_config`.  It builds an exclusion list prefixed with the current dir name, where `Warbler::Jar` uses "." as the prefix instead:
```ruby
> wc = Shoes::Package::Configuration.load("app.yaml").to_warbler_config
> wc.excludes
 => ["myapp/pkg", "myapp/static", "myapp/static/..."]
> jar = Warbler::Jar.new.apply(wc)
> jar.app_filelist 
 => ["./pkg", "./static", "./static/..."]
```
Hope this helps!

**Comment by PragTob** [comment]
Aha! That certainly helps :) If you want send along a pull request, otherwise we will shoot for a timely solution :) Thanks!

**Comment by bliaxiong** [comment]
I'm having similar issues. When I run: shoes -p swt:jar app.yaml, it errors with:

```
Furoshiki::ConfigurationError: Invalid configuration.
  - Run file configured as '', but couldn't find file at .
       initialize at /Users/dude/.rvm/gems/jruby-1.7.18@mygems/gems/furoshiki-0.3.0/lib/furoshiki/jar.rb:14
  create_packager at /Users/dude/.rvm/gems/jruby-1.7.18@mygems/gems/shoes-swt-4.0.0.pre3/lib/shoes/swt/packager.rb:75
              run at /Users/dude/.rvm/gems/jruby-1.7.18@mygems/gems/shoes-swt-4.0.0.pre3/lib/shoes/swt/packager.rb:30
             each at org/jruby/RubyArray.java:1613
              run at /Users/dude/.rvm/gems/jruby-1.7.18@mygems/gems/shoes-swt-4.0.0.pre3/lib/shoes/swt/packager.rb:27
              run at /Users/dude/.rvm/gems/jruby-1.7.18@mygems/gems/shoes-core-4.0.0.pre3/lib/shoes/packager.rb:19
              run at /Users/dude/.rvm/gems/jruby-1.7.18@mygems/gems/shoes-core-4.0.0.pre3/lib/shoes/ui/cli.rb:61
           (root) at /Users/dude/.rvm/gems/jruby-1.7.18@mygems/gems/shoes-swt-4.0.0.pre3/bin/shoes-swt:11
             load at org/jruby/RubyKernel.java:1087
           (root) at /Users/dude/.rvm/gems/jruby-1.7.18@mygems/bin/shoes-swt:1
```

My setup is:

```
app.yml
app/myapp.rb
app/background.png
```

**Comment by gmcnaughton** [comment]
@bliaxiong try adding a `run:` directive to your app.yaml:

    run: app/myapp.rb

This tells shoes what to run in order to launch your app!

**Comment by bliaxiong** [comment]
Thanks, I wasn't sure what that line meant. Adding the path to my .rb file
successfully builds the jar.

Having another entirely different issue with Java and won't run:

The Gestalt selector gestaltSystemVersion is returning 10.9.1 instead of
10.10.1. Use NSProcssInfo's operatingSystemVersion property to get correct
system version number.

On Thu, Feb 5, 2015 at 4:35 AM, Gordon McNaughton <notifications@github.com>
wrote:

> @bliaxiong <https://github.com/bliaxiong> try adding a run: directive to
> your app.yaml:
>
> run: app/myapp.rb
>
> This tells shoes what to run in order to launch your app!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shoes/shoes4/issues/1041#issuecomment-73025878>.
>



-- 
Thanks!

Blia Xiong
bliaxiong1@gmail.com

**Comment by gmcnaughton** [comment]
@bliaxiong Make sure you pass the `-XstartOnFirstThread` flag when you open the jar, like so: `java -jar -XstartOnFirstThread myapp.jar`.  Without this flag, Java SWT won't work -- unfortunately this means you can't double-click on the jar to launch it.  There's discussion about this on the packaging docs somewhere!

If that doesn't fix it, could you open a new issue (since this is probably unrelated)?

**Comment by bliaxiong** [comment]
Thank you for the hep!

**Comment by PragTob** [comment]
Thanks for helping a fellow shoeser @gmcnaughton ! :)

**Comment by jasonrclark** [comment]
Fix for this was over in furoshiki: https://github.com/shoes/furoshiki/pull/18

**Comment by jasonrclark** [comment]
With the furoshiki change merged, this should be fixed using that change (and a new gem for it will come with the next pre-release of Shoes.) Thanks again @gmcnaughton for the great :bug: report!

**Comment by gmcnaughton** [comment]
Awesome, thanks for the fix @jasonrclark! :+1:
