### ISSUE TITLE
How changelog works

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#1045]
In our `changelog` task we determine which commits took place between the last release and the current one via `git rev-list --tags --max-count=1`.

This makes sense since the last tagged commit should be the last version we released.

If I call `git tag` I get back the three tags we've used for three versions we've released. But if I call `git rev-list --tags` I *do not* get just three commit SHA back! I get a huge pile of them!

If I ask git to `describe` the tag second from the top (which I expected to be pre-release 2) here's what I get

```
KC:shoes4$ git rev-list --tags --max-count=2
8d392f47e41d4e3b147dbe6346291933a0927c1d
7f2ca0f47604c5f8a027dc12010ac34ac61e28ae
KC:shoes4$ git describe 7f2ca0f47604c5f8a027dc12010ac34ac61e28ae
v4.0.0.pre2-265-g7f2ca0f
```

My best guess is that all of the commits between pre2 and pre3 got automatically tagged as `pre2-1` `pre2-2` etc.  But I haven't been able to find any documentation online verifying that for me.

Can anyone explain this mystery to me?

**Comment by PragTob** [comment]
that is also my best guess :)

```
tobi@airship ~/github/shoes4 $ git describe 40151e9817f608b8ee0c99
v4.0.0.pre3-89-g40151e9
tobi@airship ~/github/shoes4 $ git describe 1728e41d3c3eb71
v4.0.0.pre3-88-g1728e41
tobi@airship ~/github/shoes4 $ git describe 4e55bf221780fe6
v4.0.0.pre3-87-g4e55bf2
tobi@airship ~/github/shoes4 $ 
```

Looking at the help I found this:

```
tobi@airship ~/github/shoes4 $ git help describe
The command finds the most recent tag that is reachable from a commit. If the tag points to the commit,
       then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional commits on
       top of the tagged object and the abbreviated object name of the most recent commit.

```

That should answer your question :)

**Comment by KCErb** [comment]
Oh yeah, that definitely explains why describe is describing them that way, thanks again!

I do have an  extra question now though :)

Based on what you said, it sounds to me like the commits between the pre2 tag and pre3 tag *aren't* tagged; `describe` is just describing them in reference to nearby tagged commits.

So my follow up question is: why does `rev-list --tags` return non-tagged commits if they are before the last tag, but no commits after the last tag? That's the behavior we want for changelog, but I don't understand how to predict that behavior.

Look at `git help rev-list` under the tags option I see

```
 --tags[=<pattern>]
           Pretend as if all the refs in refs/tags are listed on the command
           line as <commit>. If <pattern> is given, limit tags to ones
           matching given shell glob. If pattern lacks ?, *, or [, /* at the
           end is implied.
```

but I don't know what refs, refs/tags, or <commit> are doing in there! It's a totally foreign language! I don't want to get too far off on a tangent, but what can I do to understand why this works, and maybe even understand what the manual is saying :P

**Comment by PragTob** [comment]
To be honest - I'm not sure. I _think_ git tags only one commit and can then infer which commits are still in that range from the last commit but I'm no super expert. Also, the `git` manual is regarded as rather difficult to understand by most people that I know - if you really want to understand that lingo I recommend reading one of the many free online books about git :)

**Comment by KCErb** [comment]
OK, thanks @pragto.  I'll just safely file this away as git magic that can be answered by more serious study and move on :)

My goal is to understand these things as well as the next guy for now. So from my standpoint, "I'm not sure" is as good as "Oh that's common knowledge, read this."

Thanks again
