### ISSUE TITLE
Text background not filling to edge when wrapping

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1047]
Sample app (drawn from #777)

```
Shoes.app width: 250, height: 500 do
  COLORS = [red, green, blue, yellow, orange, purple]
  3.times do
    flow do
      COLORS.each do |color|
        para "Boo Hoo Hoo Hoo", fill: color, size: 24
      end
    end
  end
end
```
![image](https://cloud.githubusercontent.com/assets/130504/5991241/d336e9e6-a995-11e4-8855-01c7388a769a.png)

Would look a lot nicer if the color on the first text layout extended to the furthest edge.

**Comment by PragTob** [comment]
Huh, it probably would look nicer but I guess it migt cause problems - what we would need for this to work is to make the first text block (when we break them up) extend all the way to the edge (increase width). Hm Maybe it's not that difficult after all :)
