### ISSUE TITLE
Shoes quit/close may fall? 

### ISSUE THREAD

**Issue by seethemhigh** [shoes/shoes4#1053]
Hello. Running a simple app that, from my perspective, should only render a window and be gone immediately,

example 1 
```ruby
Shoes.app { quit }
```
but instead it throws an exception "Java::OrgEclipseSwt::SWTException: Widget is disposed"

Running example 2 works fine though

example 2
```ruby
Shoes.app do
  keypress { |k| quit }
end
```

This is the intended behavior? I'm running on Ubuntu 14.04. Thanks

**Comment by wasnotrice** [comment]
Definitely not the intended behavior. Thanks for the report!

**Comment by PragTob** [comment]
Yeah thanks for the report, we'll look into it! :)

**Comment by seethemhigh** [comment]
@wasnotrice , @PragTob you're welcome!
Offtopic. Could you please look at #772 ? I've posted there a comment. Thanks.
