### ISSUE TITLE
rake samples causes invalid thread access error on mac

### ISSUE THREAD

**Issue by richardbatty** [shoes/shoes4#1055]
I'm guessing you already know about this given that the readme says that bin/shoes doesn't work on mac, but rake samples uses bin/shoes and therefore also doesn't work. I get

```
LoadError: load error: shoes/swt -- org.eclipse.swt.SWTException: Invalid thread access
```

This is on version 4.0.0.pre3

**Comment by KCErb** [comment]
Hi @richardbatty, thanks for trying Shoes!

I'm on OS X and `rake samples` works fine for me right now. Can you give me some more details about how to reproduce the error?

* Are you running from a fork of `shoes4` or are you in the gem (i.e. which Rakefile is `rake` talking to)?
* What version of OSX are you on?
* Have you run `bundle install`?
* Which files are in your `shoes4/bin` directory? You should have a `shoes-backend` file. If so what's inside?

**Comment by richardbatty** [comment]
Hi,

I cloned the ```shoes4``` repo and then ran rake samples from inside that. So ```rake``` is talking to https://github.com/shoes/shoes4/blob/master/Rakefile

I'm on OSX 10.10.1

I've run bundle install

in ```shoes4/bin``` I have ```shoes```, ```shoes-swt``` and ```shoes.bat```. No ```shoes-backend``` file. As far as I can tell my ```shoes4/bin``` directory is the same as https://github.com/shoes/shoes4/tree/master/bin

**Comment by KCErb** [comment]
Hmm,  I believe the `samples` task should call the samples with `bin/shoes` like you said. But `bin/shoes` is supposed to create a `shoes-backend` file the first time it runs. It's this file that makes `bin/shoes` work on OS X. (If you're curious to know why, you can read [these notes](http://kcerb.github.io/cordwainer/start/) I wrote up to remind myself how this stuff works).

I'm not sure why yours hasn't created it yet though . . .

Someone with more experience than me may chime in here and figure this out (:+1:) but until then can you try creating a file called `test.rb` and running it with `$ bin/shoes path/to/test.rb`. The contents should just be

```ruby
puts "Hello"
```

Copy and paste your terminal output for me. And then run `rake samples --trace` and let me see the full output from that too.

Thanks!

**Comment by PragTob** [comment]
Hi there,

yeah could you please do what @KCErb suggested? The output of running `bin/shoes` is highly interesting to us. It should generate a script that is mac compatible on the first run.

Thanks for the issue report! :+1:

**Comment by richardbatty** [comment]
I just created a pull request with what I think is the fix.

The output of ```rake samples --trace``` was:

```
** Invoke samples (first_time)
** Invoke samples:random (first_time)
** Execute samples:random

82 samples are known to work
Running samples/simple-calc.rb (1 of 82)...quit to run next sample
***WARNING: Display must be created on main thread due to Cocoa restrictions.
LoadError: load error: shoes/swt -- org.eclipse.swt.SWTException: Invalid thread access
  require at org/jruby/RubyKernel.java:1071
  require at /Users/richardbatty/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/runtime.rb:85
     each at org/jruby/RubyArray.java:1613
  require at /Users/richardbatty/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/runtime.rb:61
  require at /Users/richardbatty/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler.rb:134
   bundle at /Users/richardbatty/Code/shoes4/shoes-core/lib/shoes/ui/picker.rb:17
      run at /Users/richardbatty/Code/shoes4/shoes-core/lib/shoes/ui/picker.rb:7
   (root) at /Users/richardbatty/Code/shoes4/shoes-core/bin/shoes-picker:6
cat: /Users/richardbatty/Code/shoes4/shoes-core/bin/shoes-backend: No such file or directory
shoes-core/bin/shoes: line 62: samples/simple-calc.rb: Permission denied
Running samples/sample2.rb (2 of 82)...quit to run next sample
```

**Comment by PragTob** [comment]
It seems that no `shoues-backend` file was generated for you.

Could please post the output of `bin/shoes samples/simple-calc.rb` ? Maybe it will generate the `shoes-backend` - I dunno. We probably need to look into this. @jasonrclark ?

If the problem in #1060 is the require, have you tried running `bundle exec rake samples` ?

**Comment by jasonrclark** [comment]
That output would be very helpful. As soon as I can I'll take a closer look too... maybe tonight, hopefully this weekend.

**Comment by jasonrclark** [comment]
Hey @richardbatty, I have a branch #1069 which I think might address your issue. I was able to duplicate your problem exactly when I updated my JRuby version (was on 1.7.16.1, moved to 1.7.19), and this dealt with it.

Great catch on this! :heart: Guess I should upgrade my JRuby more often :see_no_evil:

**Comment by PragTob** [comment]
:+1:  update jruby all the time! (I try to keep `.ruby-version` in sync with new releases)

**Comment by richardbatty** [comment]
I just cloned the repo afresh and ran rake samples. It works fine now.

Thanks!

**Comment by PragTob** [comment]
Thanks for getting back to us and glad it works for you now :)

**Comment by jasonrclark** [comment]
Thanks for the double-check @richardbatty, and thanks again for the report! :sparkles:
