### ISSUE TITLE
Closing leaves a zombie app (Shoes.apps)?

### ISSUE THREAD

**Issue by seethemhigh** [shoes/shoes4#1065]
I believe I've spotted something suspicious when closing an app. Here's the output from IRB:
```
irb(main):001:0> require 'shoes'
=> true
irb(main):002:0> Shoes.apps
=> []
irb(main):003:0> Shoes.app {}
=> (Shoes::App:0x00003b24 "Shoes 4")
irb(main):004:0> Shoes.apps
=> [(Shoes::App:0x00003b24 "Shoes 4")]
irb(main):005:0> Shoes.apps.first.close
=> nil
irb(main):006:0> Shoes.apps
=> []
irb(main):007:0> 

```
Line 4 shows that there's a registered app, though I've already closed it using the mouse. But only after the line 5 the app goes away completely. Btw ```Shoes.app { quit }``` also leaves the app in ```Shoes.apps```.

It's a bug, right?

**Comment by jasonrclark** [comment]
Can confirm the behavior, and that does seem like a bug to me. When an individual app window is closed, I'd expect it to be removed from the list. Good catch @seethemhigh!

**Comment by PragTob** [comment]
Most definitely, sorry forgot to comment here before! Thanks @seethemhigh :)

**Comment by seethemhigh** [comment]
@PragTob You're welcome. Hoping to return contributing here soon :)
