### ISSUE TITLE
ask_save_file does not allow user to type a filename

### ISSUE THREAD

**Issue by tlemburg** [shoes/shoes4#1066]
First of all, love what everyone has going on here, and I'm looking forward to possibly contributing in the future. I'm using Shoes4, Mac OSX 10.10, and running samples/simple-dialogs.rb, and trying the save file dialog. But this dialog doesn't actually give me the option to type in a filename to save a new file. I can click an existing file to use that filename, but this is typically not what users want out of "Save File". I'm not sure if this works correctly in other OS's but it seems that this is just a weird oversight with which SWT dialog to query? I'm kind of a noob in this kind of thing, so any help would be appreciated. Thanks!

1. Run samples/simple-dialogs.rb
2. Click Save File...
3. Following dialog appears.
![screen shot 2015-02-23 at 8 31 56 pm](https://cloud.githubusercontent.com/assets/1199848/6342221/0e4ccc46-bb9b-11e4-9a0b-a20b63130d47.png)

**Comment by tlemburg** [comment]
Upon further investigation, it seems the dialog_chooser method in shoes-swt/lib/shoes/swt/dialog.rb only uses the SWT::OPEN constant and not the SWT::SAVE constant. So I made an early pull request: https://github.com/shoes/shoes4/pull/1067

I will defer to the stylistic choices of the community if we want a little different separation of code here. I can also write tests, but I will have to look into it tomorrow. Thanks! :)

**Comment by seethemhigh** [comment]
Can confirm the same issue on Ubuntu 14.04. Here's how it looks like
![screenshot from 2015-02-25 20 55 26](https://cloud.githubusercontent.com/assets/10567153/6376822/5d51b62a-bd31-11e4-852c-eb5237a77c6d.png)

**Comment by PragTob** [comment]
Hi there, thanks a lot for the report! :)

Sorry for the late reaction, lots of stuff happening in the lifes of lots of shoes contributors atm (I'm moving flats atm :) )

Thanks so much - I'll check out the PR and see that this will get fixed.

PS: @seethemhigh nice device names... RIP Leonard Nimoy

**Comment by tlemburg** [comment]
Pull request was merged so I'll close this.

**Comment by PragTob** [comment]
Yes, thank you very much! :)
