### ISSUE TITLE
Packaged apps only work sometimes...

### ISSUE THREAD

**Issue by tlemburg** [shoes/shoes4#1071]
I'm having a very strange problem with packaging apps where the packaged Mac App will sometimes work, and sometimes crash immediately upon opening. It is making no sense to me why it only does it sometimes...I'm hoping someone can reproduce this. I started with a brand new everything, and after installing RVM, and downloading and installing the JDK,

1. rvm install jruby-1.7.19
2. rvm use jruby-1.7.19
3. rvm gemset create packaging
4. rvm gemset use packaging
5. gem install shoes --pre

I now grabbed the simple-oval.rb file from Shoes samples to test this out. It was put in its own directory.

6. shoes -p swt:app simple-oval/simple-oval.rb

And of course, an app was created under simple-oval/pkg. I double-clicked the app and got 

![image](https://cloud.githubusercontent.com/assets/1199848/6494809/f7fa817c-c289-11e4-8fa3-3806039ec779.png)

I clicked Ignore, then double-clicked the app again. The app loaded and a black oval was displayed. 

I've been struggling with this for a while...after running a ton of attempts, it seems the app will load about 40-50% of the time, and crash otherwise. **However**, if I dig into the app (right-click, show contents), and double-click the JavaLauncher under MacOSX, it will always work. The JVM puts a log in my home directory if it crashes, but I don't think there's anything useful in there. I know packaging is just a baby, but it seems that this should work, especially with an extremely simple sample. Does anyone know what's going on here/what I'm doing wrong??

I'm on Mac OSX 10.10 | jRuby-1.7.19 | JDK8u40 | shoes4.0.0-pre3

**Comment by PragTob** [comment]
Hm this seems really strange... :'(

What does the crash log say? Could you please post it as a gist?

Also, if you package it as a jar, does it always work then?

This issue over at furoshiki might be interesting (that's the packaging component): shoes/furoshiki#16

Thanks for the report! :)

**Comment by tlemburg** [comment]
I found a little more info on this. Here's the gist of the error log dropped in my home folder: [https://gist.github.com/tlemburg/b07b1f42b0a57a961072](https://gist.github.com/tlemburg/b07b1f42b0a57a961072)

If I package as a jar, and run with `java -jar -XstartOnFirstThread path/to/jar.jar`, I don't run into problems...I haven't been able to crash it. However, running `open path/to/app.app` with the packaged app gives an error in terminal:

    LSOpenURLsWithRole() failed with error -10810 for the file 
    /Users/tyler/Documents/packaging/simple-oval/pkg/simple-oval.app.

But oddly, still only about half the time.

I actually DID see that issue on furoshiki but didn't make the full connection until you linked it. And it makes more sense because that 10810 error code is noted in [this StackOverflow](http://stackoverflow.com/questions/24582806/creating-bundle-for-java-7-jar-file-on-macos-manually) which was also linked in [shoes/furoshiki#16](https://github.com/shoes/furoshiki/issues/16). Further, removing the key in the Info.plist file as @justahero did made the app work. 

I think if there are no more comments on this we can close this issue, as the real work to do is in  [shoes/furoshiki#16](https://github.com/shoes/furoshiki/issues/16). Thanks so much @PragTob ! :D

**Comment by PragTob** [comment]
:) great and thanks @tlemburg - we can close this up :) Haven't been good on issue gardening lately.
