### ISSUE TITLE
Default class level styles seem to override app level styles

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1077]
I tried to set a default font and it failed. It seems to me that the class level degault overrides the global setting, at least for fonts. Setting the font explicitly for a class solves the problem. Example:

```ruby
Shoes.app do
  font File.join(Shoes::DIR, 'fonts/Coolvetica.ttf')
  stack do
    font = 'Coolvetica'
    style(font: font)
    title 'The quick fox runs fast'
    style(Shoes::Title, font: font)
    title 'The quick fox runs fast'
    para 'The quick fox runs fast'
  end
end
```

![shoes 4 _044](https://cloud.githubusercontent.com/assets/606517/6769163/12ba95b0-d090-11e4-8559-a3166506b26b.png)

I'd expect the first title to already be styled as Coolvetica. As you can see, the workaround is to set it for all classes for now.

Should be a (I hope) rather easy fix in `Shoes::Common::Style` for the order in which hashes are merged there.

Specs for this case are a must :)

**Comment by seethemhigh** [comment]
I've took a look at this and have got an ok'ish solution. A PR will follow soon :)

**Comment by PragTob** [comment]
Solved by @seethemhigh - thank you very much!!!! :D
