### ISSUE TITLE
Performance - simple-manual.rb

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1078]
It might just be me but `simple-manual.rb` seems A LOT slower on master. A lot as in clicking on `Colors` takes a felt `~ 10 seconds` to open and then scrolling is awfully slow.. even laggy where scrolling takes multiple seconds some times.

We need to investigate to see what introduced this (if reproducible) and fix it or just a good old general performance analysis. 

If it is not a degradation, then well. still FIX it :)

**Comment by PragTob** [comment]
Went as far back as to pre2. On pre 2 it is still slow, but load feels at least `~3x` faster between pre2 and pre3. So that's a start - dunno if the best approach is to do a general performance analysis or look what happened inbetween.

Maybe it's just my subjectiveness. Any confirmations? :)

**Comment by jasonrclark** [comment]
Confirmed very briefly that things seemed worse between pre2 -> pre3, and then running off master seemed worse still than pre3.

Don't have time before :sleeping: tonight, but I'm keen to bisect it at least given how many of the changes in that timeframe are mine :) I've also been doing a lot of perf work in my day job, so I'm keen to put some of what I've been using to work there as well.

Given the confirmation and my interest, tagging this for pre4 to at least assess what can be improved.

**Comment by PragTob** [comment]
Through great work by @jasonrclark I believe we are at an even better stage than pre2 now - thanks you :metal: :rocket:

**Comment by PragTob** [comment]
As written before, we went to even better perf than before - closing this one!
