### ISSUE TITLE
Document performance debugging/tools and benchmarks in wiki

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1082]
Right now we were hitting some performance issues and I remember I already did some of that work in 2013 - now @jasonrclark did some. Leading up to a release I expect us to do a lot more of this (for great profit!). We still got algorhitmic improvements ahead of us with #593 and the like but sometimes we need to track down slow code.

I remember the tools were a bit confusing at the beginning - so gathering information in our wiki to help people get started seems good.

Off the top of my head:

* http://visualvm.java.net/ - you can attach it to a JRuby process and then monitor with all the JVM goodness
* `jruby --profile` - a builtin profiler in JRuby, supports different formats. The implementation is quite old but I found it to be the most useful tool back then. (fun fact, written by danlucraft who also made the SWT gem)
* sdlib `benchmark` or even better `benchmark-ips` for writing benchmarks to have a baseline and see if we actually get better

Looking for more tools and more extensive docs on how to use those :)

**Comment by jasonrclark** [comment]
https://github.com/shoes/shoes4/wiki/Profiling-and-Benchmarks :boom: :books: :athletic_shoe:

**Comment by jasonrclark** [comment]
FWIW, I do still plan to do some blogging on this in more detail with some example cases from Shoes. The tools are only half the battle--the process and mindset of finding what's slow will be interesting to write more about when I have some time.

**Comment by KCErb** [comment]
Please do! :+1:
