### ISSUE TITLE
Use benchmark-ips gem at least for micro benchmarks

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1083]
[benchmark-ips](https://github.com/evanphx/benchmark-ips) automatically runs the benchmark a certain number of times (with warmup) which is nice at least for micro benchmarks.

Find existing micro benchmarks in benchmarks and use benchmark-ips there instead please :)

**Comment by jasonrclark** [comment]
I've added the `benchmark-ips` gem to the Gemfile, but haven't made any significant changes to benchmarks, so this is still open to anyone interested to pick it up.
