### ISSUE TITLE
ListBox#change block doesn't trigger when ListBox#choose is called

### ISSUE THREAD

**Issue by TieSoul** [shoes/shoes4#1089]
Example:

```
Shoes.app do
  button "change" do
    @list.choose("x")
  end
  @list = list_box items: ["x", "y", "z"] do |x|
    p x.text
  end
end
```

When you manually change the ListBox, the change block triggers, but when ListBox#choose is called by the button's click block, it doesn't. In Shoes 3, ListBox#choose does trigger the change block.

**Comment by jasonrclark** [comment]
Good find @TieSoul! That's totally a bug, and I've marked it so we make sure to get it fixed before the 4.0 release.
