### ISSUE TITLE
Gradient clipping with Line

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1100]
With the following sample app:

```
Shoes.app do
  line 10, 10, 100, 100, strokewidth: 20, stroke: gradient(blue, green)
end
```

I see this result:

![image](https://cloud.githubusercontent.com/assets/130504/7245181/9e2211e2-e79b-11e4-9707-d6472c4154c8.png)

The strokewidth apparently should get taken into account when a line is being used with a gradient. Haven't been able to duplicate another element type having the same problem (even rectangles when rotated, which seemed most likely to be impacted).

**Comment by PragTob** [comment]
I guess we could/should reuse some of the mathematical code of the `in_bounds?` implementation or treat it as a rectangle or something :)

**Comment by jasonrclark** [comment]
The other idea I had was that we know based on the strokewidth the maximum that the line could extend below it's "bottom" point, so we could just set the gradient to start/stop slightly further out?

**Comment by PragTob** [comment]
Certainly the more pragmatic solution :D 

I'd probably try an exact solution for a bit and if that doesn't work resort to that :)

**Comment by jasonrclark** [comment]
Did a little further investigating, and seeing even more weirdness with the gradients. Here's the sample app which rotates a line around.

```
Shoes.app do
  @l = line 10, 200, 200, 200, strokewidth: 20, stroke: gradient(blue, green)
  dx = +8
  dy = -8

  animate do
    @l.left += dx
    @l.top  += dy

    dx = -dx if @l.left > 400 || @l.left < 10
    dy = -dy if @l.top  > 400 || @l.top < 10
  end
end
```

In addition to the clipping I noted before, when crossing the vertical point, the ends of the gradient switch. When crossing the horizontal, the pattern gets too small and repeats.

Still no precise solution--too much math for me this late at night--but more to consider.

**Comment by jasonrclark** [comment]
Found this app in a commit comment, bc21f58124d37cd85dc1ffc8cadb3521a96eab46, which helped me finally understand what the whole angle business was doing:

```
Shoes.app height: 300 do
  background salmon..chartreuse, angle: -45
  oval 10, 10, 200, fill: green..yellow, angle: 90
  rect 300, 10, 200, fill: red..blue, curve: 10, angle: 45
end
```

This is also discussed at some length in #156. Not sure when I'll get to this, but I've got some ideas forming about what's going on and the best way to handle it.

**Comment by KCErb** [comment]
Hey @jasonrclark, you mentioned you have some ideas forming about this. Do you still want to tackle this one? If not you can maybe jot some of those ideas down if you still have them and I'll try to pick it up.

**Comment by jasonrclark** [comment]
So to be honest, I don't entirely remember what those ideas were at the time :grin: I think I had some clever thought that we just needed to bump the boundaries on the pattern out more in a couple cases and :boom: it'd be done.

In actual fact, I've picked at this a couple times, and if you watch the sample app in https://github.com/shoes/shoes4/issues/1100#issuecomment-101541890 like I have, I **really** don't understand what's going on. I believe that it's something to do with https://github.com/shoes/shoes4/blob/master/shoes-swt/lib/shoes/swt/gradient.rb#L63-L75 which has a bunch of crazy math that treats things differently in the four quadrants (which you can observe in the animated sample).

This has proven to be a bit rough for me to wrap my brain around in tired moments at the end of the day, so if you feel inclined please have at it! One approach would be to try and understand how that pattern creation method's argument effect things, because maybe if we get a grasp on that it'll be obvious what to do.

**Comment by KCErb** [comment]
Sounds fun! I'll see what I can learn...

**Comment by KCErb** [comment]
OK, I'm thinking the right approach here is to tackle a few gradient problems at once:

#370 
#369
and this one.

Basically make sure background, border and gradient are using the same mechanics for handling a gradient angle and clipping.

I know it might be too much for one PR but as I look through the issues and the code I feel like a part of the reason this lingers is that they all need to come together at once . . .

objections before I go forward with that?

**Comment by jasonrclark** [comment]
I say go for it! It definitely feels like someone needs to grapple with and fully understand how it's working (and how it's meant to work) to deal with the outstanding issues.

Personally I wouldn't worry about the PR size at this point. I often will make lots of changes to figure out a solution to something, then as a later step try to see how they can break down into smaller pieces. And if they don't break down nicely since it's all inter-related, then that's fine too!

**Comment by KCErb** [comment]
cool cool, I'll see what I can do.

**Comment by PragTob** [comment]
:+1: have fun tackling it, I know I looked at it a couple of times and gave up. Also I looked at the gradient a couple of times to see if I can clean it up some more... and gave it up.
