### ISSUE TITLE
Crash in samples/expert-funnies.rb

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1121]
Regression from 4.0.0.pre3. #1025 looks like the cause--it's forcing download to raise errors back to the parent that weren't before.

Given this, I'm torn. Surfacing the errors seems better, but deviates from Shoes 3 behavior (and arguably the Shoes philosophy).

What do we think about providing an error proc for `Download`, and having it default to logging the exception rather than raising? That gets me the feedback I want without crashing the app.

```
~/source/shoes4:bin/shoes samples/expert-funnies.rb
2015-05-06 22:48:57.847 java[71162:230b] *** WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
java/lang/reflect/Method.java:483:in `invoke': org.eclipse.swt.SWTException: Failed to execute runnable (org.jruby.exceptions.RaiseException: (HTTPError) 404 Not Found)
	from /Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/gems/shared/gems/swt-4.4/lib/swt/minimal.rb:109:in `run_event_loop'
	from /Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/gems/shared/gems/swt-4.4/lib/swt/minimal.rb:92:in `event_loop'
	from /Users/jclark/source/shoes4/shoes-swt/lib/shoes/swt/app.rb:49:in `open'
	from /Users/jclark/source/shoes4/shoes-core/lib/shoes/internal_app.rb:106:in `open_gui'
	from /Users/jclark/source/shoes4/shoes-core/lib/shoes/app.rb:50:in `initialize'
	from /Users/jclark/source/shoes4/shoes-core/lib/shoes/app.rb:19:in `app'
	from /Users/jclark/source/shoes4/samples/expert-funnies.rb:26:in `(root)'
	from org/jruby/RubyKernel.java:1081:in `load'
	from /Users/jclark/source/shoes4/shoes-core/lib/shoes/ui/cli.rb:1:in `(root)'
	from /Users/jclark/source/shoes4/shoes-core/lib/shoes/ui/cli.rb:58:in `execute_app'
	from /Users/jclark/source/shoes4/shoes-core/lib/shoes/ui/cli.rb:72:in `run'
	from org/jruby/RubyKernel.java:1081:in `load'
	from /Users/jclark/source/shoes4/shoes-swt/bin/shoes-swt:11:in `(root)'
Caused by:
/Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/1.9/open-uri.rb:346:in `open_http': org.jruby.exceptions.RaiseException: (HTTPError) 404 Not Found
	from /Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/1.9/open-uri.rb:775:in `buffer_open'
	from /Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/1.9/open-uri.rb:203:in `open_loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from /Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/1.9/open-uri.rb:201:in `open_loop'
	from /Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/1.9/open-uri.rb:146:in `open_uri'
	from /Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/1.9/open-uri.rb:677:in `open'
	from /Users/jclark/.rbenv/versions/jruby-1.7.16.1/lib/ruby/1.9/open-uri.rb:33:in `open'
	from /Users/jclark/source/shoes4/shoes-core/lib/shoes/download.rb:77:in `start_download'
```

**Comment by ccoupe** [comment]
I wouldn't worry too much about Shoes 3 compatibility, especially  for error handling. Shoes 3.2 has diverged from 3.1 in ways that  matter for C level, bare metal folks. We've unearthed undocumented code, fixed it, documented some of it even if we don't know why it's there. Obviously no one could have used that code in their scripts if they didn't know it existed but -- they can now ( additional image transforms and creating svg/pdf files from image blocks - who knew?) , We've added  packaging and gem handling features(?) that have little relevance or impossible in a jRuby Shoes world view.

**Comment by PragTob** [comment]
I like your idea @jasonrclark of not raising and just logging it away (+ the error proc).

At the same time for me that raises the question if we could unify that behavior. E.g. we create a `Shoes::Exception` and all of our exceptions should inherit from that, we then catch it at the top level and log it away while from anywhere in the code to the top level users are still able to catch it.

**Comment by KCErb** [comment]
:+1: `Shoes::Exception`

**Comment by jasonrclark** [comment]
`Shoes::Exception` puts me very in mind of #619, which is about the general fact that Shoes 4 right now will just crash where Shoes 3 wrote to console and stumbled on. While we might not want to catch everything, will certainly be worth a more considered approach to that before the full 4.0 release. In dev, crashing's actually nicer, though :)

Appreciate your thoughts @ccoupe on compatibility there. While I don't worry a lot about the weirder corners, if someone wrote a simple Shoes app that ran before, I do want it to run on Shoes 4 if possible. This particular case falls into that camp.

For the sake of the regression in `pre4` I'm going to set things back to logging noisily with the error proc, and we can consider deeper error handling with that other issue.
