### ISSUE TITLE
Executable package for windows ?

### ISSUE THREAD

**Issue by systemaker** [shoes/shoes4#1131]
hello,
I used the command "shoes -p swt:app hello.rb" to package my app but there is no .exe file and the .jar file do nothing when i double click on it.
i have windows 7 , 64bit

**Comment by jasonrclark** [comment]
Hey @systemaker! Shoes remains under development, and packaging in particular isn't anywhere near feature complete yet.

#90 is the issue we've got for tracking that we need a .exe implementation of packaging, so I'm going to close this out as a duplicate.

As far as running the .jar, something like this command should get you running:

```
java -jar path/to/theshoes.jar
```

[This stackoverflow link](http://stackoverflow.com/questions/8511063/how-to-run-jar-file-by-double-click-on-windows-7-64) might also be of use, although I'm not on Windows to test it out at the moment.

Hope that helps, and thanks for trying out Shoes!
