### ISSUE TITLE
Ruby and Jruby on windows

### ISSUE THREAD

**Issue by systemaker** [shoes/shoes4#1135]
Hello,
maybe not an issue but an information useful  for shoes4 new users : 
 Jruby make a conflict with Ruby already installed by the ruby installer on platform like wndows.
when i add some new gems with gem install , this new gem go directly to the path of jruby gems library and not the default path of ruby ... 
some tips ?

**Comment by PragTob** [comment]
Hi there,

multiple installed ruby versions on Windows is a bit of pickle... I'm no Windows expert :(

Maybe this FAQ helps you: https://github.com/jruby/jruby/wiki/FAQs#what-if-i-want-to-use-jruby-alongside-c-ruby--how-do-i-keep-from-getting-confused

Also, I believe JRuby also comes with the executables jgem etc. that use JRuby, if you fix up your path or GEM_HOME you could make it use CRuby once by default.

this also came up on my search but I believe most Windows ruby version managers aren't maintained anymore: https://rubyonwindowsguides.github.io/book/ch02-03.html

**Comment by MartinGross** [comment]
Hi,

https://bitbucket.org/jonforums/uru is maintained Windows (and cross platform) ruby version manager and works with JRuby/shoes4 on Windows.

**Comment by PragTob** [comment]
Hi there, thanks - didn't know that there was a newer one/successor to pik/whatever - thanks for the input :)

**Comment by rebelwarrior** [comment]
Did URU fix the issue? Can this issue be closed?
Btw Uru is cross platform  you can use it on Mac (it's on homebrew) or Linux as well as Windows. 
I have an ansible playbook for [installing URU](https://github.com/rebelwarrior/AnsibleUruInstall/blob/master/playbook.yml) and ruby-build on Ubuntu.

**Comment by PragTob** [comment]
Thanks for pinging about this, nobody complained again so I'll close this out waiting to be reopened if a new issue pops up :)
