### ISSUE TITLE
Question about App Specs

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#1141]
I have a couple of questions about the specs over in [app_spec](https://github.com/shoes/shoes4/blob/master/shoes-core/spec/shoes/app_spec.rb).

1. Couldn't we replace [these](https://github.com/shoes/shoes4/blob/master/shoes-core/spec/shoes/app_spec.rb#L37-L51) with something like [this](https://github.com/shoes/shoes4/blob/a906a5d797d6c8eab4adb30a305d181817a2f456/shoes-core/spec/shoes/shared_examples/dsl/star.rb#L24-L28)?

2. What's `:qt` doing [here](https://github.com/shoes/shoes4/blob/master/shoes-core/spec/shoes/app_spec.rb#L37)? I can't find anything about that in the docs...

**Comment by jasonrclark** [comment]
1. Yes, those two ways of stating it are equivalent. That said, RSpec 3 actually removed `its` from the core, and we're using a gem (`rspec-its`) to put it back to keep supporting our existing specs. I don't feel strongly about it either way, but following along with RSpec's own patterns will probably be better in the long run.

2. Symbol values passed to the `it` call get tagged in the metadata for that particular spec, and are used for filtering sets of specs to run. You can see a clearer example of this at https://github.com/shoes/shoes4/blob/b527f6ffa1e1dc7f94411a68973600e87a83b2c2/shoes-core/spec/shoes/app_spec.rb#L248 (which I believe might not actually be correct anymore, but it shows how the mechanism works). The exclusion is then actually set for running specs over in https://github.com/shoes/shoes4/blob/b527f6ffa1e1dc7f94411a68973600e87a83b2c2/tasks/rspec.rb#L43. All that said, nothing appears to actually use the `:qt` filtering at this point. Probably a holdover from the early days.

**Comment by KCErb** [comment]
Thanks!
