### ISSUE TITLE
Can't package to .app

### ISSUE THREAD

**Issue by seanosaur** [shoes/shoes4#1145]
As the title says, I can't package to `.app`, but `.jar` will complete.

I'm receving this error on OS X:

`Zip::Error: Zip end of central directory signature not found`

**Comment by PragTob** [comment]
Hi there,

thank you for your bug report!

Could you please supply the commands that you've used (e.g. both app and jar) and maybe even a sample script to package so we can check it out and try to reproduce the errors? :)

Tobi

**Comment by seanosaur** [comment]
Here's a screenshot of me using both app & jar commands found in the README (https://github.com/shoes/shoes4#packaging-a-shoes-app).

**Comment by wasnotrice** [comment]
@seanosaur looks like it's failing when unzipping the .app template file. At the very least, it should give a reasonable error message (not this). What happens if you clear `~/.furoshiki/cache`, so you get a fresh download of `shoes-app-template.zip`?

**Comment by seanosaur** [comment]
@wasnotrice that appears to have solved my issue, thank you.

**Comment by PragTob** [comment]
Thanks for jumping in @wasnotrice :)

Just tried packaging, "sadly" it works fine for me :)

**Comment by PragTob** [comment]
Seems to be fixed :)
