### ISSUE TITLE
Runnign scripts through ruby myscript.rb is broken

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1146]
Take this script:

```
require 'shoes'

Shoes.app {button 'hello'}
```

trying to run it via `ruby my_script.rb` (or prepended with `bundle exec`) yields this error:

```
NameError: uninitialized constant Shoes::Swt::App
  const_missing at org/jruby/RubyModule.java:2733
      setup_gui at /home/tobi/github/shoes4/shoes-core/lib/shoes/internal_app.rb:30
     initialize at /home/tobi/github/shoes4/shoes-core/lib/shoes/app.rb:48
            app at /home/tobi/github/shoes4/shoes-core/lib/shoes/app.rb:19
```

Running through `bin/shoes` of course works fine. I'm guessing that when reworking the backend selection we forgot about good old running scripts with ruby and requiring shoes. We should get that back to possible again :)

Buck courtesy of [this stackoverflow](http://stackoverflow.com/questions/31040742/shoes-cannot-find-its-own-backend) - I'm going through stackoverflow right now searching for these kind of things (really I'm just putting of unpleasant work but whatta you know.. :) )

Tobi

**Comment by jasonrclark** [comment]
Good catch on that. I think I understood at the time that we made some changes that this was possible, but given the requirement for Mac to run through `bin/shoes` to get the thread access right, it didn't seem quite as important at the time to solve.

But now that we have #1115, though, you can just start up everywhere (paying a price for a second JRuby startup on Mac, of course). Hurray! PR incoming...
