### ISSUE TITLE
Unable to install pre version

### ISSUE THREAD

**Issue by aditya-kapoor** [shoes/shoes4#1149]
```
gem install shoes --pre
ERROR:  Error installing shoes:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Users/adityakapoor/.rvm/gems/ruby-2.1.2/cache/jruby-jars-1.7.21.gem
```

**Comment by PragTob** [comment]
Hi there and thanks for your report,

you try to install shoes on ruby 2.1.2. Shoes is a JRuby only gem as [stated in the README](https://github.com/shoes/shoes4#get-a-jdk-and-jruby). Please install JRuby and try again :)
