### ISSUE TITLE
Get information about screen dimensions through Shoes?

### ISSUE THREAD

**Issue by michaelfward** [shoes/shoes4#1150]
I have been digging through the code base for the past couple days (just made my upgrade to Shoes 4 this morning), trying to get the feel for the project, and I've had one thing sort of troubling me. Is there any way to reliable determine dimensions of the users screen, so that the buttons and whatnot on Shoes can be written to fit the window perfectly? For example, I used the buttons and a couple ugly hacks to create a "toolbar" type deal with File, Edit, etc options that you would find in most programs with a GUI. I really want to use Shoes regularly for my projects that require a GUI, but this is one small thing that bothers me enough to give me pause. For instance, I am currently initializing my GUI to be run in certain dimensions and then hard coding all of the elements dimensions in to be proportional to that, but if someone were to run my code with different screen dimensions than I, I'm not confident that my code would withstand that test and that kind of defeats the purpose. Any ideas?

By the way, I'm not very active in the open source community and am just starting out, so sorry if this was out of context / the wrong place to ask. 

Cheers!
Michael

**Comment by PragTob** [comment]
Hi there!

Nice of you to check out shoes :)

So what are you looking for - the dimensions of the application window or of the user's display?

Getting the dimensions of the app should be rather easy, can't check right now but `app.width`/`app.height` should do the trick. Also you can use relative values for sizing e.g. a value of `0.1` means 10 percent of the width/height of the parent container.

As for the user's screen size/resolution we have no way to provide that value right now, but it sure seems like a good addition :)

Hope that helps!

Tobi

**Comment by PragTob** [comment]
Here is an example that might help, show casing getting the data from `app` and using the relative sizes.

```ruby
Shoes.app do
  flow width: 0.2, height: 0.4 do
    background lightgreen
    button 'report' do
      alert "#{app.width}x#{app.height}"
    end
  end
  flow width: 0.8, height: 0.6 do background yellow end
end
```

**Comment by KCErb** [comment]
Hi @michaelfward!

About a year ago I sketched out a helper for using a Bootstrap-like grid system in Shoes that I called Boots: https://github.com/KCErb/boots

I *do* plan to pick it back up one day (just like regular Shoes development) but I haven't looked at it in a while. Perhaps it can give you a direction to go / code to copy+paste? The samples worked last time I checked so you can just run one of those and resize the screen to see what this offers.

If you look around you'll see I even started work on nav / navbar stuff but it looks like I didn't finish.

**Comment by PragTob** [comment]
I opened #1157 to get the info about screen resolutions - for the responsive stuff I hope the pointers we gave hear should help you @michaelfward - if not reopen/comment/make a new issue :)
