### ISSUE TITLE
Remove .furoshiki/cache from shoes-package

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1153]
Noticed we've got a large file that snuck into the source tree, and hence into the `shoes-package` gem: https://github.com/shoes/shoes4/tree/master/shoes-package/spec/.furoshiki/cache

This might have to do with where we download during tests, so make sure that we don't re-download on every test run after we get rid of this. Might be acceptable to download once per user to the standard location, though.

**Comment by PragTob** [comment]
Taking a stab at it
