### ISSUE TITLE
Mailing List question

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes4#1160]
The librelist mailing list appears to not be working.  Messages I've sent are not in the archives and it's been months since  I've seen anything. Can someone fix that?

I'm considering hosting a bbpress forum for Shoes (any version) at my website  so folks that are not github savvy can have a place to ask questions, request features.  I want to know what they are stumbling over and what they'd like to see in the future.  Shoes 3.2  is being downloaded and installed and I can see from the server logs, people are packaging their scripts. More than I expected.

I'm willing to admin/moderate the forum since bbpress is just a wordpress plugin and the anti-spam, anti-hacker defenses for Wordpress are pretty good. 

What do you think of the idea?

**Comment by PragTob** [comment]
Hi @ccoupe !
Thanks for nudging about this, yes the mailing list seems to be down :( I'll try to get in touch with Zed Shaw - librelist has been sort of a source of constant problems so something else would be nice.

google groups is the common solution for mailing lists, but I know lots of people have objections there (and the interface is a horror) sort of.

I like [discourse](http://www.discourse.org/) and I heard that by now it has a very good email interface. But I think we'd need to host it ourselves which is a bummer and incurs costs.

Personally I don't like bbpress and am unsure about the email interface.

Any other ideas for communication forums? @jasonrclark

**Comment by ccoupe** [comment]
A mailing list is the better tool IMO but  they can be pain to deal with. 

I could run phpBB  which is a little more familiar to most folks but there's a lot of overhead getting that setup and maintaining it. The manual is 132 pages long (but they have one!). That's too much work for a small number users.

Yes, bbpress is not as user friendly since it shares the blog's theme but it is easy to setup
http://walkabout.mvmanila.com/forums/forum/shoes/. If you want to play with it. It's only a test. The email notification check box is at the end

 I might dig into Mailman. It used to run on my web hosting site.

**Comment by jasonrclark** [comment]
Those cover the main options I can think of. Something email compatible is strongly preferable to my usage--it's hard enough to keep up, even at a low volume, unless the messages are coming to me.

Appreciate you bringing it up @ccoupe. Honestly, if you're doing the setup, I'm happy to see anything that gives folks more outlets for chatting about shoes. Having one central source has rarely been the Shoes way anyhow :)

**Comment by ccoupe** [comment]
It's been a while so I assume Zed didn't fix anything to Tobias doesn't have anything to report.  Running Mailman on my host should not be that much trouble for me. Everyone will have to subscribe to it since my desire  to deal with older subscriber lists and archives is low.

**Comment by ccoupe** [comment]
Let's see what happens. Subscribe by visiting  http://lists.mvmanila.com/listinfo.cgi/shoes-mvmanila.com or you can send an email to shoes@lists,mvmanil.com with 'subscribe' in the subject line and you'll get instructions to the same place.  I  think.

**Comment by jasonrclark** [comment]
Sent a subscribe to it, and although it's pending on being accepted, looks like it's working so far.

**Comment by ccoupe** [comment]
@jasonrclark - there is an issue with sending email with subscribe - I've managed to lose your request.  Please try the website http://lists.mvmanila.com/listinfo.cgi/shoes-mvmanila.com

**Comment by wasnotrice** [comment]
Hey Cecil, I was able to subscribe no problem. Not sure what I might have done differently than Jason. But thanks!

Eric
