### ISSUE TITLE
Running script with require "shoes" does not find backend

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1169]
**Setup:**
 * Windows 10 PC (might also have been Windows 8)
  * Install jruby 9.0.1.0
  * `gem install shoes --pre` (i.e. used pre 4, might be there in master)
  * script:

```ruby
require 'shoes'

Shoes.app {}
```

**Run via:** `jruby script.rb`

**Expected:** Window pops up

**Actual:** Undefined constant `Shoes::Swt::App`

**Synopsis:** The backend was neither loaded nor initialized. I.e. modifying the script to be:

```ruby
require 'shoes'
require 'shoes/swt'
Shoes::Swt.initialize_backend

Shoes.app {}
```

worked.

---------------------------------------------------------------------------------------------------------------------------

Not 100% sure it's a Windows thing, I'm just pretty damn sure it works on Linux (just tried it out, well master but whatever) so of course, Windows is to blame :P Will try to reproduce another time.

Happened while showing shoes to a beginner, oh what fun debugging and what little learning we achieved.

**Pro tip:** Our `shoes` executable works on Windows. Just use that.

**Comment by jasonrclark** [comment]
Might be a diff between master and pre4... https://github.com/shoes/shoes4/issues/1146

That fix and the jruby-complete are part of why I want pre5 to go soon.

**Comment by PragTob** [comment]
ugh definitely a duplicate.. I felt like there was something, but I thought we fixed it in pre4. Yep pre5 soon sounds good, I hope I get time tomorrow morning to check jruby-complete on Windows.
