### ISSUE TITLE
simple-guess-game shows answers when started

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1174]
To duplicate:

```
bin/shoes samples/simple-guess-game.rb
```

Result:
![image](https://cloud.githubusercontent.com/assets/130504/11449153/511dccd2-9520-11e5-94b0-1100d359e995.png)

The `hide` call on [this line](https://github.com/shoes/shoes4/blob/2085c9e2b3babb69e13f517a31f398bdf5ed872e/samples/simple-guess-game.rb#L7) ought to work. Not sure why it isn't.

**Comment by PragTob** [comment]
:| thanks for digging that uo!

**Comment by PragTob** [comment]
I'd assign that to pre5 as I'd rather not have a regression, of course only if we get to it :)

**Comment by PragTob** [comment]
It seems that from somewhere the visibility value is reset to false:

```
It is there Shoes::Image and is visible: true and 12600
It is there Shoes::Image and is visible: false and 12600
true
false
It is there Shoes::Image and is visible: true and 12600
It is there Shoes::Button and is visible: true and 12602
It is there Shoes::Image and is visible: true and 12600
It is there Shoes::Button and is visible: true and 12602
It is there Shoes::Image and is visible: true and 12604
It is there Shoes::Image and is visible: false and 12604
true
false
It is there Shoes::Image and is visible: true and 12604
It is there Shoes::Button and is visible: true and 12606
It is there Shoes::Image and is visible: true and 12604
It is there Shoes::Button and is visible: true and 12606
```

Also, we end up in the `update_visibility` code a whole lot (last number are IDs) - i.e. 4 times for each image o_O I'd expected it one time. Interesting.

**Comment by PragTob** [comment]
Putting it inside a container seems to make it visible:

```ruby
LOGO_IMAGE_PATH = File.expand_path(File.join(__FILE__, '../../samples/loogink.png'))

Shoes.app do
  stack do
    im = image(LOGO_IMAGE_PATH).hide
    p im.visible?
    button 'im' do p im.visible? end
  end
end
```

remvoe the stack, it's not visible, with the stack, it is. And I had my money on the Widget, damn it!

![surprise](https://media.giphy.com/media/CdXIrikpXFqhO/giphy.gif)

**Comment by PragTob** [comment]
```ruby
class Shoes
  module Swt
    class Slot
      # This is more like a temporary work around until slots have a real
      # backend representations that can just hide their contents all together
      # I decided to put this logic in the backend since the hiding is a backend
      # responsibility, although this is more DSL code
      # #904 #905
      def update_visibility
        if dsl.hidden?
          dsl.contents.each(&:hide)
        else
          dsl.contents.each(&:show)
        end
      end
    end
  end
end
```

GGGGNNNAAAARRRGGGGHHHHHHHHHH.

Now what do we do? We need to only trigger this if the visibility changed... or well the backend solution as proposed/discusssed in #905 

I might take a look later on, this seems like a more wholesome fix to only trigger that code in certain circumstances... which is sort of impossible due to the way we can set styles etc. :'(

**Comment by jasonrclark** [comment]
I'm not actually surprised to get `update_visibility` calls when there hasn't actually been a change. Maybe we need to handle that within the method itself (at least to keep this hack alive)? If so, how does #1177 look?

#905 will deal with this for control-based elements, but I'm not sure whether that will help painted elements (text and art). Depends a lot on how the painting interacts with the newly added `Composite`'s for containment.

I suspect we might end up needing/wanting a more nuanced visibility model. Rather than modifying the elements themselves and tromping state, we'd need to consider their ancestors' visibility as well.
