### ISSUE TITLE
Didn't we want to handle all styles setting through style?

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1176]
Hey @KCErb @jasonrclark 

question: I thought we wanted to handle all styles changing through the `style` method although I vaguely remember that I might have been opposed to that.

i.e. in our visibility code we do:

``` ruby
      def hide
        style[:hidden] = true
        update_visibility
      end
```

which is arguably faster (might need/should do a benchmark on that) but also a lot harder to trace (no real entry point when changes occur).

Does anyone remember what we decided?

Thanks + cheers,
Tobi

**Comment by KCErb** [comment]
Sounds right to me . . .

**Comment by jasonrclark** [comment]
(Link for further reference: https://github.com/shoes/shoes4/blob/9b8f5b5eddb37f9cbce68465cc400846ae7cc0a2/shoes-core/lib/shoes/common/visibility.rb#L6)

Agreed that it seems like we should be running through styles. I suspect this just got missed in the styling passes prior, although will be worth testing to ensure there aren't other side-effects.

There almost certainly is a perf cost, but hiding/showing shouldn't be a super-frequent thing so I'm good with it until it's shown to be a problem.
