### ISSUE TITLE
Ditch JRuby 1.7 in favor of 9k? (also means dropping 1.9 in favor of 2.x)

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1179]
1.7 still receives maintenance releases but 9k is the way forward. If we dropped it we could make the README clearer as we're only talking about one JRuby version and its requirements then. Moreover, we could use shiny new Ruby 2 features.

It'd require shoes users to have a JDK 7+ though.

I'm gonna leave this open for a while to gather a wide range of feedback. :)

**Comment by KCErb** [comment]
Sounds good to me!

**Comment by jasonrclark** [comment]
I was actually thinking about this over the weekend as well. Noticed that our main tests on Travis are running 1.7, and the others are jruby-head which had some hiccups lately :/ 

I'd be completely on-board with just going 9k. JDK 7 doesn't seem at all onerous as a requirement, and by the time we hit a full release for Shoes it'll be even more reasonable.

Definitely leave this for further discussion, but maybe with `pre6` we could flop over?

**Comment by PragTob** [comment]
@jasonrclark yes the travis thing is a nuisance I haven't yet fixed up... the problem is a lack of rvm updates there so jruby-9 install jruby-9-pre1 or something... a friend sent me an undocumented possible fix that I have yet to apply but maybe JRuby has also been properly updated in the meantime.

**Comment by PragTob** [comment]
I fixed travis up and I feel inclined to revisit this and drop 1.7 since some dependencies now apparently fail as show cased by #1234

**Comment by PragTob** [comment]
As seen in #1246 rubocop now fails on us, so I want to move forward with this :)
