### ISSUE TITLE
Make bash script recognize i386 mac as a mac and not as Linux 

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1180]
.@lmrodriguezr  posted a couple of bash setting he had to have in order to [get shoes running](http://pastebin.com/a0LihAx1)

```
export JRUBY_OPTS='-J-XstartOnFirstThread' # Just to remove annoying warnings
export PATH="/usr/local/Cellar/jruby/9.0.3.0/libexec/bin/:$PATH" # I installed jruby from homebrew
export MACHTYPE=darwin-x86_64 # the default is i386, which makes shoes believe it's a linux and use readlink -f
alias ruby=jruby # I also have ruby installed
alias gem=jgem
```

This issue is about the third one of those, as I think that's the only one we can fix. The first one should be fixed when using the `bin/shoes` script, but maybe detection is broken there as well so it'd be the same problem

**Comment by lmrodriguezr** [comment]
Same issue with `bin/shoes`. The problem is in [shoes-core/bin/shoes-stub:45-51](https://github.com/shoes/shoes4/blob/master/shoes-core/bin/shoes-stub#L45). Perhaps it should use `uname` or `$OSTYPE` instead of `$MACHTYPE`?

**Comment by jasonrclark** [comment]
@lmrodriguezr What values do you get reported for `$MACHTYPE` and `$OSTYPE` on your machine?

@PragTob do you get a value for either of those when you're on Linux?

**Comment by PragTob** [comment]
```
tobi@tobi-desktop ~ $ echo $OSTYPE
linux-gnu
tobi@tobi-desktop ~ $ echo $MACHTYPE
x86_64-pc-linux-gnu
```

**Comment by lmrodriguezr** [comment]
```bash
$ echo $OSTYPE
darwin14
$ echo $MACHTYPE
i386
```

**Comment by jasonrclark** [comment]
Since we're giving `pre5` another week to look at a few things, put up #1196 which should address this. @lmrodriguezr any chance you could test?

Confirmed locally on my 64-bit Mac + VM Ubuntu. (Windows is unaffected since it doesn't run `shoes-stub` to begin with).

**Comment by lmrodriguezr** [comment]
I confirm, #1196 solves #1180 in my box.
