### ISSUE TITLE
Check packaging with installed executable

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1181]
We've gotten [some hint](https://github.com/shoes/shoes4/issues/1148#issuecomment-161430317) that packaging might not work properly when using the installed executable. However, that it does work with the local one in the shoes repository.

Please try that out and see which of those is true :)

**Comment by jasonrclark** [comment]
Started digging into this a little, and ouch, I think getting packaging back to a working state is going to be a big job. I think what I'll do is cut a release pretty soon with what we've got done for `pre7`, and declare `pre8` the big "get packaging on its feet" version and focus in there. Sound cool @PragTob?

**Comment by wasnotrice** [comment]
It will be a big job for sure. it might even be worth making packaging a 4.1 feature and just acknowledging that it will be missing in 4.0.

**Comment by jasonrclark** [comment]
Yeah, that's attractive in a sense, although it doesn't quite feel like Shoes without packaging. That's one of the things that makes it special.

Given my not-so-secret target of getting to 4.0 sometime late next year, there's still time to investigate more, but will keep the punt to 4.1 in mind if things get too hairy.

**Comment by PragTob** [comment]
The eternal when is packaging going to drop discussion/thoughts :)

Sounds cool, I was always on the packaging might be 4.1 side of things but concur that it's a massively important feature and doesn't feel like shoes without it.

:+1: for pre7 soon and packaging at a later point :)

Thank you all!

**Comment by jasonrclark** [comment]
With #1325 I was able to use the `shoes` executable from a local gem build to run packaging outside of the Shoes directory (and without any `Gemfile` present).

I'll be testing this further with the `pre8`, but for now looks like we're generally back on an 👌 for the gem running packaging.
