### ISSUE TITLE
Shoes stops working after closing shell

### ISSUE THREAD

**Issue by paynito** [shoes/shoes4#1185]
I was just able to run `$shoes vjot.rb`
a pretty gui popped up.
   and then I restarted my terminal and now that same command gives
 `zsh: command not found: shoes`

do I have to
`export PATH=/Users/AbuDavid/.rvm/gems/jruby-9.0.1.0:$PATH` and
`export JRUBY_OPTS=-J-XstartOnFirstThread`
or something?  It's so strange.  I had shoes 2 mins ago.

**Comment by paynito** [comment]
fixed it by running
`brew install jruby`
`gem install shoes --pre`
`shoes vjot.rb`
now it works
this is the example from 
https://github.com/shoes/shoes4/blob/master/samples/good-vjot.rb
don't know why I had to reinstall after closing and reopening iTerm, 
but never mind.

**Comment by PragTob** [comment]
Hi there, that is strange... please let us know if it happens again in some sort of reproducible way :)

**Comment by paynito** [comment]
verbose
shoes vjot.rb
Selecting shoes-swt backend to use. This is a one-time operation.
warning: --1.9 ignored
Ignoring shoes-core-4.0.0.pre4 because its extensions are not built.  Try: gem pristine shoes-core --version 4.0.0.pre4
2015-12-04 10:21:17.316 java[70462:530652] *** WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
