### ISSUE TITLE
image inherits alpha from last background call

### ISSUE THREAD

**Issue by lmrodriguezr** [shoes/shoes4#1190]
This is a bit odd, and I suspect it's not an intended behavior (plus I couldn't find it in the docs), so I'm gonna guess it's a bug. Take a look at this little program (to be executed from the shoes4 dir):

``` ruby
Shoes.app do
   stack margin: 40 do
      stack{ background rgb(1.0,1.0,1.0,1.0) }
      stack do
         title "Now I'm here"
         image("samples/avatar.png")
         para "zoot!"
      end
      stack{ background rgb(1.0,1.0,1.0,0.3) }
      stack do
         title "Now... sorta"
         image("samples/avatar.png")
         para "zap!"
      end
      stack{ background rgb(1.0,1.0,1.0,0.0) }
      stack do
         title "Now I'm not"
         image("samples/avatar.png")
         para "zouk!"
      end
   end
end
```

This how it looks like:
<img width="712" alt="screen shot 2015-12-06 at 5 33 57 pm" src="https://cloud.githubusercontent.com/assets/12363/11616082/c04e9ebc-9c3f-11e5-9ef7-47efd5615537.png">

What this means is that the only way to put an image with `alpha=1.0` inside a container with `alpha < 1.0` is by adding an "invisible" `stack{ background rgb(1.0,1.0,1.0,1.0) }` before the image.

**Comment by jasonrclark** [comment]
That's totally a :bug: Nice catch and great sample!

**Comment by PragTob** [comment]
Thanks, great bug report! :D 

If I were to guess, I'd say that the graphics context doesn't correctly reset alpha but I'm probably wrong...
