### ISSUE TITLE
expert-minesweeper causes strange reflow when bomb is found

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1192]
Hard to describe all this - but when I start up expert-minesweeper-adjusted.rb and play it a bit and I find a bomb, the moment the alert goes up it looks like the whole background is redrawn or at least reflowed/repositioned,

Does anyone get that as well or should I make a video to show what I mean? :)

**Comment by jasonrclark** [comment]
Can confirm I've seen a flash before when things are finishing up. Not the first time that dialog popups have screwed with stuff drawing stuff :(

**Comment by jasonrclark** [comment]
After merging #1310 and moving back to the unadjusted minesweeper, I'm not seeing this bug anymore. Woot!
