### ISSUE TITLE
Margins for slot and background broken (samples/good-vjot)

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1193]
![selection_024](https://cloud.githubusercontent.com/assets/606517/11635302/165e81a6-9d16-11e5-8948-eb729c4d6100.png)
(Shoes 4 to the left, 3.2 to the right, if you go back to #255 you see that it used to work)

Might investigate further later on, seems like an annoying breakage :(

**Comment by PragTob** [comment]
It seems like we partly ignore margins when drawing backgrounds/borders in shoes 4:

```ruby
Shoes.app do
  stack margin: 20, height: 100 do
    background green
  end

  stack margin: 40, height: 100 do
    background blue
  end
end
```

![selection_027](https://cloud.githubusercontent.com/assets/606517/11637401/6fb72130-9d21-11e5-9461-c179fbb165a4.png)

(Shoes 4 to the left, 3. 2 to the right which looks about right)

**Comment by PragTob** [comment]
Okay I got this figured out... we didn't grab the margins of the parent which lead to us failing here. Let's see if I can cook up a complete fix today.

![shoes 4 _028](https://cloud.githubusercontent.com/assets/606517/11638156/9e0f7308-9d25-11e5-97c7-aad42f701264.png)

**Comment by PragTob** [comment]
Current Status: Why the hell did past Tobi think these things were a good idea? Why the hell should we not inherit the margin from the parent? It seems because we thought elements were going to get positioned... which they don't atm and I'm not super sure why not, this needs to be revisited.

I pushed it on a branch if you're interested, but this needs a good hard look of which I'm incapable as of now :)

**Comment by jasonrclark** [comment]
Hmm, that's tricky and I can't quite see why those changes would make the right thing happen. In my mental model, the `ParentDimension` should only be responsible for reporting a varying `extent`.

I guess I'm left wondering why we were overriding `start` at all, and by what mechanism your additional overrides work. When we're both capable of more attention, maybe one of us can explain it :dizzy_face:

**Comment by PragTob** [comment]
We overrode start et. al. to allow for custom values to be passed in to backgrounds, i.e. the background itself has an offset somehow. Which... makes sense I guess. 

I'm scared that this will entail me going back, setting up a couple of examples, compare them with shoes 3 and see what the hell we want.

I do have an idea that _should_ be rather smooth but no idea if it is the right one, it would also require the backgrounds to be positioned, which apparently they were at some point in time but I can't remember why we changed it back. Might need to search through git history and/or PRs.

**Comment by jasonrclark** [comment]
I do remember us taking the backgrounds out of positioning, since they aren't supposed to influence other elements' placement. I think https://github.com/shoes/shoes4/pull/1154 is the one you might be thinking of.

If background/border need positioning, but just should be treated as filling their parent that doesn't seem unreasonable to me.

**Comment by PragTob** [comment]
Yeah we used to have it like that, and thenw e positioned them (I believe) but didn't adjust the current_positiong going forward through the `takes_up_space?` method that asked for it. When I get to it I'll play with that. Thanks for the reference!
