### ISSUE TITLE
Most system-call methods break inside packaged OS X apps

### ISSUE THREAD

**Issue by lmrodriguezr** [shoes/shoes4#1198]
Take the following script (in short, it runs `echo 123` using different methods, and shows the errors if any):

``` ruby
require 'open3'

def show_err(err)
   para "Exception: #{err}", stroke: darkred
   edit_box err.backtrace.join("\n"), width: 1.0
end

Shoes.app do
   stack margin: 40 do
      title "Backticks"
      begin
         `echo 123`
         para "All ok."
      rescue => e
         show_err(e)
      end
      title "System"
      begin
         system("echo 123")
         para "All ok."
      rescue => e
         show_err(e)
      end
      title "IO.popen"
      begin
         IO.popen("echo 123"){}
         para "All ok."
      rescue => e
         show_err(e)
      end
      title "Open3.popen3"
      begin
         Open3.popen3("echo 123"){}
         para "All ok."
      rescue => e
         show_err(e)
      end
      title "Open3.pipeline_start"
      begin
         Open3.pipeline_start("echo 123")
         para "All ok."
      rescue => e
         show_err(e)
      end
   end
end
```

When I call it with `shoes`, or when I package with `shoes -p swt:jar` and open the jar, I get the following window (no difference between `shoes` and `jar`):
<img width="684" alt="screen shot 2015-12-08 at 3 35 24 am" src="https://cloud.githubusercontent.com/assets/12363/11651175/d6d411b2-9d5c-11e5-96ac-4c0336917fab.png">

However, when I package it with `shoes -p swt:app` and open the app, I get the following:
![screen shot 2015-12-08 at 3 37 09 am](https://cloud.githubusercontent.com/assets/12363/11651198/f9dabc42-9d5c-11e5-95d5-2bb0e27c4328.png)

With results:
- **Backticks:** Exception: Cannot run program "/bin/echo" (in directory "/Users/lmr3"): error=2, No such file or directory [Full trace](http://pastebin.com/dF0LXBup).
- **System:** All ok.
- **IO.open:** Exception: Cannot run program "echo" (in directory "/Users/lmr3"): error=2, No such file or directory [Full trace](http://pastebin.com/UBGyxtR5).
- **Open3.popen3:** Exception: Cannot run program "echo" (in directory "/Users/lmr3"): error=2, No such file or directory [Full trace](http://pastebin.com/z81n4e4p).
- **Open3.pipeline_start:** Exception: Cannot run program "/bin/sh" (in directory "/Users/lmr3"): error=2, No such file or directory [Full trace](http://pastebin.com/V7Q48Zqz).

I don't know if this is due to some sandboxing of Mac apps (hence an OS X security feature) or it's something from the shoes packaging. Note that `system` seems to work fine, but it's a limited method and for some tasks it's just not enough :-/

**Comment by PragTob** [comment]
Hi there,

thanks once again for your great bug reports :+1: 

I'll test this out on Linux after work or in the coming days to see what's happening. You are right it might be a security feature, it might also just be JRuby confusing paths and everything as it runs a packaged application or what not.

It might as well be us... I think the packaging to `app` is even more immature than our .jar packaging :)

Cheers,
Tobi

**Comment by lmrodriguezr** [comment]
FYI, I packaged a shoes app using `ant` with the `jar` and the system calls seem to work perfectly. Here's the code: https://github.com/lmrodriguezr/enveomics-gui/tree/master/dist.

The actual `.app` packaging is [here](https://github.com/lmrodriguezr/enveomics-gui/blob/master/dist/Makefile#L28), and the bundler uses [this build.xml](https://github.com/lmrodriguezr/enveomics-gui/blob/master/dist/build.xml).

This is still work in progress, so it doesn't have logo or other things that the shoes packaging do.

**Comment by PragTob** [comment]
:+1: great work - we'll definitely have a look at that when we rework packaging - this should have our answers :)

**Comment by jasonrclark** [comment]
Finally back to working on packaging, and in the meantime the underlying pieces have moved a bit and I think might have corrected this problem. It's now running on Java 8 in the packaged app + JRuby 9.1.70, which I know did significant work around process management.

@lmrodriguezr, don't know if you still have time or interest, but I'd been keen to hear whether things are better for you against the latest shoes release (4.0.0.pre8, or cloned from master). If I don't hear in a bit I'll probably close out since it seems fixed now, but happy to reopen or debug further if we can get a repro!

**Comment by lmrodriguezr** [comment]
@jasonrclark I'll be revisiting these issues for a much-needed update of one of my packages using Shoes, but I won't be able to get to this in the next couple of weeks. I'll keep an eye on these system-call-related issues and reopen them if 4.0.0.pre8 still misbehaves.
Thanks!
