### ISSUE TITLE
packaging problems (not working as gem, working as separate install)

### ISSUE THREAD

**Issue by thebenjy** [shoes/shoes4#1199]
mac os x yosemite, rvm

app working in shoes3 and can launch when installing shoes as separate binary (e.g. /tmp/shoes4)

using rvm, but i think this is mostly a bundler issue
using bundle as cannot sudo gem install a bunch of dependent gems

steps
as need to run packaging from shoes dir e.g. /tmp/shoes, I need to run bundle exec ./bin/shoes  ...
however bundle exec needs gemfile
so added my project specific gems to end of Gemfile
bundle install
then bundle exec bin/shoes

```
$ bundle install --path vendor/bundle

... installs all the gems...

$ bundle exec bin/shoes -p swt:jar ~/Documents/repositories/package-project-gui-app/sm.rb
```

**issue** it can't find shoes-swt 

```
  Error opening script file: ~/.rvm/gems/jruby-9.0.1.0@projectshoes4/gems/shoes-core-4.0.0.pre4/bin/shoes-swt (No such file or directory)
```

**remediation**

created symlink from core/bin to shoes-swt/bin

**issue**

running packaging, cannot find rake, but gem list confirms it is slisted (and correct version 10.4.2)

```
$ bundle exec bin/shoes -p swt:jar ~/Documents/repositories/packagedir/sm.yaml
Could not find rake-10.4.2 in any of the sources
```

note attempted with no bundle e.g. $ bin/shoes -p swt:jar 
i get 

```
    LoadError: no such file to load -- bundler/setup
      require at org/jruby/RubyKernel.java:939
      require at /usr/local/Cellar/jruby/9.0.1.0/libexec/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
      <top> at /private/tmp/shoes4/shoes-swt/bin/shoes-swt:5
         load at org/jruby/RubyKernel.java:957
       <top> at /private/tmp/shoes4/bin/shoes-swt:5
```

however i have done a `sudo gem install bundle; sudo gem install bundler`

**Comment by PragTob** [comment]
Thanks for the report!

The first one is already weird... there should definitely be a `shoes-swt` as it should be created the first time around. It looks a bit like it wasn't created or isn't found... @jasonrclark if we never run a shoes app but go straight for packaging, do we still create the executable?

The `bundler/setup` thing that occured last could be fixed in a recent PR where we moved that require somewhere else

However, does `bundler` show up in `gem list` ? rvm usually doesn't do `sudo gem install` but only `gem install` so my fear is that the gem ended up in the system ruby, not in JRuby.

**Comment by thebenjy** [comment]
good to know rvm does work - i'd seen issues so had tried to get it working without.
restarted fresh rvm install. shoes as a gem. all non-sudo. 
**packing now works** sorry to waste your time - not sure what i mixed up there

**now error unning java**

       ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- shoes

opening the jar file however shoes is listed in the jar file (see attached file) .... i do feel like its getting closer however!
       

         $ java -XstartOnFirstThread -jar package_sm/pkg/savemailuploadgui.jar 
         Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
         Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
         Ignoring jruby-launcher-1.1.1-java because its extensions are not built.  Try: gem pristine jruby-launcher --version 1.1.1
         Ignoring shoes-core-4.0.0.pre4 because its extensions are not built.  Try: gem pristine shoes-core --version 4.0.0.pre4
         LoadError: no such file to load -- shoes
           require at org/jruby/RubyKernel.java:1040
           require at /var/folders/20/9wqryt1n76s1f0b9mpq500nc0000gp/T/jruby9024473116832615119extract/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
            (root) at file:/Users/ben.forrest/Documents/repositories/savemail/savemail-upload-gui/package_sm/pkg/savemailuploadgui.jar!/META-INF/init.rb:8
           require at org/jruby/RubyKernel.java:1040
            (root) at /var/folders/20/9wqryt1n76s1f0b9mpq500nc0000gp/T/jruby9024473116832615119extract/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
           require at /var/folders/20/9wqryt1n76s1f0b9mpq500nc0000gp/T/jruby9024473116832615119extract/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
         ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- shoes

[sm_jar_contents.txt](https://github.com/shoes/shoes4/files/57362/sm_jar_contents.txt)

**Comment by thebenjy** [comment]
I saw a comment that someone using rvm was actually using shoes as a separate install. so have uninstalled all shoes gems (shoe*, swt). installed shoes separately. repeated. *it works* , packages and jar file runs (on mac os x)

so it seems to be something with shoes as a gem.

below is difference between the 2 generated jar files (generated using shoes gem, generated using separately installed shoes)

$ diff sm_jar_contents.txt sm_jar_contents-notgem.txt 

         > # jar contents when using shoes native (not gem)
         252,253c249
         < gems/shoes-core-4.0.0.pre4/Gemfile
         < gems/shoes-core-4.0.0.pre4/Gemfile.lock
         ---
         > gems/shoes-core-4.0.0.pre4/Guardfile
         260d255
         < gems/shoes-core-4.0.0.pre4/bin/shoes-guard
         263d257
         < gems/shoes-core-4.0.0.pre4/bin/shoes-swt
         282a277
         > gems/shoes-core-4.0.0.pre4/lib/shoes/color/
         283a279,281
         > gems/shoes-core-4.0.0.pre4/lib/shoes/color/dsl.rb
         > gems/shoes-core-4.0.0.pre4/lib/shoes/color/dsl_helpers.rb
         > gems/shoes-core-4.0.0.pre4/lib/shoes/color/hex_converter.rb
         288a287
         > gems/shoes-core-4.0.0.pre4/lib/shoes/common/hover.rb
         320d318
         < gems/shoes-core-4.0.0.pre4/lib/shoes/link_hover.rb
         388a387
         > gems/shoes-package-4.0.0.pre4/Guardfile
         401a401
         > gems/shoes-swt-4.0.0.pre4/Guardfile
         423d422
         < gems/shoes-swt-4.0.0.pre4/lib/shoes/swt/common/child.rb
         753,754c752

**Comment by thebenjy** [comment]
spoke to soon. Jar file runs on mac os x no problem (i.e. java -jar xxxx). however on windows jar file fails

i noticed the jar file is not actually properly including all gems. it seems to be using the gems installed on my mac, but they are not installed on the windows machine.

i now realise the jar tf xxxx.jar is not showing the specific gems for my app (inifile, os)

i have tried a yaml file to do the packaging (attached- *format correct ?* ), but it has no difference. e.g. jar file does not include gems.

[savemail-upload-gui.yaml.txt](https://github.com/shoes/shoes4/files/57784/savemail-upload-gui.yaml.txt)

i realise i am not calling bundle exec bin/shoes .....etc . HOWEVER I cannot do this as bundle exec needs to be run from the source directory. 

if i run

       bundle exec bin/shoes ... # from /tmp/shoes  , there is no Gemfile so it will not work

if i run

       bundle exec shoes -p swt:jar package-savemail-gui-app/   # from code directory

**error** it cannot find rubygems!?

         air:savemail-shoe-gui Ben$ bundle exec shoes -p swt:jar package-savemail-gui-app/
            <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rubygems    (LoadError)
               from <internal:lib/rubygems/custom_require>:29:in `require'
               from <internal:gem_prelude>:167:in `load_full_rubygems_library'
               from <internal:gem_prelude>:217:in `try_activate'
               from <internal:lib/rubygems/custom_require>:32:in `rescue in require'
               from <internal:lib/rubygems/custom_require>:29:in `require'
               from /Users/Ben/.rvm/gems/jruby-1.7.12@global/gems/bundler-1.10.6/lib/bundler/shared_helpers.rb:1:in `<top (required)>'
               from <internal:lib/rubygems/custom_require>:29:in `require'
               from <internal:lib/rubygems/custom_require>:29:in `require'
               from /Users/Ben/.rvm/gems/jruby-1.7.12@global/gems/bundler-1.10.6/lib/bundler/setup.rb:1:in `<top (required)>'
               from <internal:lib/rubygems/custom_require>:29:in `require'
               from <internal:lib/rubygems/custom_require>:29:in `require'


**i seem to be stuck again...**

**Comment by thebenjy** [comment]
i attempted to add the gems directly to the jar

      cp .rvm/..../gems/inifile-xxx/* ./gems
      jar uf savemailuploadgui.jar gems/*
      jar tf savemailuplaodgui.jar | grep inifile

       gems/inifile-3.0.0/
         gems/inifile-3.0.0/.gitignore
         ...
         gems/inifile-3.0.0/inifile.gemspec
         gems/inifile-3.0.0/lib/
         gems/inifile-3.0.0/lib/inifile.rb
         gems/inifile-3.0.0/Rakefile
         gems/inifile-3.0.0/test/data/section.ini
         ...
         gems/inifile-3.0.0/test/test_inifile.rb

when running the jar


         air:pkg Ben$ java -XstartOnFirstThread -jar savemailuploadgui.jar
         LoadError: no such file to load -- inifile
           require at org/jruby/RubyKernel.java:1040
           require at /var/folders/20/9wqryt1n76s1f0b9mpq500nc0000gn/T/jruby8923529803821915706extract/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:121
            (root) at file:/Users/Ben/Documents/repositories/savemail-shoe-gui/package-savemail-gui-app/pkg/savemailuploadgui.jar!/shoes-app/savemail-upload-gui.rb:4
              load at org/jruby/RubyKernel.java:1059
            (root) at file:/Users/Ben/Documents/repositories/savemail-shoe-gui/package-savemail-gui-app/pkg/savemailuploadgui.jar!/META-INF/main.rb:1
           require at org/jruby/RubyKernel.java:1040
           require at /var/folders/20/9wqryt1n76s1f0b9mpq500nc0000gn/T/jruby8923529803821915706extract/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:121
            (root) at file:/Users/Ben/Documents/repositories/savemail-shoe-gui/package-savemail-gui-app/pkg/savemailuploadgui.jar!/META-INF/main.rb:1
         ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- inifile
         air:pkg Ben$ 


**so it can't find the specific app gems, in this case inifile**

**Comment by PragTob** [comment]
@thebenjy what do you mean "installed shoes separately" ? Like on it's own rvm gemset? I don't know what you mean.

Sorry for all the trouble with packaging, it is one part of the system that needs a lot of work and also hasn't been touched (in a meaningful way) in a while. One of the future releases will be dedicated to packaging but right now we are still on the "getting the shoes part" right :)

**Comment by thebenjy** [comment]
no need to apologise @PragTob totally understand. by separately i mean 'outside of rvm' i.e. git clone, cd /tmp/shoes 4, bundle install.
i then have the project separate not using shoes as a gem.

we have a shoes3 app that we cant get working on windows (it crashes the c++ redistributable "has been asked to terminate") I was hoping this would solve our problems. (have tried old versions of mscrvt.dll etc to no avail.

**Comment by jasonrclark** [comment]
I've tried to duplicate this with various setups, but haven't been able to get there. Given that @thebenjy has indicated there isn't active interest in Shoes at the moment (no worries!) I'm going to close this unless someone else can get a repro with current JRuby + configuration.
