### ISSUE TITLE
Packages ship with ruby 1.9

### ISSUE THREAD

**Issue by lmrodriguezr** [shoes/shoes4#1209]
**Disclaimer**: This is probably not a :bug:, not sure.

I need to use `Process.spawn` options in my app, which was not supported by JRuby 1.7<sup>1</sup>. This works fine with `bin/shoes` or with `require 'shoes'`, so long as I have 9K in my system. The problem comes when I try to package my app, because the jar ships with ruby 1.9.3 instead of 2.x (I believe it's jruby 1.7.23), so the `Process.spawn` options are not understood when running from the jar. Here's a tiny session:

``` bash
$> cat samples/t.rb
# Just show the ruby version
$stderr.puts RUBY_VERSION
$> # With bin/shoes it gets my system's jruby
$> bin/shoes-swt t.rb
2.2.2
$> # With a jar it runs with 1.7
$> bin/shoes-swt -p swt:jar samples/t.rb
$> java -XstartOnFirstThread -jar samples/pkg/t.jar
1.9.3
```

Is there any way to tell shoes (or furoshiki) that I want the package to ship with the jruby-jars of 9K? I saw discussions on restricting support to 9K (with 2.x) over at #1179, so I'm assuming I'm not the only one that wants to play with 9K features :)

Happy holidays `shoes-people`!

---

**<sup>1</sup>** `Process.spawn` supported options in ruby 1.9, it was just not implemented in JRuby 1.7. Some discussion on this at jruby/jruby#985.

**Comment by jasonrclark** [comment]
Thanks for the report! As you mention, I think there's something weird going on between the installed version of JRuby vs what gets into the package.

**Comment by jasonrclark** [comment]
Fixed by https://github.com/shoes/furoshiki/pull/21
