### ISSUE TITLE
Button::text=() doesn't update the text of buttons

### ISSUE THREAD

**Issue by lmrodriguezr** [shoes/shoes4#1210]
This little script shows the problem:
```ruby
Shoes.app do
   stack margin: 10 do
      @b = button("Hello") do
        stack margin: 10 do
           para strong("pre:"), @b.text
           @b.text = "Bye"
           para strong("post:"), @b.text
        end
      end
   end
end
```

Which, after clicking the button twice, looks like this:
<img width="250" alt="screen shot 2015-12-25 at 10 54 45 pm" src="https://cloud.githubusercontent.com/assets/12363/12005097/9c85013e-ab5c-11e5-816e-f1e26e4a7142.png">

As you can see, the `text` slot of the object changed, but the button itself still shows the same (original) text.

**Comment by jasonrclark** [comment]
Closed by #1211
