### ISSUE TITLE
visit doesn't remove clickable objects

### ISSUE THREAD

**Issue by lmrodriguezr** [shoes/shoes4#1212]
This is a very strange bug, that I've noticed has certain... selectivity. It doesn't seem to occur with all clickable objects, but it turns out that some objects are persistent (and clickable) after the window has been cleared out by `visit`.

I've prepared a script that showcases the bug:

``` ruby
class BadBoxes < Shoes
   url "/",     :index
   url "/(.+)", :color_rand

   def index
      stack(margin:30) do
         stack do
            background darkblue
            title "Testing blue...", stroke: white, margin: 30
         end.click{ visit "/blue" }
      end
      stack(margin:30) do
         $s = stack do
            background darkred
            title "Testing red...", stroke: white, margin: 30
         end
         $s.click{ visit "/red" }
      end
      stack(margin:10) do
         para link(strong("Green"), click: "/green")
         para strong(link("Green", click: "/green"))
         para link("Green", click: "/green")
      end
   end

   def color_rand(col)
      para.parent.hidden = false
      para link("Home", click: "/")
      stack(margin:40){ para rand(1e3), stroke: eval(col) }
   end
end

Shoes.app
```

If you run this script and click in any of the big boxes, you'll notice (unless it's something specific to my system) that the cursor keeps switching to clickable (the little hand) whenever you hover the place where the boxes used to be. Not only that, if you click there you'll see that the click event is actually fired (I've put a random number, so you can tell when the page is reloaded).

The three "Green" links show something interesting. Here's the relevant piece of code:

``` ruby
         para link(strong("Green"), click: "/green")
         para strong(link("Green", click: "/green"))
         para link("Green", click: "/green")
```

The first and the third links go away nicely when any `visit` is fired (as they should). However, the second link stays to haunt the `color_rand` page. I know that `strong(link(...))` is not proper syntax, and it's not actually rendered as `strong`, but that's actually how I found out about this bug and it might give some extra clues.

**Comment by lmrodriguezr** [comment]
By the way, I've found a workaround to this problem, but it's rather cumbersome: hide clickable objects. Here's a very manual way to do it just to showcase the workaround:
```ruby
class BadBoxes < Shoes
   url "/",     :index
   url "/(.+)", :color_rand

   def index
      stack(margin:30) do
         ($b = stack do
            background darkblue
            title "Testing blue...", stroke: white, margin: 30
         end).click{ visit "/blue" }
      end
      stack(margin:30) do
         $r = stack do
            background darkred
            title "Testing red...", stroke: white, margin: 30
         end
         $r.click{ visit "/red" }
      end
      stack(margin:10) do
         para link(strong("Green"), click: "/green")
         $g = para strong(link("Green", click: "/green"))
         para link("Green", click: "/green")
      end
   end
   
   def color_rand(col)
      para.parent.hidden = false
      para link("Home", click: "/")
      stack(margin:40){ para rand(1e3), stroke: eval(col) }
      button("Fix blue") { $b.hide }
      button("Fix red")  { $r.hide }
      button("Fix green"){ $g.hide }
   end
end

Shoes.app
```

**Comment by jasonrclark** [comment]
Haven't had a chance to look at this closely yet, but thank you for the thorough examples! This wouldn't be the first time that we've had phantom "clickable" regions left over by links, so I'm not super surprised that `visit` would unearth an incompatibility there.

Setting this for our next pre-release since I'd really like to look at it before then at least. Might be a simple fix given the work we've previously done on link clearing (i.e. #979)

**Comment by jasonrclark** [comment]
Started digging into this, and found that there are a couple things overlapping to get the bad effects you're seeing.

* Slots don't clear their clicks when being removed (which is what happens during `visit`). Non-visit example:

```
Shoes.app do
  @outer = stack do
    @inner = stack do
      background darkblue
      title "Testing blue...", stroke: white, margin: 30
    end

    @inner.click do
      puts "whatever"
    end
  end

  button "clear" do
    @outer.clear
  end
end
```

* Links that are nested within other formatting (like the `strong(link(...))`) aren't getting cleaned up properly when removed.

```
Shoes.app do
  button "clear" do
    @p.remove
  end

  @p = para(strong(link("yo") { puts "yo" }))
end
```

Running out of steam for actually PR'ing a fix tonight on any of this, but I think I see where it's going.
