### ISSUE TITLE
logo update?

### ISSUE THREAD

**Issue by traffic-camera** [shoes/shoes4#1216]
Not sure if this is the appropriate channel (I saw this discussion already):
https://github.com/shoes/shoes4/issues/3

But I think a new logo would be a great idea. The posterized .bmp logo looks _very_ 1995 and is the primary reason I always lean away from Shoes when looking at GUI toolkits. 

Compared to the quality of graphic design in the rest of the Ruby ecosystem, it really sticks out like a sore thumb. No offense intended, I just think such a small tweak could vastly improve the perception of this library.

**Comment by PragTob** [comment]
Hi there,

thanks for the nudge and the honesty :)

You are absolutely right... shoes would deserve a new appeal to look fresh and modern. Before we get to a 4.0 release we'll certainly give it more effort... I mean we'd love a new logo, but back then we found no (better) new logo. If you're an artist yourself, it'd be highly welcome though :)

Cheers,
Tobi

**Comment by jasonrclark** [comment]
While I have a soft spot for the "classic" Shoes logo, I agree it's time for an update!

With the Shoes 4 release candidate coming up and me lacking any real artistic skill, I commissioned some options from a designer (my brother @traviseugeneclark) that I'm excited about.

Two major options I'd put forward as an updated app icon. My first choice is Option 1, but let me know what you think in the comments (nudge nudge @PragTob @wasnotrice @KCErb and others!)

# Option 1 - Toe Up
<img src="https://user-images.githubusercontent.com/130504/32207539-e1364c7c-bdb9-11e7-8b06-3c7d534f5567.png" width="200" />

<img width="500" alt="finder-1" src="https://user-images.githubusercontent.com/130504/32207569-0dd43924-bdba-11e7-9637-3498b87dd034.png">

Could also play with the background color on this one. Here's what a full white background looks like:

<img width="500" alt="finder-3" src="https://user-images.githubusercontent.com/130504/32208149-dff955b2-bdbd-11e7-9b9d-db35fffec9c7.png">

# Option 2 - Full Shoe
This one is a nice callback to the original Shoes icon if we wanted to keep it a little more retro...

<img src="https://user-images.githubusercontent.com/130504/32207544-e9ae0aac-bdb9-11e7-8302-2d2f5fd171a4.png" width="200"/>

<img width="500" alt="finder-2" src="https://user-images.githubusercontent.com/130504/32207573-14483a9e-bdba-11e7-8b9b-a904dbfeea7c.png">

## Other images
Along with those, we've got a variety of other images I'm looking forward to using too, probably in a (fairly basic) website refresh in the [next couple weeks before RubyConf](http://rubyconf.com/program#session-220)!

<img src="https://user-images.githubusercontent.com/130504/32207781-6e922360-bdbb-11e7-952f-79eef1b3cad3.png" width="200"/>
<img src="https://user-images.githubusercontent.com/130504/32207782-6fcbf10c-bdbb-11e7-8720-33f0e2c33eed.png" width="200"/>
<img src="https://user-images.githubusercontent.com/130504/32207784-71cef788-bdbb-11e7-8416-cf2a157df0cb.png" width="200"/>
<img src="https://user-images.githubusercontent.com/130504/32207786-76b42700-bdbb-11e7-85de-450fb48d8ad4.png" width="200"/>
<img src="https://user-images.githubusercontent.com/130504/32207788-78b9a8c2-bdbb-11e7-970c-4ed9ab0d7531.png" width="200"/>

**Comment by ccoupe** [comment]
Your brother has skills. I kind of like the second to last of the 'others'.  A reference to the old icon but perhaps hard to render at smaller sizes.

**Comment by jasonrclark** [comment]
Yeah, the four shoes was one of his first ideas and I like it... just doesn't squeeze nicely into app icon sizes. Definitely want to find somewhere to use that one though.

**Comment by steveklabnik** [comment]
These are great! I really like the second one.

**Comment by KCErb** [comment]
I agree with @steveklabnik, though I'm not sure about the version number on the shoe. Maybe the app icon would have no number and the same graphic used in other contexts would include it?

By "not sure" I mean just that, I don't mean to imply that I lean away from it at all. I feel very enthusiastic about the new design options, the impending release, and neutral about number vs no number. :)

**Comment by traviseugeneclark** [comment]
Hello all, thanks for the feedback and for allowing me to contribute to this project. 

It seems like everyone is leaning towards the full shoe design using the classic Shoe colors. I've put together a couple different versions using that as the image, and also a take on how we could use it as the app icon.

![shoes-inline-app-icon-reversed](https://user-images.githubusercontent.com/4459233/32236292-fa1a9b52-be1e-11e7-8c90-33e926393340.png)

**Comment by PragTob** [comment]
Huh, somehow missed this but my favorite won either way :D

**Comment by traffic-camera** [comment]
Very nice.
