### ISSUE TITLE
Don't swallow painter exceptions while running tests

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1222]
Talking about [this code here](https://github.com/shoes/shoes4/blob/e22db7b713b73136294721bbc4f8f67c026c8abe/shoes-swt/lib/shoes/swt/common/painter.rb#L24-L29)

```
     rescue => e
      # Really important to rescue here. Failures that escape this method
      # cause odd-ball hangs with no backtraces. See #559 for an example.
      #
      puts "SWALLOWED PAINT EXCEPTION ON #{@obj} - go take care of it: " + e.to_s
      puts 'Unfortunately we have to swallow it because it causes odd failures :('
```

Introducing it was fairly critical, but sadly it can (and has) masked failures when running our specs. So we shouldn't swallow it and raise instead when running the tests.

I'm thinking setting some environment variable for which it then raises (might also be nice for debugging) and then automatically setting it in `spec_helper.rb` - something like that.

Any ideas @jasonrclark ?

**Comment by jasonrclark** [comment]
ENV is a sensible way to control this.

Alternatively we could extract an error handler method and explicitly override it in spec_helper.rb. Would allow tighter control on how we fail for testing purposes.

Either way this is a great idea.
