### ISSUE TITLE
Add #focussed? to retrieve whether or no an element has the focus

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1224]
We should be able to ask elements whether or not they are currently focussed, this is especially true for our inputs (edit_line and button). Therefore a method `focussed?` seems fitting that just returns true/false. Could call it `focus?` or `has_focus?` but `focussed?` sounded best to my non native tongue ;)

Originated in this stackoverflow question: http://stackoverflow.com/questions/35415114/how-can-i-bind-function-with-object-in-ruby-shoes-gui

**Comment by KCErb** [comment]
As long as we alias it with `focused` I'm in favor ;)

**Comment by PragTob** [comment]
sure thing ;) (I believe we have gray and grey as well)

**Comment by estensland** [comment]
Is this still wanted? I think I figured it out...

**Comment by jasonrclark** [comment]
Absolutely @estensland, that'd be great!

**Comment by jasonrclark** [comment]
Closed by #1489
