### ISSUE TITLE
selecting the current ruby (mri) by default

### ISSUE THREAD

**Issue by majioa** [shoes/shoes4#1225]
After trying to run the shoes from command line I got the error:

    $ bundle exec shoes bin/rssui

    Selecting shoes-swt backend to use. This is a one-time operation.
    /usr/local/home/majioa/git/rss/.bundle/bin/shoes: line 62: jruby: команда не найдена

It seem that it selecting `swt` by default and try to run `jruby`, how to select the current ruby (mri) by default?

**Comment by PragTob** [comment]
Hi there, shoes4 currently only runs on JRuby as [stated in the README](https://github.com/shoes/shoes4#installing-shoes-4). We need it to run SWT, there is multiple backends support and experimental backends for qt and opal/atom-shell, but these are nowhere near done. If you want to do something with CRuby check out Shoes 3.2 https://github.com/Shoes3/shoes3
