### ISSUE TITLE
Please help, package failed

### ISSUE THREAD

**Issue by lpniuniu** [shoes/shoes4#1232]
FanFamilydeMacBook-Air:imappush familymrfan$ shoes -p swt:app imappush.rb
Packaging swt:app...
Zip::Error: Zip end of central directory signature not found
       get_e_o_c_d at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:143
      read_e_o_c_d at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:103
  read_from_stream at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:136
        initialize at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/rubyzip-1.1.7/lib/zip/file.rb:77
              open at org/jruby/RubyIO.java:1181
        initialize at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/rubyzip-1.1.7/lib/zip/file.rb:76
              open at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/rubyzip-1.1.7/lib/zip/file.rb:96
  extract_template at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/furoshiki-0.3.1/lib/furoshiki/jar_app.rb:170
           package at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/furoshiki-0.3.1/lib/furoshiki/jar_app.rb:53
               run at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/shoes-swt-4.0.0.pre5/lib/shoes/swt/packager.rb:29
              each at org/jruby/RubyArray.java:1613
               run at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/shoes-swt-4.0.0.pre5/lib/shoes/swt/packager.rb:25
               run at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/shoes-core-4.0.0.pre5/lib/shoes/packager.rb:24
               run at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/shoes-core-4.0.0.pre5/lib/shoes/ui/cli.rb:70
            (root) at /Users/familymrfan/.rvm/gems/jruby-1.7.19/gems/shoes-swt-4.0.0.pre5/bin/shoes-swt:11
              load at org/jruby/RubyKernel.java:1087
            (root) at /Users/familymrfan/.rvm/gems/jruby-1.7.19/bin/shoes-swt:23

**Comment by jasonrclark** [comment]
Hey @lpniuniu, sorry for the long silence. Just getting back to working regularly on Shoes, and packaging in particular.

One question, do you get the same result for this if you run to build `shoes -p swt:jar imappush.rb` instead of `swt:app`?

**Comment by jasonrclark** [comment]
Checking back in, I haven't been able to duplicate this on recent versions. If there's any interest, could you try again with JRuby 9.1.7.0 and `shoes` 4.0.0.pre8 and see if it duplicates for you @lpniuniu?

If I haven't heard back in a couple weeks, I'll probably close since I can't repo, but happy to reopen or pursue with any additional info.
