### ISSUE TITLE
Calling alert from irb fails

### ISSUE THREAD

**Issue by JoyceBabu** [shoes/shoes4#1233]
I have installed `jruby-9.0.5.0` using `rbenv`. When I try to run the following code, it works as expected

```
iMac:tmp joyce$ export JRUBY_OPTS='-J-XstartOnFirstThread'
iMac:tmp joyce$ irb
irb(main):001:0> require 'shoes'
=> true
irb(main):002:0> 
irb(main):003:0* Shoes.app { button "test" }
=> (Shoes::App:0x00001074 "Shoes 4")
```

But when I try to call alert from irb, it is throwing an exception

```
irb(main):004:0> alert "Hello"
Java::JavaLang::NullPointerException: 
    from org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
    from java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:422)
    from RUBY.open_message_box(/Users/joyce/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.pre5/lib/shoes/swt/dialog.rb:37)
    from RUBY.alert(/Users/joyce/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.pre5/lib/shoes/swt/dialog.rb:9)
    from RUBY.alert(/Users/joyce/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.pre5/lib/shoes/dialog.rb:8)
    from RUBY.alert(/Users/joyce/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.pre5/lib/shoes/builtin_methods.rb:13)
    from RUBY.<eval>((irb):4)
    from org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:976)
    from org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1287)
    from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1096)
    from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1096)
    from Users.joyce.$_dot_rbenv.versions.jruby_minus_9_dot_0_dot_5_dot_0.bin.irb.<top>(/Users/joyce/.rbenv/versions/jruby-9.0.5.0/bin/irb:13)
    from java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:625)

```

**Comment by PragTob** [comment]
Hi there, thanks for reporting an issue!

I'm sorry but Shoes isn't designed to run inside irb (I don't think it's a big use case), so while I'll take this in as a wish that it worked don't expect it to be tackled soon :)

**Comment by JoyceBabu** [comment]
Thank you @PragTob . I just wanted to see how the alert box looks like, and was too lazy to create a script file and run it, hence went for the irb way ☺️. I am new to ruby, so did not understand the error message enough to know that this is an irb only issue.

If it happens only in irb, then I agree that it is not a valid use case, except for the laziest people like me :)

But since someone might find this useful while debugging, I will leave the issue open

Have a great day

**Comment by jasonrclark** [comment]
Hey @JoyceBabu ! Folks searching can still find this, even if it's closed out. Searching for "shoes ruby irb" turns this up as the second result, so I'm going to close out as I'm starting to prune our bug lists down to active stuff we're planning to fix. Thanks!
