### ISSUE TITLE
Packaged App

### ISSUE THREAD

**Issue by morganric** [shoes/shoes4#1245]
Hi Chaps,

Awesome work on Shoes4! I have a scrip that relies on one external gem, which runs well from the cmd line using shoes4. I can package the app into a .app but when I try to launch it it does nothing...

Any ideas?

Rich

**Comment by PragTob** [comment]
Hi Rich,

thanks :) Packaging is still a baby... I think we might not package to gems correctly with it yet, but to be honest I also don't see much work done on it in the near future :(

Tobi

**Comment by PragTob** [comment]
Does it also fail when you try to package as a jar?

**Comment by morganric** [comment]
@PragTob Yep, the jar wouldn't run either. Do I need to include the Gem in order to package it? Could I check on the system to see if the gem is installed, if not install it and then require it?

Rich

**Comment by jasonrclark** [comment]
Sorry for the long delay--just getting back to Shoes and focusing on packaging for a bit!

The pacakaged app/jar actually embeds the gems it needs inside it. I _think_ if you have. Gemfile in the directory where you're packaging you should get the gems picked up, but not 200% sure. Will give it a try when I can.

Is there any chance you can share the app code your trying to package? Or even just the shell of how you have things laid out?

**Comment by jasonrclark** [comment]
All right, finally got around to trying to duplicate this, and sure enough gems aren't getting picked up even with the Gemfile. That ain't right!

Duplicating app at https://github.com/jasonrclark/actively_supported

When you run it via the OS X app, you get this cryptic noise:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Users/jason/tmp/actively_supported/pkg/app.app.
```

Fortunately, the jar version is more revealing:

```
LoadError: no such file to load -- active_support
  require at org/jruby/RubyKernel.java:961
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:120
   <main> at uri:classloader:/shoes-app/app.rb:1
     load at org/jruby/RubyKernel.java:979
   <main> at uri:classloader:/META-INF/main.rb:1
  require at org/jruby/RubyKernel.java:961
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:120
   <main> at uri:classloader:/META-INF/main.rb:1
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- active_support
```

Expanding the jar as a zip, you can easily see that indeed, `activesupport` is nowhere to be found in the resulting archive.

No gumption to try and actually address this tonight, but one step forward! 👟
