### ISSUE TITLE
The download() method does not respect :headers, :body and :method styles

### ISSUE THREAD

**Issue by spidzio** [shoes/shoes4#1250]
This is what manual says.

![image](https://cloud.githubusercontent.com/assets/2708775/19646644/aa18642a-99fa-11e6-98bc-f7f0ba196d10.png)

For making http requests `open` method is used from `open-uri`. That method accepts only additional http headers (which are not passed in this case) and several other options related to proxy and http basic authentication. So it doesn't even seems to be possible to pass these styles somehow.

The issue is checked on simple web service, and manipulation of the `:headers`, `:body` and `:method` styles does't give any effect.

**Comment by PragTob** [comment]
Hi there,

thanks for pointing this out. Indeed, it's not implemented yet. For those interested it's implemented in [download](https://github.com/shoes/shoes4/blob/master/shoes-core/lib/shoes/download.rb).

Sadly, right now no one is actively working on shoes4 so it is also unlikely to make it in the foreseeable future. Sorry :(

Cheers,
Tobi

**Comment by jasonrclark** [comment]
Closed by #1343
