### ISSUE TITLE
Use frozen_string_literal: true where appropriate

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1284]
The magic `# frozen_strign_literal: true` can be used to auto freeze all strings within a file, allows us to get rid of a couple `.freeze` calls, can be done on a file by file basis, prepares for ruby 3.0 (potentially) and others :)

WDYT?

**Comment by jasonrclark** [comment]
Seems legit to me. Does rubocop pick up on the use of frozen string literals and allow you to not `freeze`?

**Comment by PragTob** [comment]
I guess we'll find out whenever we try... if it doesn't, it's a nice issue/PR :)

**Comment by jasonrclark** [comment]
As discovered in #1316, when appropriately configured Rubocop does handle it properly. In fact, there's a new cop with Ruby 2.3 mode that'll enforce this once we're ready (and maybe auto-fix?)
