### ISSUE TITLE
Testcoverage reporting is broken

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1287]
It seems like test coverage reporting is broken, maybe at the same time that I upgraded the code climate test coverage reporter...

![selection_041](https://cloud.githubusercontent.com/assets/606517/20462634/64a40fa0-af23-11e6-845b-f95d4f2f166b.png)

if you [look at the coverage](https://codeclimate.com/github/shoes/shoes4/coverage), you can see that it only counts **2** files at the moment.

So no idea what's wrong there atm... maybe some update is broken, maybe the wrong ruby version updates and doesn't send it all along.. needs further investigation.

**Comment by PragTob** [comment]
The problem seems to be with simplecov.

Running `rake spec:shoes` locally gives me 2619 / 2791 which sounds about right. Running `rake spec:swt` reports 73 / 94 for some reason :'(

so fault is most likely somewhere in SWT or in something JRuby does, might try an old version as I think it used to work. Might be related to colszowka/simplecov#524 and probably needs some tinkering...

**Comment by olleolleolle** [comment]
Ohai! You do great things here.

In order to have good numbers from coverage with JRuby, you need to tell it to count more carefully.

Add something like this to your .travis.yml

```yaml
env:
  - JRUBY_OPTS="--debug"
```

**Comment by PragTob** [comment]
@olleolleolle thanks I'll try that as well... I also just had another check and some reordering of requires has lead to requiring code before `simplecov` :| WHich is.. an embarrassing rookie mistake. Trying our my fix now and pushing then. I'll try that option nonetheless :)

**Comment by PragTob** [comment]
@olleolleolle in my testing adding the debug did not make a difference so omitting it in the PR. Still thanks a lot for dropping by :heart: Tack ska du har!
