### ISSUE TITLE
Rotate reversed vs Shoes 3?

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1288]
In writing arrow, I noticed that we might have rotate flipped?

**Shoes 3**
![image](https://cloud.githubusercontent.com/assets/130504/20513198/335d5afc-b039-11e6-9f89-9ab2e05b25a5.png)

**Shoes 4**
![image](https://cloud.githubusercontent.com/assets/130504/20513203/3e2558ae-b039-11e6-8878-eb2a5743a3a2.png)

```
Shoes.app do
  rotate 45
  rect 50, 50, 100, 50
end

```

Negating the rotation gets it pointed the same way in Shoes 4 as in Shoes 3.

**Comment by PragTob** [comment]
that is... hummm.

Yes it is different, but I'd have totally expected the Shoes4 outcome e.g. that it is rotated clock-wise not counter clock wise.

I dunno if this is worth breaking compatibility, it's also not an often used feature I guess/hope.

**Comment by jasonrclark** [comment]
Yeah, will ponder where to go with this. Popped it into rc1, so I don't feel like we need an answer right away.
