### ISSUE TITLE
Better error messages if running on unsupported Ruby?

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1300]
Per #1239, the errors you get if trying to run on MRI are definitely cryptic. Can we do any better at installation or runtime to detect what's up and point them in the right direction?

**Comment by PragTob** [comment]
definitely... I mean there is a myriad of variables where we can get it from like RbConfig, RUBY_DESCRIPTION and the like we should definitely error out nicer and link to the installation part of the README or something :)

**Comment by jasonrclark** [comment]
After some examination, this appears more slippery than I originally hoped.

Specifically we have a few places in the [main](https://github.com/shoes/shoes4/blob/3d8d2780ef72c36d89ad3413d64762726e540e1f/shoes-swt/bin/shoes-swt#L1) [executables](https://github.com/shoes/shoes4/blob/3d8d2780ef72c36d89ad3413d64762726e540e1f/shoes-core/ext/install/shoes.bat#L10) which explicitly use `jruby` from their respective shells. While changing this on Unix/Mac to just `ruby` should work fine with Ruby version management schemes I know about, it doesn't appear that'll work on Windows. 😢 

This leaves me wondering if we need to get a solution that can run outside of Ruby entirely to avoid us just failing at a shell level when trying to start up. This could be accomplished by having the `generate_backend` code create a `shoes-validate` and `shoes-validate.bat` which would appropriately (and quickly) check what we need from the shell before starting Shoes up. In the case of Unix/Mac, running `ruby --version` under JRuby is speedy (it's specially handled apparently to avoid huge JVM startup). For Windows, seems like we could just use the existence of a functioning `jruby` command to check it. (Where `shoes-backend` magically is the correct command for both Unix/Mac and Windows all at once, this sort of validation has no prayer of actually matching between the platforms 😭 )

Oh, another avenue that I went down briefly was setting the platform in the gemspec to 'java' to indicate `shoes-swt` gem is only allowed for JRuby. Unfortunately, this just gives you "unresolved gem version" messages when you try to install on CRuby... not at all the friendly experience I want for folks who may be confused about this. Seems like allowing install and then failing with a very descriptive message is actually nicer than being explicit about the platform in this case. 😿
