### ISSUE TITLE
jruby -S gem install shoes --pre on win7 error

### ISSUE THREAD

**Issue by hakehuang** [shoes/shoes4#1313]
```
C:\Users\hake\Documents\GitHub\smart_cal>shoes smart_cal.rb
Gem::GemNotFoundException: can't find gem shoes-core (>= 0.a)
  find_spec_for_exe at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems.rb:271
  activate_bin_path at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems.rb:298
             <main> at C:\Ruby23-x64\bin\\shoes-picker:22
The system cannot find the file specified.
C:/Users/hake/Documents/GitHub/smart_cal/smart_cal.rb:149:in `<main>': uniniti
alized constant Shoes (NameError)

C:\Users\hake\Documents\GitHub\smart_cal>jruby -S gem install shoes --pre
NotImplementedError: symlink unsupported or native support failed to load; see h
ttp://wiki.jruby.org/Native-Libraries
                  symlink at org/jruby/RubyFile.java:1091
  block in extract_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.r
b:388
                     each at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package/t
ar_reader.rb:65
  block in extract_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.r
b:365
     block in open_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.r
b:459
                     wrap at org/jruby/ext/zlib/RubyGzipFile.java:96
              open_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.r
b:456
           extract_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.r
b:364
   block in extract_files at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.r
b:345
                     each at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package/t
ar_reader.rb:65
   block in extract_files at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.r
b:342
                     open at org/jruby/RubyIO.java:1141
                     open at org/jruby/RubyKernel.java:306
             with_read_io at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package/f
ile_source.rb:30
            extract_files at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.r
b:339
            extract_files at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/installer
.rb:772
                  install at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/installer
.rb:302
                  install at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/resolver/
specification.rb:97
         block in install at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/request_s
et.rb:166
                     each at org/jruby/RubyArray.java:1734
                  install at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/request_s
et.rb:156
              install_gem at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/commands/
install_command.rb:205
    block in install_gems at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/commands/
install_command.rb:255
             install_gems at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/commands/
install_command.rb:251
                  execute at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/commands/
install_command.rb:158
   invoke_with_build_args at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/command.r
b:310
             process_args at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/command_m
anager.rb:169
                      run at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/command_m
anager.rb:139
                      run at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/gem_runne
r.rb:55
                   <main> at C:/jruby-9.1.6.0/bin/jgem:21
                     load at org/jruby/RubyKernel.java:977
                   <main> at C:/jruby-9.1.6.0/bin/gem:4

```

**Comment by PragTob** [comment]
thanks for the report!

Seems like some problem when trying to create the executable or well whatever we do in that post install hook? Pinging @jasonrclark

**Comment by jasonrclark** [comment]
That's very odd to be sure. Looking over the stack trace, I don't actually think we're getting to the special stuff we do during installation--this appears to be falling over prior to even unzipping the gem it's downloaded.

Are you able to successfully install other non-Shoes gems with the `jruby` command in that form @hakehuang?

**Comment by hakehuang** [comment]
deep_merge works fine with me. @jasonrclark 
$ jruby -S gem install deep_merge
Successfully installed deep_merge-1.1.1
1 gem installed

**Comment by jasonrclark** [comment]
Thanks @hakehuang! I'm going to dig up a Windows VM so I can do some testing on this myself and see if I can duplicate the problem.

**Comment by PragTob** [comment]
I was so confused right now, cause I'm the author of the `deep_merge` package for Elixir and its version number is 0.1.1 :D

**Comment by githublearner** [comment]
I am also having the same problem. I installed a number of gems with jruby successfully, but I cant install this shoes version. I am getting the exact same message described above. I am also running under Windows 7,  64-bit. I'll appreciate ANY help to get this installed.

Thank you

**Comment by PragTob** [comment]
Thank you very much for letting us know @githublearner ! We'll see if we can carve out some time and resources to check into this... might be in the next days I can see if I can reproduce on my Windows 10 machine. Install definitely used to work... grml.

**Comment by jasonrclark** [comment]
I've got my Win7 VM image downloaded but not set up yet, so I'll try to poke at that tonight.

**Comment by PragTob** [comment]
Okay I did a quick google and it seems like jruby/jruby#3905 may be the source. It suggests that you need to run it with adminstrator privileges (can you try that please?) as otherwise it can't create symlinks... (I skimmed the issue) - also warbler is mentioned there, so that might happen in one of our dependencies that is "only" needed for packaging if that's the case it might strengthen my case to create a shoes meta gem that is not dependent on packaging but only on the parts needed to execute shoes applications :)

**Comment by githublearner** [comment]
It did not work. I open a command windows as Administrator and got the same results:

C:\Windows\system32>**jruby -v**
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b15 +jit [mswin32-x86_64]

C:\Windows\system32>**jruby -S gem install shoes --pre**
NotImplementedError: symlink unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
                  symlink at org/jruby/RubyFile.java:1091
  block in extract_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.rb:388
                     each at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package/tar_reader.rb:65
  block in extract_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.rb:365
     block in open_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.rb:459
                     wrap at org/jruby/ext/zlib/RubyGzipFile.java:96
              open_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.rb:456
           extract_tar_gz at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.rb:364
   block in extract_files at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.rb:345
                     each at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package/tar_reader.rb:65
   block in extract_files at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.rb:342
                     open at org/jruby/RubyIO.java:1141
                     open at org/jruby/RubyKernel.java:306
             with_read_io at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package/file_source.rb:30
            extract_files at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/package.rb:339
            extract_files at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/installer.rb:772
                  install at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/installer.rb:302
                  install at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/resolver/specification.rb:97
         block in install at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/request_set.rb:166
                     each at org/jruby/RubyArray.java:1734
                  install at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/request_set.rb:156
              install_gem at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:205
    block in install_gems at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:255
             install_gems at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:251
                  execute at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:158
   invoke_with_build_args at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/command.rb:310
             process_args at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/command_manager.rb:169
                      run at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/command_manager.rb:139
                      run at C:/jruby-9.1.6.0/lib/ruby/stdlib/rubygems/gem_runner.rb:55
                   <main> at C:/jruby-9.1.6.0/bin/jgem:21
                     load at org/jruby/RubyKernel.java:977
                   <main> at C:/jruby-9.1.6.0/bin/gem:4

C:\Windows\system32>

**Comment by jasonrclark** [comment]
Confirmed that admin or not doesn't impact this on Win7. Also followed the Github issue train and https://github.com/rubygems/rubygems/issues/1623 appears to be involved as well.

Fiddling around, warbler is installing fine these days, but we have an unintended symlink in `shoes-core` itself in https://github.com/shoes/shoes4/tree/master/shoes-core/bin (see the `shoes` icon is different there because it just links to `shoes-stub`).

This file doesn't appear to be necessary--the real installation of things copies over from `shoes-stub` anyway with our "fun" "native" hooks during gem installation. PR on its way in, marking this for `pre7`.

Thank you @hakehuang and @githublearner for the continued feedback which kept my attention on this issue! 💖

**Comment by jasonrclark** [comment]
PR #1317 is up for this. To test I had to build new versions of the gem and install.

@hakehuang or @githublearner, if you wanted to check it out yourselves locally you'd need to:

* Clone this repo from github
* `git checkout jclark/no-symlink-for-you` branch
* In the shoes4 directory, `jruby -S bundle install`
* In the shoes4 directory, `jruby -S rake install:all` to build local copies of the gems and install them

From everything I can see, that _should_ work, and the testing I've done locally seems happy. If you get a chance to check it, much appreciated. If not, will merge away in a few days and :cross-fingers: for the upcoming `pre7` release!

**Comment by githublearner** [comment]
OK, the fix works fine on my Windows 7, 64-bit desktop.

Thank you

C:\MyData\rubyPGMS>jruby -S gem install shoes --pre
Fetching: shoes-core-4.0.0.pre7.gem (100%)
Building native extensions.  This could take a while...
Successfully installed shoes-core-4.0.0.pre7
Fetching: swt-4.4.gem (100%)
Successfully installed swt-4.4
Fetching: after_do-0.4.0.gem (100%)
Successfully installed after_do-0.4.0
Fetching: jruby-jars-1.7.26.gem (100%)
Successfully installed jruby-jars-1.7.26
Fetching: jruby-rack-1.1.20.gem (100%)
Successfully installed jruby-rack-1.1.20
Fetching: rubyzip-1.2.0.gem (100%)
Successfully installed rubyzip-1.2.0
Fetching: warbler-1.4.10.gem (100%)
Successfully installed warbler-1.4.10
Fetching: plist-3.2.0.gem (100%)
Successfully installed plist-3.2.0
Fetching: furoshiki-0.3.1.gem (100%)
Successfully installed furoshiki-0.3.1
Fetching: shoes-package-4.0.0.pre7.gem (100%)
Successfully installed shoes-package-4.0.0.pre7
Fetching: shoes-swt-4.0.0.pre7.gem (100%)
Successfully installed shoes-swt-4.0.0.pre7
Fetching: shoes-highlighter-1.0.1.gem (100%)
Successfully installed shoes-highlighter-1.0.1
Fetching: nokogiri-1.6.4.1-java.gem (100%)
Successfully installed nokogiri-1.6.4.1-java
Fetching: shoes-manual-4.0.1.gem (100%)
Successfully installed shoes-manual-4.0.1
Fetching: shoes-4.0.0.pre7.gem (100%)
Successfully installed shoes-4.0.0.pre7
15 gems installed

**Comment by hakehuang** [comment]
ok for me too. Thanks
