### ISSUE TITLE
NullPointerException on second call to Shoes.app in same script on OS X

### ISSUE THREAD

**Issue by jayjlawrence** [shoes/shoes4#1319]
I figured the my test script ( [display_npe.rb.txt](https://github.com/shoes/shoes4/files/636810/display_npe.rb.txt) ) would be acceptable. Basically it is (minus body code):

    app1 = Shoes.app { }
    app2 = Shoes.app { }

I get an NPE ( [exception.txt](https://github.com/shoes/shoes4/files/636826/exception.txt) ) when creating the 2nd app:

`Unhandled Java exception: java.lang.NullPointerException
java.lang.NullPointerException: null
    setNeedsDisplay at org/eclipse/swt/widgets/Widget:-1
         windowProc at org/eclipse/swt/widgets/Display:-1
       objc_msgSend at org/eclipse/swt/internal/cocoa/OS:-2
    setDocumentView at org/eclipse/swt/internal/cocoa/NSScrollView:-1
          setZOrder at org/eclipse/swt/widgets/Shell:-1
       createWidget at org/eclipse/swt/widgets/Control:-1
       createWidget at org/eclipse/swt/widgets/Scrollable:-1
             <init> at org/eclipse/swt/widgets/Shell:-1
             <init> at org/eclipse/swt/widgets/Shell:-1
Unhandled Java exception: java.lang.NullPointerException
        newInstance at java/lang/reflect/Constructor.java:423
  newInstanceDirect at org/jruby/javasupport/JavaConstructor.java:294
        newInstance at org/jruby/RubyClass.java:1008
               call at org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1`

I poked around in the shoes code - my hunch is that I'm irritating a SWT glitch (maybe calling it a bug is too strong). There was a somewhat similar report (only I could find) here: https://www.eclipse.org/forums/index.php/t/205090/

I did check the value of ::SWT.display that is used when creating the second app and it is returning the same object id for Java::OrgEclipseSwtWidgets::Display for both the first and second runs.

a) is this correct  usage of Shoes.app?
b) is there a way to avoid touching this issue?

Thanks!
Jay

Environment info - jruby 9.1.6.0, swt gem 4.4, java version "1.8.0_74", OS X 10.11.6

**Comment by jasonrclark** [comment]
Hi @jayjlawrence! We were actually discussing this over in #1298. It seems like we're leaning toward saying that having two top-level apps like that isn't currently supported.

That said, you can easily call `Shoes.app` again from within another app to "open another window.":

```
Shoes.app do
  para "First window"
  Shoes.app do
     para "Another window"
  end
end
```

Does that get you what you're looking for behavior-wise?

**Comment by jasonrclark** [comment]
Oh, two other things... first, great bug report and thank you for the thorough details! Second, even if this isn't supported, it's probably worth us behaving better than crashing. Seems like a very rough edge to just let things go 💥

**Comment by jayjlawrence** [comment]
Actually my intention was to speed up the testing cycle for Shoes apps. I wrote a tiny script that I would launch with Shoes ...

    while true do
      load './pw.rb'
    end

Then the "pw.rb" is my shoes code. The thinking here is that I can load the app see how it runs. Then make some code changes, close the app and *WHAMMO* she loads right back up.

Works except for this reported issue.

This could make end user development cycles go a lot faster and increase the JOY in working with Shoes.

**Comment by jasonrclark** [comment]
Great idea @jayjlawrence! I'm playing with a similar idea to speed up sample testing, and I used something like this previously to get those type of results:

```
require 'shoes'

file = ARGV[1]

Shoes.app do
  banner "Press Enter to reload #{file}"
  keypress do |key|
    load file if key == "\n"
  end
end
```

This side-steps the problem by starting up one main window, so the app you `load` isn't the main one hitting that crasher.

You could probably even put an `every` and use the `Shoes.apps` list to see whether you've got more than one and auto-launch if  you've dropped back to just the original window.

**Comment by PragTob** [comment]
Hey there, this is totally possible! Or well, from within an app you can do it, more like Jason said.

So, you can see [this sample](https://github.com/shoes/shoes4/blob/master/samples/simple_sample_executor.rb):

```ruby
Shoes.app width: 650, height: 32 do
  %w(simple_altered_para simple_border_image simple_breadsticks simple_buttons).each do |name|
    button(name) { load "samples/#{name}.rb" }
  end
end
```

I believe if you did the while loop in the program you might wait for the app to quit or something though as otherwise might just load the others all at the same time... or wait, maybe load blocks on the execution, yeah it probably does so should be fine :)

**Comment by PragTob** [comment]
god the hell damn it... double answer with Jason :)

**Comment by jasonrclark** [comment]
Twins again! \o/ 😈

**Comment by jayjlawrence** [comment]
@jasonrclark many thanks for the pointers. I am poking away at a small Shoes project in my "spare time". I will give some thought as a n00b to shoes how to implement a faster / dinner development cycle and offer my efforts back to the project.

**Comment by PragTob** [comment]
@jayjlawrence thanks a lot that's great! Hope you enjoy it, feel free to get in touch again :)

**Comment by jasonrclark** [comment]
#1328 handled this as we're planning to for now (just giving you a clear error about what's happening if you try to do two apps at the top level.) Thanks again @jayjlawrence for the report!
