### ISSUE TITLE
Where're my samples?

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1320]
In testing for `pre7` (:tada:) I did a gem install on an Ubuntu VM and promptly realized I don't have samples since I haven't cloned from Github!

Maybe we should package up the samples in `shoes` or `shoes-core` and provide a command to install them? Maybe `shoes --samples path/to/my/samples`?

**Comment by PragTob** [comment]
I like the idea. First thought was only working samples should be packaged, but by release all of them will/should work so no need to overengineer that now.

API wise I'd rather it not be a switch but a "sub command" like `copy-samples`, `samples` or `samples copy` - which makes me realize that packaging is also just a switch. I like proper sub commands better but maybe I spent too much time in elixir/mix :)

**Comment by jasonrclark** [comment]
I'm onboard with the subcommands when we get there. This also aligns with `gem` and `bundle`, and won't feel at all weird to Ruby folks. Will entail a change for packaging, but I'm totally good with that.
