### ISSUE TITLE
Button doesn't respect height on Mac

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1323]
This program:

```
Shoes.app do
  button "haha", height: 100 do
    alert "whatever"
  end
end
```

results in this on the Mac:

![image](https://cloud.githubusercontent.com/assets/130504/21071231/0c98682a-be4f-11e6-98fa-a317e92031da.png)

Look like we're getting appropriate positioning to some extent, but the element just isn't the height it's supposed to be!

**Comment by PragTob** [comment]
That's a major bug imo (Shoes apps are supposed to look the same and basic options not working is :scream: )... hence I set it to pre8 although I most likely won't be the one fixing it due to lack of Mac.

**Comment by jasonrclark** [comment]
Totally cool, although I don't think this
