### ISSUE TITLE
Check Art Element compatibility with Shoes 3

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1333]
Double-check and address any parameter incompatibilities between Shoes 4 and 3 on art elements.

* [x] arc (#1364)
* [x] arrow (#1336)
* [x] background (#1358)
* [x] border (#1358)
* [x] line (#1363)
* [x] oval (#1357)
* [x] rect (#1355)
* [x] shape (#1367)
* [x] star (#1365)

## Example, Star

Reported via https://github.com/shoes/shoesrb.com/pull/78

In Shoes 3 the following app results in the image below. In Shoes 4 we get `ArgumentError` exceptions instead.

(Oddly, Shoes 3's star seems to default out if we don't give values, unlike `arrow` which will just not paint in the absence of values. 🤔 )

```
Shoes.app do
  star fill: blue
  star 100, top: 100, points: 5, fill: green
  star 200, 200, points: 5, fill: yellow
  star 300, 300, 5, fill: orange
end
```

![image](https://cloud.githubusercontent.com/assets/130504/21295193/86433ab8-c504-11e6-8c13-a3ba630f8695.png)

**Comment by jasonrclark** [comment]
All art elements handled. Closing out!

**Comment by PragTob** [comment]
:tada:
