### ISSUE TITLE
But will it chain?

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1340]
Back in #1338 we added method chaining for `click` and `release`. What other Shoes 3 methods were chainable? Let's find them and patch up whatever we've missed!

* [x] `Shoes::Common::Changeable#change` should return element (list or input box), currently returns the block passed in
* [x] `Shoes::ListBox#choose` should return the listbox, currently returns an item array
* [x] `Shoes::Slot#clear` should return the slot being cleared, currently returns the parent stack
* [x] `Shoes::Common::Focus` should return element, returns bool
* [x] `Shoes::DSL::Interaction#keypress` returns key handler, should return element it's happening against
* [x] `Shoes::DSL::Interaction#keyrelease` returns key handler, should return element it's happening against
* [x] `Shoes::Common::Hover#leave` return array, should return element it's called against
* [x] `Shoes::DSL::Interaction#motion` returns array, should return element it's happening against
* [x] `Shoes::DSL::Style#nofill, nostroke` return nil, should return element
* [x] `Shoes::InternalApp#click, release` returns InternalApp when it should return the App for this case (other clicks and releases are fine)
* [x] `Shoes::Common::Remove#remove` should return element being removed
* [x] `Shoes::TextBlock#replace` should return element
* [x] `Shoes::Slot#translate` should return slot, returns array

**Comment by jasonrclark** [comment]
A monstrous little bit of metaprogramming to produce a list of candidate methods:

```
puts ObjectSpace.each_object(Class)
  .select {|c| c.superclass == Shoes::Common::UIElement rescue nil }
  .map { |c| c.public_instance_methods - Object.methods - 
              Shoes::Dimensions.public_instance_methods -
              Shoes::DimensionsDelegations::CANDIDATE_METHODS }
  .flatten
  .reject { |m| m.to_s.end_with?("=") || m.to_s.end_with?("?") }
  .sort
  .uniq
```

Just 113 methods to look over 😁

**Comment by jasonrclark** [comment]
Updated description with list of actionable stuff from that list.

**Comment by PragTob** [comment]
You're the best! :tada: 

Btw. we mgiht add `Hacktoberfest` Labels to some of the easier tickets like this one? :)
