### ISSUE TITLE
can't run shoes jar

### ISSUE THREAD

**Issue by RedXTech** [shoes/shoes4#1342]
I have been trying to make a shoes app but when I package it with `shoes -p swt:jar SnowShoes.rb` and try to run the file with `java -jar pkg/redxtech_snowshoes.jar`, I get an error.
Here it is:
```
Ignoring shoes-core-4.0.0.pre7 because its extensions are not built.  Try: gem pristine shoes-core --version 4.0.0.pre7
LoadError: no such file to load -- shoes
  require at org/jruby/RubyKernel.java:1040
  require at /C:/Users/redxtech/AppData/Local/Temp/jruby404529263560838882extract/jruby-stdlib-1.7.26.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
   (root) at file:/C:/Users/redxtech/RubymineProjects/SnowShoesProd/pkg/redxtech_snowshoes.jar!/META-INF/init.rb:8
  require at org/jruby/RubyKernel.java:1040
   (root) at /C:/Users/redxtech/AppData/Local/Temp/jruby404529263560838882extract/jruby-stdlib-1.7.26.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
  require at /C:/Users/redxtech/AppData/Local/Temp/jruby404529263560838882extract/jruby-stdlib-1.7.26.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- shoes
```

I have tried `jruby -S gem pristine shoes-core` and it has confirmed that shoes-core 4.0.0.pre7 has been made pristine, but the same error keeps happeneing.

If any more information is needed, let me know.

Any ideas on why this is happening?

**Comment by jasonrclark** [comment]
Thanks for the report @RedXTech!

So it turns out that this is an issue we're working on for the `pre8` release. It appears to be related to [something happening with the underlying `warbler` gem](https://github.com/jruby/warbler/issues/404) that we rely on for packaging up the jars.

Unfortunately there's not much you can do to work around it at this point, but I'm working hard on getting that release together, and will ping back here when it's ready for you to try out.

**Comment by RedXTech** [comment]
Thanks @jasonrclark !
Do you any estimates on how long it would be until pre8 is released?

**Comment by jasonrclark** [comment]
You can track the progress on [this milestone](https://github.com/shoes/shoes4/milestone/11) to see the issues remaining that I'm aiming to get done. I'll definitely be in January before it's there.

Once this is fixed on master, you may be able to get things from a local copy of the code with a little massaging. When I get the packaging issues settled, I'll be sure to chime back here with some instructions in case you want to try it out.
