### ISSUE TITLE
Packaged app failure on Windows

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1351]
After the fixes from #1345, found a following, unrelated problem with packaging on Windows. :rage1:

When trying to run a jar (built either on the Windows machine locally, or one built on my Mac, no difference) I get the following error:

```
NameError: missing class name (`org.eclipse.jface.viewers.ColumnViewerToolTipSup
port')
    method_missing at org/jruby/javasupport/JavaPackage.java:261
  <module:Viewers> at uri:classloader:/gems/swt-4.4/lib/swt/full.rb:111
    <module:JFace> at uri:classloader:/gems/swt-4.4/lib/swt/full.rb:110
            <main> at uri:classloader:/gems/swt-4.4/lib/swt/full.rb:103
           require at org/jruby/RubyKernel.java:959
           require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubyg
ems/core_ext/kernel_require.rb:68
            <main> at uri:classloader:/gems/swt-4.4/lib/swt.rb:1
           require at org/jruby/RubyKernel.java:959
           require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubyg
ems/core_ext/kernel_require.rb:68
            <main> at uri:classloader:/gems/swt-4.4/lib/swt.rb:3
           require at org/jruby/RubyKernel.java:959
           require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubyg
ems/core_ext/kernel_require.rb:133
            <main> at uri:classloader:/gems/shoes-swt-4.0.0.pre7b/lib/shoes/swt.
rb:1
           require at org/jruby/RubyKernel.java:959
            (root) at uri:classloader:/gems/shoes-swt-4.0.0.pre7b/lib/shoes/swt.
rb:2
            <main> at uri:classloader:/META-INF/init.rb:1
ERROR: org.jruby.embed.EvalFailedException: (NameError) missing class name (`org
.eclipse.jface.viewers.ColumnViewerToolTipSupport')
```

The problem roots back to this [line in the SWT gem](https://github.com/danlucraft/swt/blob/08d8f71d80f40e9d2cd75d0be8f8adad3059a120/lib/swt/full.rb#L104) which is trying to load vendored jars in the `swt` gem. When running inside the package, that gets a path like `uri:classloader:\gems\swt-4.4\lib\swt\full.rb\..\..\..\vendor\jface\*.jar` which apparently on Windows isn't resolving correctly to the jars like it does on Mac/Linux 😭 

This will likely need a fix to the SWT gem around what's busted on the `Dir` lookup there. Since we seem to be the major clients of that gem at this point, I'll dig in and get a PR together as I'm able. 🔧 

Probably also means getting ourselves past #1295 to get whatever fix gets eventually applied there :no_good_man: 

(Appears that we've been here before with https://github.com/danlucraft/swt/pull/4. :rofl: )

**Comment by jasonrclark** [comment]
Found that the behavior seems to be rooted in `File.expand_path` on Windows from JRuby itself, so logged https://github.com/jruby/jruby/issues/4418. Will see where that goes before pushing too hard on altering how `swt` does its business.

**Comment by PragTob** [comment]
Btw. dan gave me access to both the gem and the github couple of weeks back, so we can get that in easily :)

**Comment by jasonrclark** [comment]
Ah, that's great news @PragTob. Was curious how the timeline would go on that.

Depending how the JRuby issue goes, another possible approach would be to carve up https://github.com/danlucraft/swt/blob/master/lib/swt/full.rb in separate sections (`swt/core.rb`, `swt/jface.rb`, `swt/bot.rb`) `swt/full.rb` would still include them all, but Shoes could just do the basic setup and `swt/core.rb` and sidestep the whole problem.

**Comment by PragTob** [comment]
That sounds like an... excellent idea. Which would need me to branch of unless I fix the problems we're having in #1295 which should increase my motivation to do so :D

**Comment by jasonrclark** [comment]
Yeah, if we continue to have trouble we could ship a 4.4.2 on swt fixing these things. FWIW, I'm also going to try again getting a VM into the same state you're duplicating, but been distracted by other, more enjoyable coding activities 😆

**Comment by jasonrclark** [comment]
Looks like a fix for this in JRuby itself will be coming in 9.1.7.0 very soon now. I still like the `swt` fix, as it loads less stuff which seems like a win, but we may be able to call this resolved with the new JRuby 🚢
