### ISSUE TITLE
Gradient angle incorrect across many art elements

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1354]
Doesn't look like all elements are properly supporting the angle for gradient. Only the rectangle appears right to me.

With this application:

```
Shoes.app height: 800 do
  rect 100, 50, 100, 50, fill: blue..green, angle: 45
  oval 100, 150, 100, 50, fill: blue..green, angle: 45
  arrow 150, 250, 100, fill: blue..green, angle: 45
  line 100, 350, 200, 350, strokewidth: 50, stroke: blue..green, angle: 45
  star 100, 450, 5, center: true, fill: blue..green, angle: 45
  arc 100, 550, 100, 100, 0, Shoes::PI, fill: blue..green, angle: 45

  shape fill: yellow..red, angle: 45 do
    move_to 100, 650
    line_to 200, 650
    line_to 150, 750
    line_to 100, 650
  end
end
```

You get this result:

![image](https://cloud.githubusercontent.com/assets/130504/21597891/dccd3c0e-d106-11e6-8f33-936b99d43ff3.png)

## TODO
* [ ] Also check with gradients on `stroke` instead of `fill`
* [x] rect
* [ ] oval
* [ ] arrow
* [ ] line (#1100)
* [ ] star
* [ ] arc
* [ ] shape (#1101)

**Comment by PragTob** [comment]
ha, gradient is tough as I think the pattern starts repeating at some point or something... :|

But yeah, good catch!
