### ISSUE TITLE
Rotate problem in samples/simple_gradient_shapes.rb

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1366]
Noticed this in testing things... probably due to something in #1349 or the neighborhood.

```
$ bin/shoes samples/simple_gradient_shapes.rb

Unfortunately we have to swallow it because it causes odd failures :(
SWALLOWED PAINT EXCEPTION ON #<Shoes::Swt::Shape:0x749ab7b4> - go take care of it: undefined method `nonzero?' for [45, 300, 300]:Array
```

**Comment by jasonrclark** [comment]
FWIW, I can only find reference in the Shoes manual to `rotate` accepting a number for degrees. Traced the sample back to [its origin](https://github.com/shoes/shoes4/commit/bd6cbfe859f036406883b1a6bc512e7cefa76bda), which had the array but also notes in the comment that `rotate` wasn't implemented yet...

Given that, this seems like just an error in the sample with incompatible code that was quietly not doing anything until we enable rotation on shapes.

**Comment by PragTob** [comment]
So, what you are saying is we can remove the rotate call and close this? :D

**Comment by jasonrclark** [comment]
Yep. Just ran out of steam to actually do it last night.
