### ISSUE TITLE
Something that I've realized about packaging (and shoes-4.0.0.pre1.gem)

### ISSUE THREAD

**Issue by ashbb** [shoes/shoes4#138]
- gem executable command name

I'd like to name `shoes4` instead of `shoes`.
Because I want to do like this on my console window:

<pre>
    c:\tmp> shoes -v   #=> run shoes 3
    c:\tmp> shoes4 -v  #=> run shoes 4
</pre>

- file I/O

Download [this test app](http://www.rin-shun.com/shoes4/tmp/hello.zip) and save as c:\tmp\hello

Both `bin\shoes.bat -p swt:jar c:\tmp\hello\hello.rb` and `bin\shoes.bat swt:jar c:\tmp\hello\hi.rb` make a `.jar` file without any errors. But `java -Djruby.compat.version=1.9 -jar hi.jar` doesn't work and get the below error message.

<pre>
NativeException: org.eclipse.swt.SWTException: i/o error (java.io.FileNotFoundEx
ception: file:C:\tmp\hello\pkg\hi.jar!\shoes-app\man-ele-video.png (Syntax 
error: file name or directory name or volume lavel))
</pre>

In order to read a file compacted into a `.jar` file, we have to use Kernel#open. 
Please compare the code between `hello.rb` and `hi.rb`.

**Comment by jasonrclark** [comment]
I'm settled here that we won't be doing the version spanning on the command at this point.

On the image finding, it looks to be the same thing reported over on #676 (although I can't download the test app linked here anymore to be absolutely certain). Given that, gonna close this out in favor of debugging over there.
