### ISSUE TITLE
Purpose of shoes-package

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1399]
As I've started peeling away the layers around packaging, I'm having doubts about needing`shoes-package` gem.

Current dependency tree:

```
shoes-swt
-> shoes-package
    -> furoshiki
      -> warbler
-> shoes-core
```

Hints we've got an unnecessary split:

* Turns out, we aren't even using the `Shoes::Package::Jar` and `Shoes::Package::JarApp` classes at all--[we're just using the `Furoshiki` versions of them!](https://github.com/shoes/shoes4/blob/master/shoes-swt/lib/shoes/swt/packager.rb#L72-L81)
* Despite `shoes-swt` depending on `shoes-package` gem-wise, `shoes-package` is [tightly bound to the SWT backend](https://github.com/shoes/shoes4/blob/master/shoes-package/lib/warbler/traits/shoes.rb#L34)
* Removing `Shoes::Package::Jar` and `Shoes::Package::JarApp` leaves `shoes-package` with just the `Shoes::Package::Configuration` class and Warbler trait setup.
* If there's generic packaging logic to share across backends, it belongs up in `shoes-core` with [`Shoes::Packager`](https://github.com/shoes/shoes4/blob/master/shoes-core/lib/shoes/packager.rb), not separated into yet another gem.

What do you think of cleaning the cruft and hoisting those couple of bits up into a packager subdirectory in `shoes-swt`? @PragTob

**Comment by PragTob** [comment]
I believe the main reason for the split is me and my "I wanna have a shoes setup that is just there to run applications" - i.e. it's not only about code but about dependencies. You only need warbler and its many dependencies when you wanna package a shoes application, but if someone wants to publish a shoes application as a ruby gem - the people using it don't need warbler + friends + potential conflicts/setup troubles.

So afaik that's the main reason but can still be discussed :)

**Comment by jasonrclark** [comment]
Ah, that totally makes sense. In the current packaging we unfortunately don't benefit from the separation. Since `shoes-swt` depends on `shoes-package` (even if it doesn't `require` anything significant until you try to package), the packaging picks it up.

Based on this, I definitely have turned around and want to keep it, but I'll enter an item about us making sure we don't package unnecessary gems up. Thanks @PragTob!
