### ISSUE TITLE
Implement Copy and Save button for Console

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1407]
Press `Alt+/` to bring up the Shoes Console. Back on Shoes 3 it looked like this:

![image](https://cloud.githubusercontent.com/assets/130504/21001024/e6cd06d2-bcd2-11e6-8a3e-3111a1b1ce62.png)

Shoes 4's console is missing the Copy and Save buttons, and it'd be nice to have those back!

**Comment by estensland** [comment]
I am interested in helping out, so if this issue is fair game I will take a stab at it.

**Comment by jasonrclark** [comment]
It's wide open @estensland, so have at it! Let me know if there's any help I can give you on getting set up and running.

**Comment by estensland** [comment]
Thanks, I seem to have it all working. I have one dumb newcomer question, but where in the repo does it make the most sense to write specs for this?

**Comment by jasonrclark** [comment]
Not a dumb question at all, especially given that this appears to lack existing specs :|

I'd recommend that we add a spec in `shoes-core`  at `shoes-core/spec/shoes/console_spec.rb` to get it covered. Sorry there isn't preceding work there to base things off, so hit me up if you need any help with approaching tests there.

**Comment by estensland** [comment]
@jasonrclark Appreciate the offer of help! Any existing tests I can look at for pointers on how to test the code block for buttons?  Like the existing clear button:

    button "Clear", margin: 6, width: 80, height: 40, right: 10 do
       @messages.clear

       @message_stacks.each(&:remove)
       @message_stacks.clear
     end

If there are no existing tests to base off of elsewhere, I have an idea to it best covered

**Comment by jasonrclark** [comment]
@estensland I honestly can't think of another case inside of Shoes itself where we have tests against something that's running DSL code in this fashion. @PragTob any ideas there?

Look forward to seeing what you come up with!

**Comment by estensland** [comment]
@jasonrclark My first thought was just have the buttons call methods defined on the console class, so they can just be tested there. The code inside the block would not be covered, but the code called would be.

But...I am thinking now if the mock classes are only used in testing, we can assign the button's given block as an instance variable, then call the block in a spec to see if it works. It is a little more complicated, but as long as Mock::Clickable is only used by rspec, it seems to be working.

Sorry if overthinking it :man_shrugging:

**Comment by jasonrclark** [comment]
@estensland Totally not overthinking it :)

I'd probably start trying out the mocking, but if you run into any significant hurdles fall back to extracting methods and testing those. That really gets to the heart of the functionality--how does the Shoes app interact with the data we hold in the `Console` class--while the precise layout and app invocation is of less interest for testing.

**Comment by estensland** [comment]
@jasonrclark So it seems I have it working by adding an instance variable to the mock clickable class. I wrote some specs for other parts of console.rb, since I pretty much was testing them to figure out how the whole model worked any way. 

Long story short though, they are far from the best specs I have ever written. I'd like to get your feedback on the whole thing, do you prefer I post code snippets here? Or just make a pull request?

**Comment by jasonrclark** [comment]
@estensland Pull requests are great for giving it a look over. Excited to see what you came up with!

**Comment by estensland** [comment]
Sorry for delay fighting a cold, hope to have PR up tomorrow

**Comment by PragTob** [comment]
@estensland take all the time, health >>> open source :)

**Comment by jasonrclark** [comment]
Fixed by #1447. Thanks @estensland!
