### ISSUE TITLE
Apply fail fast wrapper to all eval blocks in Shoes

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1413]
Doesn't have to be a single PR. In fact, would be super happy with individual PRs against different spots.

A good example of the basic mechanics of the changes are in https://github.com/shoes/shoes4/pull/1409/commits/d01a6d4a02b065085c8bf102d5812e22af99a798

Will keep this list up to date with the various locations as we find more of them:

* [x] `Common::Changeable`
* [x] App mouse motion
* [x] App hover/leave (handled by underlying Hover module already)
* [x] App keypresses
* [x] Element hover/leave
* [x] Download callbacks (already covered because slot-bound async callbacks are wrapped!)
* [x] click handlers on `Link`, art elements, etc.
* [x] ~~`Shape`~~ Looked fine in re-testing!
* [x] ~~`App#append`~~ Looked find in re-testing!

**Comment by cursande** [comment]
Such a cool project! I'm happy to give this a shot, other than the wiki is there any other vital info re testing and developing with shoes I should know?

**Comment by jasonrclark** [comment]
Welcome @cursande! The [basic installation from GitHub](https://github.com/shoes/shoes4#installing-shoes-4-from-github) and just running `bundle exec rake` to get the specs should be plenty to get you rolling. Definitely file an issue if you run into any unexpected problems with that.

**Comment by cursande** [comment]
Hi @jasonrclark, I got a little sidetracked but I've kept my eye on this. I hadn't really encountered eval blocks before, I've been trying to apply the wrapper to `Link` click but honestly I haven't made much meaningful progress. would you prefer if I opened a new issue or pull request with what I've got in place, or since it's only a few lines just add it to this post/thread?

**Comment by jasonrclark** [comment]
@cursande Thanks for getting in touch. Even if you've only got a couple lines, feel free to open a PR with where you're at. That's the easiest way to have more detailed conversation about the code (at least for me!) if it's not too much trouble.

**Comment by jasonrclark** [comment]
Hey @cursande! Just wanted to let you know that I'm likely to pick up during the next week in the push toward 4.0.

If you're interested to work on it further that's great, but if not I'm happy to take care of it and help you find another spot to contribute to Shoes when you're ready.

**Comment by cursande** [comment]
Sorry @jasonrclark , I've been more swamped in work than I thought I'd be and overestimated myself. I'd love to contribute properly in the future but I won't be able to right now. Thanks for your patience on this.

**Comment by jasonrclark** [comment]
Thanks for letting me know, and no worries @cursande! Just didn't want any surprises if I swooped in on the issue. Look forward to seeing you around in the future!
