### ISSUE TITLE
Can't even run -_-

### ISSUE THREAD

**Issue by dwaindibbly** [shoes/shoes4#1418]
runs jruby with rbenv and java 9,
at `Shoes.app` when run:
`Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/alex/.swt/lib/linux/x86_64/libswt-gtk-4626.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
NameError: cannot link Java class org.eclipse.swt.widgets.Display (java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.swt.widgets.Display)
         method_missing at org/jruby/javasupport/JavaPackage.java:259
       <module:Widgets> at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/swt-4.6.1.1/lib/swt/minimal.rb:10
           <module:Swt> at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/swt-4.6.1.1/lib/swt/minimal.rb:9
                 <main> at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/swt-4.6.1.1/lib/swt/minimal.rb:6
                require at org/jruby/RubyKernel.java:961
                require at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:65
                 <main> at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.pre9/lib/shoes/swt.rb:1
                require at org/jruby/RubyKernel.java:961
                require at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:65
                 (root) at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.pre9/lib/shoes/swt.rb:3
                 (root) at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/shoes-core-4.0.0.pre9/lib/shoes/dsl/setup.rb:1
           load_backend at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/shoes-core-4.0.0.pre9/lib/shoes/dsl/setup.rb:26
  ensure_backend_loaded at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/shoes-core-4.0.0.pre9/lib/shoes/internal_app.rb:49
              setup_gui at /home/alex/.rbenv/versions/jruby-9.1.9.0-dev/lib/ruby/gems/shared/gems/shoes-core-4.0.0.pre9/lib/shoes/internal_app.rb:34
                 <main> at typers.rb:212`
exits without showing anything else and is not good

**Comment by PragTob** [comment]
Hi there,

you seem to be running with JRuby-head - while often rather stable could you please try to run with a non head/master release aka 9.1.8.0 ?

Seems something is wrong with the SWT library, it might be (from the stack trace) that it tries to load a newer SWT version than we expect (there seems to be an SWT library in `.swt` maybe in version 4.6.2.6 - I'm guessing, while we wanna work with 4.6.1.1). So, I guess this mixup might be faulty.

I'm running it myself on Linux 64 bit and it runs rather fine :)

**Comment by dwaindibbly** [comment]
actually i did install a newer swt library (i think) after this error and still got the same result so not to do with that,

well, what do you mean by swt library

**Comment by PragTob** [comment]
The first error part of your message comes from there:

> Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/alex/.swt/lib/linux/x86_64/libswt-gtk-4626.so which might have disabled stack guard. The VM will try to fix the stack guard now. It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

The stacktrace you posted is without line breaks, which makes it also a bit hard to read what comes from where. But that's at least a warning that could cause an error.

However, still running on a released JRuby version would be good.

**Comment by dwaindibbly** [comment]
well i can't run on a release version, it gives me an error when trying to install it :cry:

**Comment by PragTob** [comment]
And what is that error?

**Comment by dwaindibbly** [comment]
`Last 10 log lines:
Via: 1.1 326c3a58e0e7630f5d608316203a71a3.cloudfront.net (CloudFront)
X-Amz-Cf-Id: zbZxK54wQW2ib1D6GfMjQPJl70avirSLPdlGfby1GBlaGPndSZm0Rg==

/tmp/ruby-build.20170417163823.28482/jruby-9.1.8.0 /tmp/ruby-build.20170417163823.28482 ~/Code/Ruby/Testing shit
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
ERROR:  Loading command: install (LoadError)
	library `zlib' could not be loaded: java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.zlib.RubyZlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass`

**Comment by PragTob** [comment]
For which execution method does that occur? When you have JRuby installed on `gem install shoes --pre` or what are you doing?

**Comment by dwaindibbly** [comment]
uhh, that was what i got when trying to install `jruby-9.1.8.0`

and on `9.1.9.0-dev i installed the `shoes --pre` gem

**Comment by PragTob** [comment]
For the fun of it I just installed the newest JRuby and installed it myself:

```
tobi@speedy ~ $ asdf install ruby jruby-9.1.8.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.5M  100 19.5M    0     0  2326k      0  0:00:08  0:00:08 --:--:-- 2806k
tobi@speedy ~ $ cd github/shoes4/
tobi@speedy ~/github/shoes4 $ uname -a
Linux speedy 4.8.0-45-generic #48~16.04.1-Ubuntu SMP Fri Mar 24 12:46:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
tobi@speedy ~/github/shoes4 $ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
tobi@speedy ~/github/shoes4 $ asdf local ruby jruby-9.1.8.0
tobi@speedy ~/github/shoes4 $ gem install shoes --pre
# magic
tobi@speedy ~/github/shoes4 $ nano app.rb # very basic shoes app
tobi@speedy ~/github/shoes4 $ jruby app.rb # runs just fine
```

Which Java Version are you running?

**Comment by dwaindibbly** [comment]
9

**Comment by dwaindibbly** [comment]
java 9
by oracle

**Comment by PragTob** [comment]
JRuby is not ready for Java 9 yet, the whole Jigsaw things messes things up. Please try again with JDK 8 or 7.

**Comment by dwaindibbly** [comment]
right but it was working earlier

**Comment by dwaindibbly** [comment]
i get the error on java 8 as well

**Comment by dwaindibbly** [comment]
it's the exact same error

**Comment by PragTob** [comment]
What do you mean by `the error` ? The error on installing JRuby 9.1.8.0 ? If so, we're not the right address. Please try shoes again when you have a running release of JRuby working on Java 8 - either openjdk or oraclejdk - we run our tests against both. As our tests constantly run against oraclejdk 8 and openjdk 7 on Linux 64 bit it's rather unlikely that that's the problem, seems more like an installation problem related to JRuby/Java imo.

**Comment by dwaindibbly** [comment]
no
the error on running the program

not installing

**Comment by dwaindibbly** [comment]
well
and also the error on installing :sweat:

**Comment by PragTob** [comment]
Are you running the program with JRuby 9.1.8.0 and JDK 8? Also what program are you running?

Please provide more detail otherwise it is very hard for me to identify the problem.

**Comment by dwaindibbly** [comment]
stop, wait a minute, i'm trying to get 9.1.8.0 to install

**Comment by dwaindibbly** [comment]
hey do you know where i can get a  org.jruby.ext.zlib.RubyZlib

**Comment by dwaindibbly** [comment]
wait
it is a loaderror
