### ISSUE TITLE
More realistic packaging samples

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1437]
It'd be nice to have a greater variety of packaging samples that are easy to run and confirm now that we're actively working on that and testing it.

**Comment by PragTob** [comment]
great idea! :rocket: 

I think things that we might wanna cover:

* using images (and sounds?) from different locations
* multiple code files/structure
* application with a couple of run time gem dependencies
* ... ?

**Comment by jasonrclark** [comment]
Those cover a lot of the bases for me. Probably also want to do something with an `app.yaml` and some of those settings too.
