### ISSUE TITLE
Gem furoshiki having trouble on master branch. 

### ISSUE THREAD

**Issue by MichaelDimmitt** [shoes/shoes4#1444]
I think this issue is created from the recent changes happening with furoshiki for pre 10 shoes.
relates to #1424 and I am hoping it will be resolved when pre shoes 10 is released.

![screen shot 2017-06-07 at 3 04 33 am](https://user-images.githubusercontent.com/11463275/26866221-2d39eace-4b2e-11e7-8a69-80accf35035b.png)

![screen shot 2017-06-07 at 3 05 15 am](https://user-images.githubusercontent.com/11463275/26866222-2ee785f2-4b2e-11e7-9179-75f1bf55883b.png)

Let me know if you need any additional information.

using macOS Seirra 10.12.4

commands: 
```rvm jruby-9.1.10.0```
```git clone https://github.com/shoes/shoes4;```
```gem install bundler```
```bundle install```

note: I imagine I could probably clone down furoshiki, checkout the version needed and then uncomment out the line shown in the Gemfile picture. 

Anyways, I thought that I would point this issue out in case you were not encountering it. 
keep up the good work, im rooting for pre 10 shoes.

**Comment by jasonrclark** [comment]
Thanks for the report! This will get resolved once I finally get the pre10 merge done. When I merged things on furoshiki which introduced the version problem, I was expecting to follow shortly with Shoes. Unfortunately a bug has got me a bit sidetracked on merging that, though.

If you're needing to run from source, you could either 1) download as you mention, 2) add `branch: 'v0.4.0'` to the `furoshiki` line in the Gemfile temporarily to clone the right version or 3) try out the `bump-4.0.0.pre10` branch in the `shoes4` repo which is all lined up to use the newer furoshiki.

Will leave this for the moment, but close out once we confirm the merge for `pre10` gets it tidied up.

**Comment by jasonrclark** [comment]
This should all be happy now on `master`. Feel free to reopen if something else about it comes up.
