### ISSUE TITLE
Apps packaged on Windows for Mac/Linux can't execute

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1448]
The core files that need to run on these *nix-y platforms don't have the executable bits set when the package was built on Windows. Needs investigation, but not going to block `pre10` release any longer on it.

**Comment by jasonrclark** [comment]
Tested building an OSX app with Shoes 3's packaging, and it's pulling it off. It does bundle the whole thing up into a `tar.gz` and I've seen indications that some zipping software preserves/sets permissions so maybe that's part of it?

@ccoupe any chance you can point me to the secret sauce that's making that work?

**Comment by jasonrclark** [comment]
So think I found my own answer... tar.gz does preserve permissions and Rubygems has classes to write it built in. So plan will be to make tarballs for each nix OS and maybe a zip on Windows for parity.

**Comment by ccoupe** [comment]
In Shoes 3 it's in lib/shoes/packshoes.rb (line: 565- we have our own tar/writer based on Gem::Package::TarWriter  that accepts a hash of filename -> permission. Clumsy but it works.

**Comment by jasonrclark** [comment]
Fixed by https://github.com/shoes/furoshiki/pull/33
