### ISSUE TITLE
Packaging Shoes app from outside directory misses gems

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1452]
Because we just use the ambient bundle that you've got, we miss out on the `Gemfile` that someone might have defined with their packaged app if you try to package from an alternate directory. This results in require failures in the package we generate.

**Comment by PragTob** [comment]
Wondering, if we could just enforce people to package from the right directory/guide them there. Just because, you know if it turns out to be hard (which I don't think or hope) that'd be good :)

**Comment by jasonrclark** [comment]
I'll totally consider that, or something that shells out into the right directory, as fallbacks if it proves difficult enough to get where we want to be with it. Appreciate the contingency plans :)
