### ISSUE TITLE
System Tray/Menu Bar apps?

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1462]
Can we support system tray (Windows) or menu bar (Mac) apps? How would that look cross-platform?

[Some basic evidence exists that SWT can do it](http://www.java2s.com/Tutorial/Java/0280__SWT/Placeaniconwithapopupmenuonthesystemtray.htm)

cc https://github.com/shoes/shoes/issues/285

**Comment by StrangeGamerHD** [comment]
Linux has a status notifier and a tray, 
Both are exactly where Windows tray is.

A system tray is a really good idea :D

**Comment by PragTob** [comment]
Isn't this a duplicate of #219 ? :)

**Comment by jasonrclark** [comment]
Yep it is. Porting my links over there. Thanks @PragTob!
