### ISSUE TITLE
Update AppVeyor JRuby version

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1465]
Looks like it's still running back on 9.1.6.0

**Comment by PragTob** [comment]
Might be difficult. Iirc they installed JRuby just for me back in the day since installing JRuby myself dealt with weird time outs. You might still find that setup in old commits/PRs

**Comment by jasonrclark** [comment]
Good to know. There's a reason I marked it post rc1. ¯\_(ツ)_/¯
