### ISSUE TITLE
Certain methods don't work (alert, confirm...)

### ISSUE THREAD

**Issue by Jeytas** [shoes/shoes4#1494]
I've been having some issues with my Shoes. Certain methods just don't seem to work at all. When I try to create a confirm? it gives me the following error

`NoMethodError: undefined method 'confirm?' for (Shoes::App:0x00000fa0 "Shoes 4"):Shoes::App
Did you mean?  confirm
              method_missing at org/jruby/RubyBasicObject.java:1657
                                    method_missing at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/shoes-core-4.0.0.pre12/lib/shoes/app.rb:107
                                    method_missing at /home/marvin/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/forwardable.rb:189
                               block in postscreen at rerutwi.rb:95
                                        eval_block at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/shoes-swt-4.0.0.pre12/lib/shoes/swt/swt_button.rb:26
  block in _after_do_redefine_method_with_callback at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/after_do-0.4.0/lib/after_do.rb:99
                                    block in click at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/shoes-swt-4.0.0.pre12/lib/shoes/swt/swt_button.rb:31
                                    run_event_loop at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/swt-4.6.1.1/lib/swt/minimal.rb:107
                                        event_loop at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/swt-4.6.1.1/lib/swt/minimal.rb:90
                                              open at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/shoes-swt-4.0.0.pre12/lib/shoes/swt/app.rb:71
                                          open_gui at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/shoes-core-4.0.0.pre12/lib/shoes/internal_app.rb:125
                                        initialize at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/shoes-core-4.0.0.pre12/lib/shoes/app.rb:52
                                               app at /home/marvin/.rvm/gems/jruby-9.1.13.0/gems/shoes-core-4.0.0.pre12/lib/shoes/app.rb:20
                                            <main> at rerutwi.rb:108`

I have tried this on both my Laptop and my Desktop but it doesn't work on either of them. I get basically the same error when trying to create an alert.

**Comment by PragTob** [comment]
Hi there,

seems you are trying to call a method `confirm?` - it's called [`confirm`](https://github.com/shoes/shoes4/blob/67a98642ef0d09b81f2d6928b85f93c2da9f6f6f/shoes-core/lib/shoes/builtin_methods.rb#L17-L19_) - does that solve the problem?

**Comment by Jeytas** [comment]
When I try that I get the exact same error message, but it says "undefined method 'confirm', did you mean 'confirm?'"

**Comment by PragTob** [comment]
Hi,

could you please show the offending code or even better produce a minimal sample? I'm asking because in my testing [simple_dialogs.rb](https://github.com/shoes/shoes4/blob/master/samples/simple_dialogs.rb)  and [simple_dialogs_outside.rb](https://github.com/shoes/shoes4/blob/master/samples/simple_dialogs_outside.rb) work just fine.

Thanks!
Tobi

**Comment by Jeytas** [comment]
For some reason, when I try the ones you sent it seems to work, but it doesn't work in the program I am currently making. I am not really that good at coding Ruby and especially Shoes yet, so maybe there's something I am missing here. [Here is an example](https://gist.githubusercontent.com/Jeytas/449c9a5f7281bca6848776edbcb3ef57/raw/e6b6d1c86e7a021785796bb0dab05d836be34c0f/snippet.rb) where an alert() should appear but it exits in an error instead. The same would happen if I used a "confirm" there.
Also, I am using the exit() method here, because Shoes.quit() also doesn't work.

**Comment by PragTob** [comment]
@Jeytas I'm sorry but that code isn't a complete example, as in there's a `Shoes.app do` or something missing. I.e. a script that we can execute and that produces the bug is ideal.

Btw. - one of my first shoes projects was also partially a twitter client. Meet [infoes](https://github.com/PragTob/infoes) :)

**Comment by tedma4** [comment]
Getting the same error on load using the `shoes` command. 

`ERROR: undefined method `alert' for (Shoes::App:0x00000fa0 "testing page"):Shoes::App`

Using jruby 9.1.15.0 with shoes-4.0.0. on High Sierra

```
class AppComponent < Shoes
  url '/', :index
  url '/login', :login
  def index
    send('login')
  end
  def login
    display_login
  end
  def display_login
    alert("doesn't work")
  end
end
Shoes.app width: 800, height: 600, title: 'testing page'
```

**Comment by PragTob** [comment]
Thank you a lot @tedma4 !

It might be that we're not including the dialogues module for the URL stuff - I'll check it out.

**Comment by tedma4** [comment]
FYI, I got it to work by calling the methods from the class itself. So, from my example above, calling `AppComponent.alert('Does now!!!')` shows the alert

**Comment by PragTob** [comment]
@tedma4 yup you can also call them directly on `Shoes` - fix will be up in a minute :)

**Comment by PragTob** [comment]
This seems fixed :tada:
