### ISSUE TITLE
Nokogiri is an implicit dependency

### ISSUE THREAD

**Issue by mileszs** [shoes/shoes4#1516]
Greetings from RubyConf! (Credit to @jasonrclark for getting me installing Shoes4)

It seems that nokogiri is a dependency, but is not explicit in the Gemfile. Here is how I came to this conclusion:

1. I installed jruby via `ruby-install jruby`
2. I created a Gemfile that looks like this:

```ruby
source "https://rubygems.org"

gem "shoes", "4.0.0.rc1"
```

3. I ran `gem install bundler`
4. I ran `bundle install`, which succeeded. 
5. I ran `shoes -v` and got:

```
Could not find nokogiri-1.6.4.1 in any of the sources
Run `bundle install` to install missing gems.
```

6. I added `gem "nokogiri", "1.6.4.1"` to the Gemfile
7. I ran `shoes -v` and got

```
Selecting shoes-swt backend to use. This is a one-time operation.
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 10.1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Shoes 4.0.0.rc1
```

This seems like an issue where I could certainly issue a PR that fixes the issue, but it also seems like it's possible I've got something odd going on (to be the first to encounter it). So, I say to myself, "Probably there's something else going on here and all of these very nice and intelligent Shoes contributors will give me a knowing smile and help me."

What do you think?

**Comment by jasonrclark** [comment]
Thanks @mileszs! This seems totally legit and an easy thing I might have missed. I’ll try your instructions out on a clean jruby next time I get to :computer:

**Comment by jasonrclark** [comment]
@mileszs Got a clean copy of JRuby 9.1.14.0 and tried this from scratch, and it installed nokogiri for me :/ Time to start tracking down what's different between our setups!

Could you get back to the state where you had the failure, probably by:

* Put your Gemfile back to only depending on `shoes`
* Running this in the directory:

```
gem uninstall nokogiri
rm Gemfile.lock

bundle -v
bundle install

shoes -v
```

After that, if you're in the bad state, I'd love to see what's in your `Gemfile.lock`

**Comment by PragTob** [comment]
:wave:

That's weird. It's a transitive dependency as it comes from [`shoes-manual`](https://github.com/shoes/shoes-manual/blob/master/shoes-manual.gemspec) (and we depend on shoes-manual)

```
  spec.add_dependency "shoes-highlighter", "~> 1.0", ">= 1.0.0"
  spec.add_dependency "nokogiri", "~> 1.6.4.1", ">=1.6.4.1" # For converting the manual to HTML
```

@mileszs please also add a `ruby -v` to the script :)

**Comment by mileszs** [comment]
Ah, that's the issue. I missed the specific version number in Jason's slides, so I had `jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.144-b01 on 1.8.0_144-b01 +jit [darwin-x86_64]`. 

I'm sorry to waste everyone's time. After making sure I got `jruby 9.1.14.0 (2.3.3) 2017-11-08 2176f24 Java HotSpot(TM) 64-Bit Server VM 25.144-b01 on 1.8.0_144-b01 +jit [darwin-x86_64]`, things are working fine. No warnings after running `shoes app.rb`, either.

Looking forward to getting my kids playing with it. Thanks again for jumping in to help so quickly. I'm sorry it was user error instead of something to move the project forward.

**Comment by jasonrclark** [comment]
No apologies needed! We're happy to help folks get set up. Thanks for the extra sleuthing @PragTob !

**Comment by PragTob** [comment]
Glad it's resolved @mileszs :tada:
