### ISSUE TITLE
Star redrawing missing pixels

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1526]
Per https://github.com/shoes/shoes4/pull/1525#issuecomment-348401940, seeing some left behind pixels in `samples/simple_star.rb` that are almost certainly related to the redrawing box we use for stars (which is custom, and probably just off by a pixel)

![image](https://user-images.githubusercontent.com/130504/33468467-62746e76-d611-11e7-9de9-772a10163311.png)

**Comment by nicholalexander** [comment]
@jasonrclark - yes, I saw these too and was trying to figure out what was going on.  I finally got it to go away by changing the redraw_height to be  ` element_height + style[:strokewidth].to_i * 2 -1` but that broke all of the tests depending on that.  

I was going to raise it with you today but you beat me to it!

I noticed in the dimensions file you pointed me to you all make use of a PIXEL_COUNTING_ADJUSTMENT and wondered if perhaps that is what one should use in this case?

**Comment by jasonrclark** [comment]
Yeah, the tests around these sort of coordinate changes are pretty tightly coupled to the math, so doesn't surprise me that the change would break things.

It's probably the right fix to make the redraw_height and/or other positioning slightly bigger than it was. It just dictates the area where SWT will do a redraw, so being more generous with the boundaries isn't a big deal.

PIXEL_COUNTING_ADJUSTMENT is probably appropriate to use, but isn't any magic--it's just a name we give when we're futzing with things like this.
