### ISSUE TITLE
Links don't default to blue text

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1537]
Regression from Shoes 3

```
Shoes.app do
  para link("yO")
end
```

**Shoes 3**
![image](https://user-images.githubusercontent.com/130504/34654274-5d07d1a2-f3ae-11e7-8d45-2eaf9517d010.png)

**Shoes 4**
![image](https://user-images.githubusercontent.com/130504/34654276-7170df3a-f3ae-11e7-9251-f0c57fa693b5.png)

**Comment by PragTob** [comment]
Great find!
