### ISSUE TITLE
Using "link"  breaks the app

### ISSUE THREAD

**Issue by RAJKUMAR18** [shoes/shoes4#1569]
I am following the book "No one knows shoes"  by _why which I found on the official site.
I am trying to create an app with links in it and followed the example step by step but it breaks the app.
I am using shoes4.
This is what happens:
1. shoes program_name.rb
2. The app window opens successfully.
3. As soon as i move my mouse cursor within the app window it terminates and following error is given

```
NoMethodError: private method `warn' called for #<Shoes::InternalApp:0x55e42449>
                         text_block_guard at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.rc1/lib/shoes/link.rb:79
                                 visible? at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.rc1/lib/shoes/link.rb:66
                         element_visible? at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.rc1/lib/shoes/swt/mouse_move_listener.rb:57
                                mouse_on? at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.rc1/lib/shoes/swt/mouse_move_listener.rb:52
  block in cursor_over_clickable_element? at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.rc1/lib/shoes/swt/mouse_move_listener.rb:65
                                     any? at org/jruby/RubyArray.java:4441
           cursor_over_clickable_element? at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.rc1/lib/shoes/swt/mouse_move_listener.rb:64
                      mouse_shape_control at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.rc1/lib/shoes/swt/mouse_move_listener.rb:27
                                mouseMove at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.rc1/lib/shoes/swt/mouse_move_listener.rb:15
                           run_event_loop at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/swt-4.6.1.1/lib/swt/minimal.rb:107
                               event_loop at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/swt-4.6.1.1/lib/swt/minimal.rb:90
                                     open at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-swt-4.0.0.rc1/lib/shoes/swt/app.rb:72
                                 open_gui at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.rc1/lib/shoes/internal_app.rb:128
                               initialize at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.rc1/lib/shoes/app.rb:53
                                      app at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.rc1/lib/shoes/app.rb:21
                                   <main> at E:/Project-hotel/bigger.rb:24
                                     load at org/jruby/RubyKernel.java:994
                                   (root) at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.rc1/lib/shoes/ui/cli/default_command.rb:1
                                      run at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.rc1/lib/shoes/ui/cli/default_command.rb:15
                                   <main> at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/shoes-core-4.0.0.rc1/lib/shoes/ui/cli.rb:40
                                     load at org/jruby/RubyKernel.java:994
                                   <main> at C:\jruby-9.2.0.0\bin/shoes-swt:23
```

4. I tried removing ** "link()" ** and then executing it again and it works with no problem here is the code:
```
class Booklist < Shoes
	url '/',		:index
	url '/twain',	:twain
	url 'kv', 		:vonnegut

	def index
		para "Books I've read: "
		link("by Mark Twain", :click =>"/twain")
		link("by Kurt Vonnegut", :click => "/kv")
	end

	def twain
		para "Just Huck Finn.\n",
		link("Go Back.", :click => "/")
	end

	def vonnegut
		para "Cat's Cradle. Sirens of Titan. ",
			"Breakfast of Champions. \n",
			link("Go Back.", :click => "/")
		end
	end

Shoes.app :width => 400, :height => 500
```

**Comment by jasonrclark** [comment]
Hi @RAJKUMAR18, thanks for the detailed report and the code to reproduce the problem!

So the root cause of your application failing is in the `index` method. The `para` and first `link` line in that method both need a `,` at the end of them--the whole thing is one call to `para`, with the links as parameter.

So index should look like this:

```
def index
		para "Books I've read: ",
		link("by Mark Twain", :click =>"/twain"),
		link("by Kurt Vonnegut", :click => "/kv")
	end
```

(I also noticed in testing that the line with `url 'kv'...` should be `url '/kv'...` or the link to work properly (note the slash inside the string).

The error message you got was not very helpful. I totally didn't understand why it was failing until I debugged for several minutes! I'll see if I can make that error message clearer for the future, but in the meantime adding those commas and fixing that forward slash should get your app running.

**Comment by RAJKUMAR18** [comment]
Thank you for your reply. I will make changes asap. Also is the following code was taken from the book available on the official site. So is there any other resource I can follow?

**Comment by jasonrclark** [comment]
Is the link you followed from the official site (http://shoesrb.com) pointed to http://evc-cit.info/cit020/nks.pdf? Looking at page 31 in that doc I see this, which includes the commas as needed:

![image](https://user-images.githubusercontent.com/130504/47265196-59fb9900-d524-11e8-9783-f4060f0f7402.png)

The official site is the best answer I have for resources, but I'm looking to give it a refresh soon and will see if there are other things out there that could be linked to.

**Comment by RAJKUMAR18** [comment]
Thank you. I realize it was a syntax mistake. 
One question is, why did shoes didn't warned or terminated the program while executing?
Instead it completely messed up the GUI.

**Comment by jasonrclark** [comment]
@RAJKUMAR18 Ah, that's a great question. That was actually a bug in Shoes itself that you tripped across. It was supposed to just log a warning, but a bug at that point threw an exception which fouled up the main UI loop.

Anyone making a similar syntax mistake from here forward should get a message instead of what you saw after #1570 gets released (hopefully soon!)
