### ISSUE TITLE
Shoes overwrites the Windows environment variable

### ISSUE THREAD

**Issue by ghost** [shoes/shoes4#1575]
Just a neat little heads-up for anyone stumbling over this: 

The default Shoes installer on Windows **OVERWRITES** the environment path variable on Windows instead of **APPENDING** to it.

10/10 experience, can recommend.

**Comment by lulcat** [comment]
It's windows.. who the hell would care?

**Comment by PragTob** [comment]
@graves I think you're looking for shoes3 not shoes 4 we don't do anything of the like.

@lulcat people use windows, it's a legit thing. As a maintainer I care.

**Comment by ccoupe** [comment]
There is a bug in older Shoes 3 where it fails to append to PATH because PATH is too long. There is no real fix for that Installer problem but newer Shoes 3  detects that it's likely to happen and won't install.
