### ISSUE TITLE
Not able to drag windows?

### ISSUE THREAD

**Issue by Ashvith** [shoes/shoes4#1580]
Hello, newbie to ShoeRB. I was just trying some walkthough apps , and realise that dragging and resizing of windows is not supported?

**Comment by PragTob** [comment]
@Ashvith hi there, it should be supported at least it works for me. Are you using shoes4 or shoes3?

**Comment by Ashvith** [comment]
Actually I am using Shoes walkabout. I am not sure about how to use shoes though. Also , a dumb newbie question , but can I turn my GUI into a .exe file? Maybe by building? And what about immersive title bar? I hate the default windows title bar as well as some GTK title bars , and was wondering if we can make something similar to the one used in VSCode or maybe some of the modern apps in Windows store??

**Comment by PragTob** [comment]
I'm not sure what shoes walkabout means/is.

There is packaging in shoes, I'm unsure what the current capabilities are though. https://github.com/shoes/shoes4#packaging-a-shoes-app

I'm also unfamiliar with windows and what's modern there, sorry :)

**Comment by KCErb** [comment]
Walkabout is Cecil Coupe's blog on keeping shoes3 alive: https://walkabout.mvmanila.com/

@Ashvith may want to bring this up over on https://github.com/shoes/shoes3

**Comment by Ashvith** [comment]
http://shoesrb.com/downloads/
version 3.3 is what I am talking about 😅

**Comment by PragTob** [comment]
@KCErb thanks didn't know about Cecil's blog!

@Ashvith as @KCErb pointed out you're at the wrong repo, head on over to https://github.com/shoes/shoes3 and people might help you there :)

**Comment by ccoupe** [comment]
You can file an issue against Shoes 3. This one is unlikely to be fixed. I'm not actively working on Shoes 3. There is some support for creating your own menu system in Shoes 3.3.7 but there are some bugs. Yes, it could be turned into an .exe but Windows 10 almost always believes it's not trusted and won't run it. There are ways around that but it's all too much to keep alive by myself.
