### ISSUE TITLE
Shoes joining forces with Glimmer?

### ISSUE THREAD

**Issue by rubyFeedback** [shoes/shoes4#1588]
Hey there folks,

Glimmer is written and maintained by Andy. You can find it here:

https://github.com/AndyObtiva/glimmer

If you have a look at it you'll notice that glimmer is in many ways similar
to Shoes, but it has a wider scope (focus) e. g. to be, for instance, usable
on the "world wide web" as well (opal, rails and so forth), in addition
to classical GUI desktop systems (including SWT, and perhaps java 
swing one day; not sure, ask Andy. Anyway).

I think it would make sense for both glimmer and shoes, correspondingly
the users, to join forces eventually.

Disclaimer: I am NOT officially affiliated with Andy and glimmer per se,
mind you. I am not a co-developer or anything; I am a "semi-random"
guy. Andy and I have kind of "met" virtually through libui, actually, 
which is maintained by kojix2.

I think it would be ideal if spread-out individual ruby devs could align
under common projects as such. Note that I have not asked Andy about
any of this, perhaps he may disagree, perhaps not. :)

My point is that I think it would be great if we can bundle our forces.

I do not know how compatible Glimmer is to shoes3 or shoes4, but
I am very much convinced that IF there is an incompatibility, Andy
may consider adapting glimmer to cover the use cases of Shoes.
(Some of us may remember the old shoes by _why and I think _why
would approve of glimmer, or perhaps he already uses glimmer,
who knows.)

Perhaps we can also have something like rack, but for GUI elements
in general, including the terminal. Something like an adapter. Also
a specification so that we can all create simple GUI elements such
as:

    button {
    }

And have it work on as many GUIs and world-wide-web applications
as possible. (Should be doable via opal, I think).

Anyway, this is just a little info and encouragement - perhaps the one
or the other of you may also have a similar use case as others did
before (Shoes from _why must be very old now, I think before 
2010 already right?) and it would be best if we can bundle our efforts
in the long run, in my opinion.

PS: Andy also made some statements about shoes. If you have any
more questions or request additions and extensions to the FAQ there,
I am sure Andy will be more than happy to add more information
there:

https://github.com/AndyObtiva/glimmer#faq

**Comment by PragTob** [comment]
Hi there,

most of Shoes hasn't been active in many years (sadly). As such, there aren't many efforts to combine as the efforts over here are (as far as I'm aware) 0 or close to 0. Anyone who wanted to dive back in is most likely aware of glimmer.

Glimmer also seems to knowingly deviate from Shoes, which is fine. Both are their own thing unless your suggestion is to rebuild shoes on top of Glimmer - which probably someone is doing somewhere already as I know the shoes community.

Cheers,
Tobi
