### ISSUE TITLE
samples/good-vjot.rb

### ISSUE THREAD

**Issue by ashbb** [shoes/shoes4#255]
In order to keep compatibility with Shoes 3, we have to implement the following four.

- slot with scrollbar
```ruby
# ex.
stack scroll: true
```

- decimal number style for edit_line and edit_box
```ruby
# ex.
edit_line width: 1.0
```

- margin for background and border
```ruby
# ex.
stack margin: 20 do
  background green
  border yellow
end
```

- margin_bottom
```ruby
# ex.
edit_line margin_botom: 20
```

But I think that it's not so bad to implement them after the release of Shoes 4 v1.0.
What do you think?

**Comment by PragTob** [comment]
We do have a separate slot scrolling issue now, so I'll take the liberty to close this one down.
