### ISSUE TITLE
Debugging shoes4

### ISSUE THREAD

**Issue by rjack1201** [shoes/shoes4#346]
I'm a ruby newbie, so I apologize in advance if this is a stupid question. I'm playing around with shoes on Windows and it runs fine. However, I'm trying to debug and I fail with the following:

C:\Users\Roger\Documents\GitHub\shoes4>bin\shoes-debug samples\sample99.rb

C:\Users\Roger\Documents\GitHub\shoes4>call jruby --1.9 --debug -r debug -e "$:<
< 'lib'; require 'shoes'; require 'shoes/configuration'; Shoes.configuration.bac
kend = :swt; require 'samples\sample99.rb' "
Debug.rb
Emacs support available.

-e:1:
(rdb:1) c
file:/C:/jruby-1.7.4/lib/jruby.jar!/jruby/java/java_package_module_template.rb:1
4: `cannot load Java class org.eclipse' (NameError)
        from c:/jruby-1.7.4/lib/ruby/shared/rubygems/custom_require.rb:60:in `re
quire'
        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes/swt.rb:2:in `(root
)'
        from c:/jruby-1.7.4/lib/ruby/shared/rubygems/custom_require.rb:1:in `(ro
ot)'
        from c:/jruby-1.7.4/lib/ruby/shared/rubygems/custom_require.rb:36:in `re
quire'
        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes.rb:44:in `load_bac
kend'
        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes/configuration.rb:1
0:in `backend'
        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes/app.rb:57:in `load
'
        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes/app.rb:57:in `init
ialize'
        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes/app.rb:15:in `app'

        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes/help.rb:527:in `re
quire'
        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes/help.rb:527:in `(r
oot)'
        from C:/Users/Roger/Documents/GitHub/shoes4/lib/shoes/manual.rb:1:in `(r
oot)'
file:/C:/jruby-1.7.4/lib/jruby.jar!/jruby/java/java_package_module_template.rb:1
4:
(rdb:1)

Can somebody please explain how to run shoes in a debugger? Is there a better debugger to use?

Thanks!

**Comment by jasonrclark** [comment]
So at this point we've settled on using `pry` and `pry-nav` for debugging purposes, and from my personal experience they are working great. They're already in the Gemfile under development, and you can put a break in the code with the following:

```
binding.pry
```

Shameless self-promotion, I gave [a talk on debugging tools at BaRuCo](https://www.youtube.com/watch?v=hYtUODuxy9c), and a lot of it revolved around using pry effectively.

Closing this out, but happy to answer more questions if they come up about debugging, or field other issues with using pry.

**Comment by KCErb** [comment]
Excellent talk, thanks for the link. Maybe I'll actually start using pry now :)
