### ISSUE TITLE
Remaining work on SWT Gradient

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#369]
- [ ] refactoring: what do the arguments in `calculate_x_and_y` mean? Some better names and maybe even a comment would be helpful
- [ ] a gradient may also take the angle option (easy task) although I don't know what happens if background as an angle option, and gradient has an angle option - which angle will be taken?
- [ ] Tests especially for all the angle calculations and their result
- [ ] refactoring to look into a way to make `determine_args_based_on_angle` more succint or something, it seems like some repetition to me but I can not figure out how to make it better, I suspect there must be a mathematic way to do that.

**Comment by jasonrclark** [comment]
Given these were dev notes from a very long time ago, I'm going to just close this out. I suspect that refactoring and testing will come from my trying to solve the various angle problems we've got with things today, noted in other issues.
