### ISSUE TITLE
The :angle is a style option to apply a gradient

### ISSUE THREAD

**Issue by ashbb** [shoes/shoes4#370]
Try out simple-color-transitions.rb. I got this incorrect screenshot.
![incorrect screenshot](http://www.rin-shun.com/shoes4/tmp/incorrect-screenshot-for-simple-color-transitions.png)
I think this is correct.
![correct screenshot](http://ashbb.github.io/green_shoes/snapshots/sample22.png)

**Comment by jasonrclark** [comment]
Screenshot appears broken in original issue report, but I've confirmed that we aren't rotating elements based on the angle styling as seemed to be the central issue. There're other issues around gradient angles that I'm entering separately, but this one seems clear to close.
