### ISSUE TITLE
Redrawing just for the own app

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#385]
The redrawing aspect was relatively unaware of the possibility of multiple apps. So what happens when you click a button in any of 2 open applications is that both will get drawn. 

That's not a big issue we might wanna change it though. E.g. implement a mechanism that just triggers the redraw for the app where the event was triggered. Therefore we'd have to somehow use the information the object has about it's app and make that uniform.

**Comment by jasonrclark** [comment]
Closing this out until it proves to be an actual perf issue.
