### ISSUE TITLE
Command Key on Mac for keypress

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#392]
Right now the command key on Mac maps to nothing for `keypress`.

So an idea would be to map the command key to the same thing as the "super" key on Linux (which is the Windows key on Windows).

I don't know what the Mac behaviour is here yet, could someone try that out? Just run samples/simple-keypress.rb with Shoes3 and press just command, command + letter, command + alt + letter etc.

Thanks!

**Comment by ccoupe** [comment]
On Linux, that super or meta  key is often grabbed by the Window manager/theme and not passed to the application (i.e. Shoes). Very dependent on the windows manager and the all the possible theme tweaks and user settings. Consider it a unusable key, cross platform.

**Comment by PragTob** [comment]
Thanks for your input cecil, can confirm that Mint used to swallow it but it works these days :) Maybe we could add docs that cross platform it might be an issue, I like the general possibility though

**Comment by PragTob** [comment]
Sadly it seems like the windows key isn't even supported by SWT: https://bugs.eclipse.org/bugs/show_bug.cgi?id=55236 :-/

I'm not quite sure but it seems like ot could be accessible as MOD4, whatever that means... seems like a shaky thing to do, though :-/

**Comment by jasonrclark** [comment]
Boo. Well, if that's the case do we just want to call this with the `super_` on the Mac as is? I kinda still like having it available, since there are some very natural Command+ shortcuts I personally crave in my apps...

**Comment by PragTob** [comment]
We _could_ look into what MOD4 is or if the state mask changes in any way on Windows/Linux and do stuff manually - I fear it either doesn't work or will be shaky at best :(

**Comment by jasonrclark** [comment]
Yeah, with that being the case, I'd be in favor of closing this as it is. If some future version SWT or a different backend supports it, there's now a home for those type of keypresses. Sound reasonable?

**Comment by PragTob** [comment]
:+1:
