### ISSUE TITLE
Fullscreen on Mac

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#397]
Fullscreen seems to behave weirdly on Mac. The specs fail and at least for my presentation software there seem to be buggy.

In the samples directly there is a sample `simple-fullscreen.rb` - could a mac user please run it and see if it works?

Code is as follows (or just run it from the repo):

```ruby
Shoes.app do
  button('fullscreen') { self.fullscreen = true }
  button('turn back') { self.fullscreen = false }
end
```

If that does not work I'm guessing that it might need relayouting (wild guess from my side). So if it does not work it would be super cool if you could try adding these calls to the two blockw where `self.fullscreen = bool` is called (just one of them at a time, not both (at least it should not be necessary to call both))

* `app.gui.flush`
* `app.gui.real.redraw`

If adding either of those calls resolved the problem with going into fullscreen mode and back please tell me so I can fix it on master.

Mentioning Mac Users: @davorb @fism88 @wasnotrice =)

edit: Also importantly **specs fail** namely in shoes/app_spec.rb the specs for going into fullscreen and immediately out again. They are set to pending for now.

Cheers and thanks a lot!
Tobi

**Comment by PragTob** [comment]
So erm, recurring question - is fullscreen good for most people so we can close this? :) I believe it works for at least @jasonrclark !

**Comment by jasonrclark** [comment]
Totally works for me on OS X 10.9. Don't know if anyone's running a newer version yet to check, but I'm good with calling this fixed.

**Comment by wasnotrice** [comment]
Full screen also works on OS X 10.10. The specs still fail, but that is a separate problem.
