### ISSUE TITLE
Copying text to Clipboard spec failing on Mac OS 10.7.5 with tmux

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#398]
When running the specs with `rake spec` there is the following failure when running from  iTerm + zsh + tmux (without tmux it works fine).

Error is the following:

```
3) Shoes::Swt::App when attempting to copy text copies text to clipboard
     Failure/Error: Unable to find matching line from backtrace
     Java::OrgEclipseSwt::SWTError:
       Cannot set data in clipboard
```

Check out the [full backtrace](https://gist.github.com/emig/6280080)

This is not exactly high priority as it is really specific, but if anyone wants please go ahead and fix this issue. I'd be super happy :-D

**Comment by jasonrclark** [comment]
Tried this out with latest iTerm + zsh + tmux on my Mac (admittedly not 10.7, but what you gonna do...) and the tests passed flawlessly. Closing out.
