### ISSUE TITLE
What is transform on a lot of SWT objects?

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#409]
A lot of objects have an `attr_reader :transform`. But the value is never set, it's nil. The only classes that really do something with it are `Line` and `Shape`. 

The only place where it seems to be used is in the common `Painter` here:

```ruby
gc.set_transform(@obj.transform)
```

shall really every object have that? Can we get rid of that? What can we do?

Cheers,
Tobi

**Comment by jasonrclark** [comment]
So we have #699 about getting rotate consistently implemented, which I think will have a big impact on how we apply the transform. Any objections to this closing out in favor of making any transform changes with that issue?

**Comment by PragTob** [comment]
No objections, all good :)
