### ISSUE TITLE
Remove dependency on furoshiki?

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#442]
right now we depend on furoshiki (packaging) and furoshiki depends on us - that's a circular dependency and that breaks things. e.g. I had to remove the explicit dependency from furoshiki so that bundle install would atill work.

so one of the dependencies has to go, either shoes on furoshiki or furoshiki on shoes? which one shall it be? 
I am for shoes on furoshiki. furoshiki may
 then be used as a drop in packaging solution for now. later on we would have shoes-core that is just shoes and furoshiki could depend on that. a shoes-full meta gem could then depend on furoshiki and core.

**Comment by jasonrclark** [comment]
At this point, it's `shoes-package` and `shoes-swt` using `furoshiki` that add in the Shoes gems to the package that we're creating.

I'm gonna close it out... if you feel strongly otherwise, chime in and we can always reopen.
