### ISSUE TITLE
Shoes and Threading

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#447]
There have been inquiries about shoes and Threading e.g. how to use threads with shoes.

The problem is that with the current backend (JRuby/SWT) it is not possible to access/change GUI elements from any thread other than the main thread (e.g. painting etc. can just happen from the main thread). If you want to do that from another thread you have to wrap it in Display.syncExec or Display.asyncExec - which essentially kind of makes it single threaded again (if I understand it correctly it just schedules it to be executed in the main thread depenging on sync/async).

So we could provide a more shoes-ish construct to do that Display.(a)syncExec. We could also try to automatically detect it when a thread other than the main thread tries to do drawing and then wrap it - but that sounds overly complicated and maybe not ever achievable to me.
Or we could go with an: Hey you can do multi threading, just don't access any gui elements in the threads - hmkay? That's kind of what JavaScript does. JS relies on the fact that there is a single main thread and multi threading is only provided through [web workers](http://www.whatwg.org/specs/web-apps/current-work/multipage/workers.html) which have no access at all to the DOM. Actors are kind of like actors so I'd love to see people use [celluloid](https://github.com/celluloid/celluloid/) for multi threading and then just do painting in the main thread when they get messages from the actors or something.

What do you think?

Cheers,
Tobi

**Comment by jasonrclark** [comment]
Since general consensus here seemed to be that we shouldn't do anything specific in code, I wrote up some thoughts about it on the wiki in case anyone needs it. https://github.com/shoes/shoes4/wiki/Threading
