### ISSUE TITLE
Provide spec guidance

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#506]
As identified in #505 it would be great to provide further guidance with spec writing. Most likely in the wiki.

E,g, go into stuff like:

* stubbing/mocking
* which specs are executed with what backend
* an example
* tips/tricks

What do you think @chuckremes ? Any additions? =)

Cheers,
Tobi

**Comment by KCErb** [comment]
I've been away from the project for far too long. I think I'll try to jump back in on the last thing I was doing which was some tutorials. I actually left off working through the specs so that fits in nicely with this issue.

**Comment by jasonrclark** [comment]
I think this is done on the basis of https://github.com/shoes/shoes4/wiki/Testing-Shoes
