### ISSUE TITLE
simple-anim-text.rb doesn't work properly

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#523]
Problems:

- [x] the slot should be centered on the window, but it's at upper left
- [x] the motion block doesn't print anything (uses Shoes.p - does not print anything for @PragTob on shoes3 either)
- [ ] font is not parsed/displayed correctly

shoes3:

![screenshot from 2014-02-20 20 59 20](https://f.cloud.github.com/assets/606517/2222773/8d773f96-9a69-11e3-9f8f-8c7613fd2929.png)

shoes4:

![screenshot from 2014-02-20 20 59 55](https://f.cloud.github.com/assets/606517/2222778/9d900ef8-9a69-11e3-9134-fe9cc0e67286.png)

**Comment by PragTob** [comment]
Pushing back to rc1 s this also involves the rather clunky work needed for font parsing in #551 so it should be done in the same milestone imo.

**Comment by wasnotrice** [comment]
@PragTob nope, that was just my initial placement. RC1 is cool.
