### ISSUE TITLE
SWT warning on OS X

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#530]
I haven't isolated the cause of this, or generated a minimal case, but here's the warning:

```
2013-12-30 22:41:49.740 java[57307:d0f] *** WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
```

Looks like this is in the [SWT issue tracker](https://bugs.eclipse.org/bugs/show_bug.cgi?id=386252), but there doesn't seem to be any movement yet.

**Comment by jasonrclark** [comment]
Running El Capitan with Java 1.8.0_102, I at long last don't see these warnings on every startup of Shoes. Huzzah! 💃  SWT issue linked above is also addressed, hence the change I think.

**Comment by PragTob** [comment]
:D which reminds me... I opened up a PR on the SWT gem to update to most recent SWT... will try to ping daniel
