### ISSUE TITLE
Font size is too small on OS X

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#545]
Here's `samples/sample15.rb` in Shoes 4:

![image](https://f.cloud.github.com/assets/908/1826234/0636fbf8-71f0-11e3-847e-10b23c225b13.png)

and in Shoes 3:

![image](https://f.cloud.github.com/assets/908/1826233/0035600a-71f0-11e3-90ec-b7738c4357c5.png)

Note that the font size on buttons seems right.

**Comment by jasonrclark** [comment]
Inclined to let the OS defaults be what they are in this case. Closing out.
