### ISSUE TITLE
samples/good-clock-adjusted.rb text sticks out below background

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#546]
The text at the top should be contained within the black background.

![image](https://f.cloud.github.com/assets/908/1826267/836fea1a-71f2-11e3-9a4c-7fb64fc3b6f2.png)

**Comment by PragTob** [comment]
The adjusted version isn't around anymore and the normal one looks just fine to me

![screenshot from 2015-01-09 20 07 32](https://cloud.githubusercontent.com/assets/606517/5685515/2c34be86-983b-11e4-8e64-0a741cb06ae8.png)
