### ISSUE TITLE
Setting font in options hash with "Monospace 12px" doesn't work

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#556]
See [line 8](https://github.com/shoes/shoes4/blob/5fe01360804c454c9641ac5f2cc60916f32a1188/samples/simple-editor.rb#L8) of `samples/simple-editor.rb`:

``` ruby
    t = para "", font: "Monospace 12px", stroke: white
```

![image](https://f.cloud.github.com/assets/908/1844101/d3f7c850-74fd-11e3-8b01-420d50f10fcd.png)

**Comment by jasonrclark** [comment]
Updated path for those fonts
