### ISSUE TITLE
good_psychidelic_circles.rb flashes once more after the circle closed the 2nd time

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#578]
I just discovered some odd behavior for sample14.rb and I'm not sure where it comes from (it's on master and my more more accurate redrawing branch)

When you execute it a is filling up with ovals of increasing size - when the circle is big it starts back again from small. Every 2 "circle grows" I can see a miniature version pop up for a small amount of time, then vanish and the real thing starts again.

Happens also when the whole screen is marked to be redrawn. No idea what's going on. 

(for a better explanation I probably need a video - sorry)

**Comment by jasonrclark** [comment]
Path on this now is `samples/good_psychidelic_circles.rb` after sample shuffles, and I can see the effect @PragTob although it's pretty subtle.
