### ISSUE TITLE
Expert tankspank flashes white from time to time/frequent redrawing/windows

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#595]
On Windows expert-tankspank-adjusted.rb sometimes flashes a white screen in between. E.g. I believe this is due to the redraws/flushing the screen - Java and Windows GUI is a somewhat challenging topic. 

Happens every 2 to 10 seconds or so for me.

Dunno what to do about it really, some research in the Java world needed. In general reducing the number of redraws/flushes should be beneficial - I feel like it's a lot better since the last time I tried it due to the recent more accurate redrawing changes.

**Comment by jasonrclark** [comment]
I'm actually not seeing this even running Windows in a VM with some significant other input/redraw lags happening. Given age of the bug, I'm going to close... feel free to reopen if someone sees it still and wants to tackle it.
