### ISSUE TITLE
Make shoes jruby9k/jruby-head compatible

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#600]
Hi all,

I just added jruby-head as allowed failure to out TravisCI build matrix. Right now [they are failing](https://travis-ci.org/shoes/shoes4/jobs/19811368) - [failures](https://gist.github.com/PragTob/9273336).

Why do we want to do that? I hope for a 9k release this summer/autumn or so and I want to be ready. Oh yes the next JRuby major version is called 9k/9000. 9k will be 2.1 support only which should not be too hard for us.

Why are the specs failing? No idea but when we get to running the SWT specs the following warning message will definitely turn into errors:

```
/home/travis/.rvm/gems/jruby-1.7.9-d19/gems/rspec-mocks-2.14.6/lib/rspec/mocks/method_double.rb:159 warning: singleton on non-persistent Java type Java::OrgEclipseSwtWidgets::Shell (http://wiki.jruby.org/Persistence)
```

E.g. we need to change our mocking of pure Java objects/classes (at least).

This is not a total high priority task but should be kept in the head.

Cheers,
Tobi

PS: Oh and of course I want to help uncover potential JRuby bugs in the interest of the community as well as our own :)

**Comment by PragTob** [comment]
With the JRuby error fixed, we finally got now errors:

`bind argument must be an instance of Kernel` - hope I get time to investigate end either uncover an inompatibility or a jruby bug :-)

**Comment by jasonrclark** [comment]
Tests have been running clean for a while on jruby-head, so I'm gonna call this good. If we hit other specific things in testing against the new JRuby, we should open more specific, separate issues.

**Comment by PragTob** [comment]
:+1:
