### ISSUE TITLE
Apps crash on trivial errors where Shoes 3 did not

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#619]
Take this app for instance,

``` ruby
Shoes.app do
  para "Don't touch the hot stove"
  "hot_stove".touch
end
```

Shoes 3 logs an error, but keeps running the app:

![image](https://f.cloud.github.com/assets/908/2508653/58e554d2-b3de-11e3-85d8-ebd042745931.png)

Shoes 4 just crashes:

![image](https://f.cloud.github.com/assets/908/2508683/968153a4-b3de-11e3-8949-1af6946ca725.png)

I don't know why `#touch` is a private method in Shoes 3, but undefined in Shoes 4. Let's ignore that for now :)

**Comment by jasonrclark** [comment]
This is being addressed and tracked via https://github.com/shoes/shoes4/issues/1413

We're going to provide the same rescuing we had with Shoes 3 by default, but have an option for failing fast and hard that folks can opt into. In the future we may reconsider defaults on that.
