### ISSUE TITLE
simple_calc_2.rb - layout a bit funky

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#672]
![screenshot from 2014-04-28 20 07 59](https://cloud.githubusercontent.com/assets/606517/2820970/34e897e6-cf00-11e3-924d-422542b9c910.png)

If you look closely then there are two things:
- [x] starting in the second row, every button starting at the second item is a bit off - some pixels too low it seems (well maybe just one pixel, could be an off by one error)
- [ ] the background does not extend properly at the background of the buttons which is grey not whatever that color shouldbe

**Comment by jasonrclark** [comment]
Triaging things while waiting on test runs... for me this doesn't look weird locally (although honestly we've got two calculators, so one of them could go anyway 🔪 )

Here's my Mac results:

![image](https://cloud.githubusercontent.com/assets/130504/20998173/ee57b8a0-bcc0-11e6-8369-9d97777d72a1.png)

Will take a look at it when I get my Linux VM spun up to see if this is platform dependent.

**Comment by PragTob** [comment]
@jasonrclark correct! But Mint is based on Ubuntu and since my upgrade I also run on the ubuntu 16.04 base which means same packages, gtk theme is slightly different but it should all good, but since I'm here... 

![shoes 4 _008](https://cloud.githubusercontent.com/assets/606517/21042505/06666e1e-bdf2-11e6-8423-45af63a1ba38.png)

I think this might actually have been your recent fix with the painters :+1: 

that said, your mac one looks mighty weird to me @jasonrclark - shouldn't it look like the Linux version? Looks like buttons are way too small :|

anyhow, that's another topic. Closing out. Thanks for triaging :heart:

**Comment by jasonrclark** [comment]
Ah yes, I think I've noticed before that the buttons on the Mac don't seem to respect the explicit height setting. Worth some more investigation.
