### ISSUE TITLE
Packaged app fails to open with java.io.FileNotFoundException (accessing images)

### ISSUE THREAD

**Issue by braincomb** [shoes/shoes4#676]
Hi all,

I've successfully packaged my app on MacOS X 10.8.5, but the app fails to open, with the following exception:

```
LoadError: load error: META-INF/main -- org.eclipse.swt.SWTException: i/o error (java.io.FileNotFoundException: file:/Users/braincomb/my-app/pkg/myapp.app/Contents/Java/aw.jar!/shoes-app/images/header.png (No such file or directory))
  require at org/jruby/RubyKernel.java:1065
  require at file:/var/folders/md/c7trzt5n66s3p0mwlnkbz6n4jnhzb3/T/jruby21387417529286949extract/jruby-stdlib-complete-1.7.12.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:126
  require at file:/var/folders/md/c7trzt5n66s3p0mwlnkbz6n4jnhzb3/T/jruby21387417529286949extract/jruby-stdlib-complete-1.7.12.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:124
   (root) at <script>:3
error: org.jruby.embed.EvalFailedException: (LoadError) load error: META-INF/main -- org.eclipse.swt.SWTException: i/o error (java.io.FileNotFoundException: file:/Users/braincomb/myapp/pkg/myapp.app/Contents/Java/aw.jar!/shoes-app/images/header.png (No such file or directory))
```

I have this code that calls the images, which works fine in un-packaged state:

```
  @app_dir = File.expand_path(File.dirname(__FILE__))
  @image_dir = @app_dir + "/images/"
  background @image_dir + "light_grey.png"
  image @image_dir + "header.png", top: 10, left: 20
```

I also looked inside the jar file with `jar tf` and made sure that the images were there:

```
shoes-app/images/header.png
shoes-app/images/light_grey.png
```

I removed the call to the image, repackaged it and it's working fine. Also interesting to note that the background didn't work/show, even though there were no errors about it.

Any ideas how to fix this? 

I followed all packaging instructions from the shoes4 repo, which I cloned yesterday. 

ruby -v

```
jruby 1.7.12 (1.9.3p392) 2014-04-15 643e292 on Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-462-11M4609 [darwin-x86_64]
```

Thanks!

**Comment by lmrodriguezr** [comment]
I've found a workaround for this issue, which could probably lead to an eventual solution in the shoes code. As it happens, `image` cannot read image files from within the jar, but other jruby functions are perfectly happy with it. So... you can just create a temporal folder at startup where you can `FileUtils.copy` the images you need, and then use the path to the temporal folder instead of the path relative to the script.

I know this is not a complete solution, but at least it will let you put images in shoes apps that you need to package for now.

-- Miguel.

**Comment by jasonrclark** [comment]
Thanks for the workaround on that @lmrodriguezr. One of these upcoming releases we'll finally be focusing on packaging, and at that point this will come in handy.
