### ISSUE TITLE
Fully Implement App#rotate (and make it available as a style option)

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#699]
From what I gathered (not tried out yet) [App#rotate](http://shoesrb.com/manual/Art.html#rotate) isn't fully working.

Optionally, which could be moved to another issue/PR, it'd be nice if rotate were available as a style option. That would be an extension of the DSL which I'd like but could wait for 4.1.0

e.g.:

`rect 100, 50, 200, 300 rotate: 45`

cc: @ashbb @KCerb

This issue was "born" from #698 

Cheers,
Tobi

**Comment by jasonrclark** [comment]
Investigating via app at the end of this comment, I found the following about where rotate is implemented:

* [ ] arc
* [x] arrow
* [ ] line
* [x] oval
* [x] rect
* [ ] shape
* [ ] star

Running on Shoes 3, all of these art elements rotate.

```
Shoes.app height: 800 do
  rotate 10

  rect 100, 50, 100, 50
  oval 100, 150, 100, 50
  arrow 150, 250, 100
  line 100, 350, 200, 350
  star 100, 450, 5, center: true
  arc 100, 550, 100, 50, 0, Shoes::PI

  shape fill: orange do
    move_to 100, 650
    line_to 200, 650
    line_to 150, 750
    line_to 100, 650
  end
end
```
