### ISSUE TITLE
Use the default system colors for a more native look and feel

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#710]
Every OS has their own default background color and maybe even button colors. In fact [a whole bunch of them starting at COLOR_INFO](http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fswt%2FSWT.html) - scroll down for more. E.g. COLOR_WIDGET_BACKGROUND seems interesting for setting the default background color of an app (as we ntoiced these are different between Linux, Mac and Windows).

That would mean to implement methods/constants referring to those values in a shoes friendly way in the backend.

Relates to #601

**Comment by KCErb** [comment]
Looks like @PragTob's link is broken, here's the link to the Swt docs that give those color ints

http://help.eclipse.org/luna/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/package-summary.html

**Comment by jasonrclark** [comment]
Closed by #1166
