### ISSUE TITLE
Shape doesn't support left, top arguments

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#734]
The manual says that `#shape` takes `left` and `top` arguments

![image](https://dl.dropboxusercontent.com/spa/0dcvxe71jtnccsf/k-rdaewo.png)

but our implementation just takes an optional hash of options. We don't have any samples that exercise this signature, but Shoes 3 does support it. So...

- [ ] Add sample that uses `shape(left, top)`
- [ ] Add specs for this signature
- [ ] Support the sample in Shoes 4

**Comment by jasonrclark** [comment]
Looks like this was addressed over in #948 apart from the lack of a sample. I tweaked one of the existing samples to the `left, top` form since it takes other things as a hash after (demonstrating we handle that properly).
