### ISSUE TITLE
The manual is missing an entry for shape(styles)

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#735]
The manual has only one method signature for `#shape`, that takes left and top arguments

![image](https://dl.dropboxusercontent.com/spa/0dcvxe71jtnccsf/k-rdaewo.png)

but Shoes 3 and Shoes 4 both support another signature `shape(styles)`, where styles is optional. This should be added to the manual.

See samples/sample31.rb and samples/simple_curve.rb for examples of using this signature with and without a hash of styles.

**Comment by jasonrclark** [comment]
Turns out the `shape(style)` flavor is already in the extracted shoes-manual from some point in the past.
