### ISSUE TITLE
Gradient fills for line and arc are not displaying correctly

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#743]
Noticed in [this comment](https://github.com/shoes/shoes4/pull/737#issuecomment-44748940) on #737.

![image](https://cloud.githubusercontent.com/assets/908/3139114/bcc9bd46-e8ca-11e3-89a4-72b2fe54c76b.png)

Note that Shoes 3 doesn't seem to support gradient fills in Stars or Shapes, although it handles Lines just fine.

**Comment by PragTob** [comment]
What's wrong can also be seen quite clearly in this image (star broken, rect working):

![screenshot from 2015-04-19 20 34 31](https://cloud.githubusercontent.com/assets/606517/7220762/b2a47d44-e6d3-11e4-930d-22b1e06231da.png)

**Comment by jasonrclark** [comment]
So @PragTob with #1099 merged, how do you feel about this issue? Given that Shape didn't support gradients back on Shoes 3, are we committed to getting this fully supported on this item, or willing to let it rest where it is? (Or maybe open a shape-specific item about gradient for future investigation past rc1?)

**Comment by jasonrclark** [comment]
Along these lines, noted and logged #1100 for an independent issue I'm seeing with lines and gradients outside of shapes. In this sample, all the lines we see are in shapes, hence their problems.

**Comment by PragTob** [comment]
I think opening a new specific issue seems fine. Might wanna tackle it for rc1 or so, because with hardcoding values I got it to work, the values just didn't make sense to me :-/ Probably needs more swt pattern and shape knowledge.

**Comment by PragTob** [comment]
Opened #1101
