### ISSUE TITLE
Gutter width with scrollbar not operating system independent

### ISSUE THREAD

**Issue by glenn-murray-bse** [shoes/shoes4#772]
Specs `Shoes::App#gutter when app has no scrollbar has gutter of 16` and `Shoes::App#gutter when app has a scrollbar has gutter of 16` fail on Windows. Windows returns '17' for gutter size.

```
1) Shoes::App#gutter when app has no scrollbar has gutter of 16
   Failure/Error: expect(app.gutter).to eq(16)

   expected: 16
        got: 17

   (compared using ==)
 # ./spec/shoes/app_spec.rb:300:in `(root)'

2) Shoes::App#gutter when app has a scrollbar has gutter of 16
   Failure/Error: expect(app.gutter).to eq(16)

   expected: 16
        got: 17

   (compared using ==)
 # ./spec/shoes/app_spec.rb:292:in `(root)'
```

I could fix this with operating system dependent test cases if testing for pixel perfect widths is in fact required. Thought may need to be given to best way forward for times with the windowing layer is different (I could only find a few fails_on_osx tests as examples of this)

**Comment by seethemhigh** [comment]
Hey, guys. Running specs on Ubuntu 14.04 gives the gutter size of... 0! Here's the output of rspec:
```
Failures:

  1) Shoes::App#gutter when app has a scrollbar has gutter of 16
     Failure/Error: expect(app.gutter).to be_within(2).of(16)
       expected 0 to be within 2 of 16
     # ./shoes-core/spec/shoes/app_spec.rb:292:in `(root)'

  2) Shoes::App#gutter when app has no scrollbar has gutter of 16
     Failure/Error: expect(app.gutter).to be_within(2).of(16)
       expected 0 to be within 2 of 16
     # ./shoes-core/spec/shoes/app_spec.rb:300:in `(root)'

Finished in 2 minutes 4.2 seconds (files took 14.67 seconds to load)
2068 examples, 2 failures

Failed examples:

rspec ./shoes-core/spec/shoes/app_spec.rb:291 # Shoes::App#gutter when app has a scrollbar has gutter of 16
rspec ./shoes-core/spec/shoes/app_spec.rb:299 # Shoes::App#gutter when app has no scrollbar has gutter of 16
```
Here's how it looks like when there's no scrollbar...
![image](https://cloud.githubusercontent.com/assets/10567153/6106507/137227b2-b073-11e4-85e9-888d35df7ed3.png)

..and when there's one
![image](https://cloud.githubusercontent.com/assets/10567153/6106541/55e1800c-b073-11e4-9a18-79d9eced5447.png)

**Comment by PragTob** [comment]
Hi there :)

I knew I forgot to take a look at some issue.. thanks for nudging me! In general it's cool to open a new issue for things like this, gets more attention like there :)

Weird that there is no gutter... ah I see it's an overlay scrollbar from the looks of so yeah there is no gutter. 

I think I'll get rid of those specs as so far they caused more harm than good. Thanks! 

Tobi
