### ISSUE TITLE
One-pixel gaps between flowing TextBlock segments

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#777]
When a `TextBlock` flows into separate layouts we align the text correctly, but because of how we're using the underlying SWT elements there's a gap between them when a background color is present (see sample app following).

There's also a vertical gap between text elements which probably shouldn't be there.

I tried one naive solution by altering the second SWT `TextLayout`'s spacing, but it didn't work right for all the spacing possibilities in this test app (requires resizing of the app to see all the possible ways the text blocks can split across lines):

```
Shoes.app width: 250, height: 500 do
  COLORS = [red, green, blue, yellow, orange, purple]
  3.times do
    flow do
      COLORS.each do |color|
        para "Boo Hoo Hoo Hoo", fill: color, size: 24
      end
    end
  end
end
```

![screen shot 2014-05-24 at 8 12 02 pm](https://cloud.githubusercontent.com/assets/130504/3076184/6053c8aa-e3ba-11e3-8522-baad3b0e7605.png)

**Comment by jasonrclark** [comment]
So present behavior on this is a bit different. The one-pixel gap remains between the text blocks, which deserves to get fixed with this item, but weirder offset seen above doesn't happen.

![image](https://cloud.githubusercontent.com/assets/130504/5952886/3d138440-a735-11e4-8077-e88f33755a0a.png)

However, not all is rosy. There's been changes to exactly when we choose to bump to the next line, and apparently some of the math is off for positioning the next text.

![image](https://cloud.githubusercontent.com/assets/130504/5952913/8f4dff4c-a735-11e4-9ed6-bd5da5610b12.png)

**Comment by PragTob** [comment]
Thanks for the update @jasonrclark ! :)

**Comment by jasonrclark** [comment]
Posted #1038 with fixes for some of the off-by-ones. Indicated there that I see other problems from this test:

**Text clipped on right** I suspect this is something wrong with width calculations, maybe given certain font sizes, because doesn't happen when text is set to default size.
![image](https://cloud.githubusercontent.com/assets/130504/5991239/a91a6ea8-a995-11e4-9e61-fb69c082f91b.png)


**Background not filling to edge** Would look a lot nicer if this didn't happen:
![image](https://cloud.githubusercontent.com/assets/130504/5991241/d336e9e6-a995-11e4-8855-01c7388a769a.png)


Suppose I could also file separate issues for them, but either way didn't want to lose track of those.

**Comment by PragTob** [comment]
I think it might be better to file separate issues for this, might do that tomorrow or so if you don't get to it - thanks for filing Jason! :)

**Comment by jasonrclark** [comment]
Logged the new issues, so when #1038 is merged I actually will consider this one closed out. Thanks for the nudge in the right direction @PragTob! :dancer:
