### ISSUE TITLE
Support `Shoes::Shape#arc_to`

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#795]
From my brief testing `arc_to` seems to be slightly different from `arc`--at least when I passed the same values on Shoes 3 to `arc` and `arc_to` I got different results... :confused: 

In any case, you can see reference to it in the online Shoes manual at http://shoesrb.com/manual/Art.html#shape.

Appears to be some conversation about it in #424 as well that might be worth reviewing.

**Comment by jasonrclark** [comment]
Okay, for some reason I found the single example (shown below) from the manual confusing for a long time. I think I get it now, though, and wanted to double-check by everyone before taking a stab.

```
Shoes.app do
  shape do
    move_to(90, 55)
    arc_to(50, 55, 50, 20, 0, Shoes::PI/2)
    arc_to(50, 55, 60, 60, Shoes::PI/2, Shoes::PI)
    arc_to(50, 55, 70, 70, Shoes::PI, Shoes::TWO_PI-PI/2)
    arc_to(50, 55, 80, 80, Shoes::TWO_PI-PI/2, Shoes::TWO_PI)
  end
end
```

On Shoes 3 this yields the following:

![image](https://cloud.githubusercontent.com/assets/130504/7288676/55cc2bc8-e91a-11e4-96d1-859b4e51fa01.png)

So the thing that was throwing me was the `move_to`, but that doesn't actually influence where the arcs draw at all! `50, 55` is just the center of those wedges, and each `arc_to` is just the same thing as a standalone `arc` call outside the `shape` would be.

Given that, I think we should do the same for Shoes 4--just act like an `arc`. Note that elsewhere, though, we've chosen to break compatibility on the `arc` behavior. On Shoes 3 it's the center that's `x,y`--in Shoes 4 it's left + top. I'd keep with that for `arc_to`, and since it's not relative to anything in the `shape` (aka `move_to`) there shouldn't be anything too weird from that.

Does this ring true for anyone else? If so, I'm happy 'cause it shouldn't actually be too tough to implement.

**Comment by PragTob** [comment]
If that's true, then it's cool to roll with that. It just seems weird to me that move_to doesn't have an influence at all... I always thought that move to would move the "pen" to that position and then further painting would start from there, no expert in shape here, though

**Comment by KCErb** [comment]
Likewise.

I've not used `shape` much, but based on the manual would have expected what Tobi said. So I lean towards matching Shoes 3 behavior now, but logging a planned breaking-change to fix this in the future.
