### ISSUE TITLE
Slot: compute_content_height during main loop

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#800]
`Slot#compute_contentheight` right now is executed after all the positioning took place as it was the easiest implementation (see #773). However there is already a place where `current_position` and maximum calculartions take place which is [`update_current_position`](https://github.com/shoes/shoes4/blob/master/lib/shoes/slot.rb#L156-L166). Incorporating it there would save an extra loop (possible performance boost) but most importantly it would also include all the times when positioning is skipped (possibly due to a hidden element, see #796)

However right now all that logic is skipped for absolutely positioned elements but we definitely want it to execute to for the computation of the content height... finding a good place to fit it in seems a bit difficult.

**Comment by jasonrclark** [comment]
Pretty sure that we are now calling `compute_content_height` (by way of `slot_grew_by` -> `determine_slot_height`) after each child we add into the slot. Given this is years old and a lot has changed in the slots (for instance #1124), I'm going to close this out.
