### ISSUE TITLE
All elements should support the hidden style

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#808]
As noted by @KCErb in #806 all elements should support a `hide` style where one can style them to hide them.

For this it might be nice to add a method to the visibility module (https://github.com/shoes/shoes4/blob/master/lib/shoes/common/visibility.rb) where one can just say something like `hide(true)` or `hide(false)` but that name right now collides with the existing method.

**Comment by jasonrclark** [comment]
Closed via #1028
