### ISSUE TITLE
Unnecessarily exposed accessors

### ISSUE THREAD

**Issue by davorb** [shoes/shoes4#82]
Just wanted to mention a bug I just fixed...

Basically all of our classes have a bunch of accessors that aren't private. This wouldn't be a big deal, if it wasn't for the fact that we're essentially writing a DSL. As an example, `app.rb` had an attr_accessor called `:title`, which made it impossible for users to actually create titles/textboxes of that size.

This was pretty easy to fix in this case, but keep in mind that we're polluting the name space for the users. I'm pretty sure that a lot of users might want to create variables called `width` or `height`, but right now we would be causing problems for those guys.

The [Shoes manual](http://shoesrb.com/manual/App.html) is quite clear as to what methods are exposed to the user, and we ought to start following that better.

**Comment by jasonrclark** [comment]
Digging this one back up from the long-ago-times :)

Reading through, I believe that where we're at is that we handled the main cases where the app was exposing things we didn't want. We left this open for DSL stuff... but what DSL stuff actually runs in the context of a DSL object? All the Shoes blocks force `self` in those contexts to the app itself. So unless I'm forgetting about one (which is super-possible!) I don't know of a spot where we actually run things with the target as the DSL object.

Confirm or deny anyone? If we get a loose consensus on that seeming right, I'd vote to put this one to 🛏

**Comment by PragTob** [comment]
I think what I meant with DSL objects, is unnecessary accessors on for instance a `TextBlock` or `InputBox` or whatever all of them are called :)

**Comment by jasonrclark** [comment]
So did you mean that we just have unnecessary stuff exposed on those DSL types? It seemed like the original concern was with people's blocks executed in the app shadowing variables/method names because of those, but I don't see where we run things in the context of a DSL object to be worried about that.

**Comment by PragTob** [comment]
That's how I interpret my comment from back then :) I guess I subsumed it under "unnecessarily exposed accessors" which they are, but I'm not too certain anymore :)

**Comment by jasonrclark** [comment]
Did a bit more digging and have found nothing that executes in contexts other than the app, so the primary concern of method names colliding seems to be totally addressed. 🎉 

I've also done some review on a few of the major element types, and on those I don't see a lot that could be hidden. There's some odd-ball methods around positioning, etc. but nothing easy to hide.

@PragTob you cool with calling this one fixed enough and closing? 🔨

**Comment by jasonrclark** [comment]
Ping @PragTob? ^^

**Comment by PragTob** [comment]
If you say it's all good according to your review then I'm all good as well :) If it turns out to be a problem we can still create a new issue. Thanks for digging in and pinging!
