### ISSUE TITLE
List Box should update items when style[:items] gets updated

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#820]
As noted in the mailing list you can update the `:items` of a list_box like a normal array (via `<<` for example) but the gui isn't catching the change.

Take a look at this:
```ruby
Shoes.app do
  l = list_box items: ["a", "b", "c"]
  p l.items
  l.items << "d"
  p l.items
end
```

**Comment by PragTob** [comment]
Should be done, right @KCErb ?

**Comment by KCErb** [comment]
Right, nearly forgot!
