### ISSUE TITLE
Packaging with images or Making buttons prettier

### ISSUE THREAD

**Issue by miller0929** [shoes/shoes4#825]
Hi,

Well... Just checked #676 ... Same issue - everything including images and .rb files are in the packaged jar, but it just won't load. 

However, how am I supposed to make icons/pretty looking buttons? I do prefer to package the app...
What happens if an image is a url?
If I really need to wait for Shoes 4 developers to make a fully working packager, how long am I expecting to wait?

Thank you.

**Comment by jasonrclark** [comment]
Best I can tell this is just duplicating #676 which I'll be taking a look at in the next pre release. Closing this out to minimize noise, but please comment back if there's more information I'm missing that makes this something distinct.
