### ISSUE TITLE
Samples style guidelines

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#854]
We have #353 and #850 - with them it might be good to have style guidelines to go along with them.

I'd like to use this thread as a discussion to add points to a list. We could then transfer this list to the wiki or a file in the samples folder. E.g. this should be stuff that applies to samples (not the nobody knows shoes once, as those should be left untouched):

* readable method/variable names (e.g. not a, b etc.)
* no global variables
* no class variables
* 2 space indentations
* short methods (a bit harder in shoes, but I'd like them to be around 10 lines still) - does not apply for smaller samples were everything just goes in the app body
* small amount of duplication
* no magic numbers (just using 12 somewhere as a multiplier) except for element placement (e.g. left/top etc.)
* a comment at the top describing what the sample does
* ??? (your additions)

Does that sound good? Please add!

Tobi

**Comment by jasonrclark** [comment]
Wrote up a version of the Samples Guide over at https://github.com/shoes/shoes4/wiki/Samples-Guide and linked it from `samples/README`. Feel free to edit at will, but hopefully that's a good start.
