### ISSUE TITLE
Spec needed to test reading and writing

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#897]
I'd like to see (or . . . actually write, but if someone else gets to this before me then kudos!) a set of specs that go through all of the supported styles of an element and check that the readers and writers (which should exist and are spec'd elsewhere) are in fact reading the values that are on the gui and actually write to the gui. 

It may be possible for the two to get out of sync so the spec would probably do something like

initialize element with jellybean: 'flavor'
read - does it return 'flavor'?
write - new flavor
read - does it return new flavor.

This idea has already been discussed a little bit in #871. The big picture is to spec both the `Common::Style` module over in `spec/shoes/common/style_spec.rb` _and_ to spec each element via `spec/shoes/shared_examples/style.rb`. This issue is about adding more to `spec/shoes/shared_examples/style.rb`.

**Comment by jasonrclark** [comment]
As I've been wrestling lately with the various shared examples that we apply across elements, I'm in agreement with @PragTob on this one--I think that exhaustively testing each of the element types for the basic functionality of the style getter/setters that we generate is likely to cost more than it'll buy us.

Given the passage on time, I'm going to close this out. If someone feels strongly that these should get specs and wants to write up what they'd look like, though, happy to take a peek.
