### ISSUE TITLE
Implement packager for Shoes.{exe,app,sh}

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#90]
In Shoes 3, if you try to open a Shoes app that was packaged without Shoes, it will attempt to download and install Shoes, then use Shoes to open the Shoes app. This is awesome because Shoes apps are generally small. By using a "common Shoes", you can distribute very small app files. This becomes increasingly important as Shoes itself gets larger.

But the Shoes 3 system is very fragile. It depends on URLs that need to be hard-coded in multiple places (and which are currently broken). Also, it doesn't have any notion of Shoes versioning. It just downloads "the latest Shoes".

See [this mailing list thread](http://librelist.com/browser//shoes/2012/1/10/fixing-the-packager/) for some discussion of related issues.

This system could/should be more or less independent of the Shoes library, and could be much more robust. If someone wanted to study [designing hypermedia APIs](http://designinghypermediaapis.com/), they might be able to design an API that apps could visit and navigate to discover the URL they need, rather than relying on hard-coding the URLs.

Note: This whole idea depends on our ability to package Shoes apps without including Shoes, but including a per-platform stub that runs this "download and install if necessary" logic.

**Comment by jasonrclark** [comment]
So I believe at long last I'd consider the basics of this issue done--we can package up simple jar-backed apps for all three OSs. 🎁 🎉 💃 

Plenty more that can be done with packaging, but will move onto tracking it in separate issues.
