### ISSUE TITLE
Shoes .jar package not finding non-gem files with require

### ISSUE THREAD

**Issue by parsonsmatt** [shoes/shoes4#924]
I created an application with Shoes that wraps a CLI script ([project github](http://www.github.com/parsonsmatt/okfilter)). At the top of the Shoes app (OkShoes.rb), I have the line: `require './OkFilter'`. `OkFilter.rb` `require`s the necessary gems and handles all program logic. When I run `shoes OkShoes.rb` everything works great. 

When I do `shoes -p swt:jar ./app.yaml`, then it creates the okfilter.jar file, which has the following behavior:
- When running `java -jar pkg/okfilters.jar` from the project directory, it finds the file and works fine.
- After copying the .jar file elsewhere and running `java -jar okfilter.jar`, it throws an error about not being able to find the OkFilter.rb file.

I opened okfilter.jar and modified `OkShoes.rb`'s require to look like this: `require 'shoes-app/OkFilter'` which fixes the issue. However, this would break non-packaged operation.

What's the approved/expected way to require non-gem Ruby files? Or, am I otherwise doing things terribly wrong?

Running all of this on Ubuntu 14.04, JRuby 1.7.16, Shoes v4.0.0.pre2.

**Comment by jasonrclark** [comment]
Long time this has sat open, but I'm finally buckling down on packaging.

When I duplicate building a package for the linked app (updating it's `Gemfile` to the latest Shoes release, `4.0.0.pre9`) I don't see the require issues with jars outside the original source directory. Given the update to JRuby 9.x and updates to `warbler` and `shoes` in the meantime, it isn't too surprising to me that this might have gotten addressed somewhere along the way.

@parsonsmatt if you still have any interest to check it out, would appreciate any confirmation you can give. If I don't hear back, I'll close this when the pre10 release hits (hopefully by the end of the month!)

**Comment by parsonsmatt** [comment]
Ah, I haven't touched any of this in a while! If your tests for the functionality work, then this can be closed out.

**Comment by jasonrclark** [comment]
Thanks @parsonsmatt!

Reviewing again today, I realized that you'd updated to `require_relative` in the app, and if I put it back to `require` it still breaks like so:

```
LoadError: no such file to load -- OkFilter
  require at org/jruby/RubyKernel.java:961
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:120
   <main> at uri:classloader:/shoes-app/OkShoes.rb:3
     load at org/jruby/RubyKernel.java:979
   <main> at uri:classloader:/META-INF/main.rb:1
  require at org/jruby/RubyKernel.java:961
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:120
   <main> at uri:classloader:/META-INF/main.rb:2
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- OkFilter
```

Looks like something I'll want to get fixed!
