### ISSUE TITLE
List box vertical alignment

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#927]
Originally off the mailing list, not linked there yet. (http://librelist.com/browser/shoes/)

```
#!    /usr/bin/env jruby
require 'shoes'

Shoes.app do
  stack do
    flow do
      para "1"
      list_box items: ['a']
    end
    flow do
      para "2"
      list_box items: ['b']
    end
    flow do
      button 'Push me'
    end
  end
end
```

I get the incorrect list-box alignment as in 

![listbox](http://algoram.com/tmp/shoes/4.png)

Running on jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on OpenJDK 64-Bit Server VM 
1.7.0_65-b32 +jit [linux-amd64]
Built using rvm.
OS is Debian Jessie, which is a pre-release.

Note that I (@jasonrclark) tested this on Mac OS X 10.9 and didn't see a problem

**Comment by jasonrclark** [comment]
Still repros, and after some poking I'm a bit mystified--even through we're setting the height on the combo to 20, on Linux it seems to be ignored and using 29 instead.

If I can't find a way to force the height on the combo, we may just need to draw the default height for combo from what the platform actually does instead of trying to push it down from the DSL. This would make platform differences which stinks, though... or maybe I could make all platforms a bit bigger? Will see how goofy that looks when I sit down next.

**Comment by jasonrclark** [comment]
So turns out each OS has a different default height 😭  Mac is 20, Windows is 23, Linux is 29 (at least in the desktop I've got). Images following of what it looks like just altering that default. Feels a bit brittle, but might be better than having platform-dependent positioning? What do you think @PragTob?

**Mac**
![image](https://cloud.githubusercontent.com/assets/130504/23583736/d544e43e-0101-11e7-8349-027eb1318217.png)

**Windows**
![image](https://cloud.githubusercontent.com/assets/130504/23583739/ddbf522a-0101-11e7-98bd-c0b710bbd44a.png)

**Linux**
![image](https://cloud.githubusercontent.com/assets/130504/23583744/f1493b4e-0101-11e7-802d-182e6548a6a1.png)

**Comment by PragTob** [comment]
most pragmatic solution I feel :+1:
