### ISSUE TITLE
Allow interactively selecting a Shoes backend

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#929]
Implementation of #925 made the spot where we could select a specific backend, but only implements it for a single backend (which doesn't require user interaction). Let's handle the interactive selection (and potentially other means, like an ENV?) as a separate issue.

I'm imagining something command-line, but like you get for uninstalling gems with a numbered list that you can select from.

**Comment by PragTob** [comment]
And this is... IN! :clap:
