### ISSUE TITLE
Direct JRuby dependency in Windows batch file (remove it)

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#930]
As discussed in #925 the windows batch file... 

>Still has a direct dependency on Windows for JRuby in the batch file. Locally for me I couldn't just call ruby, only jruby would work. Anyone know more about this than me to tell me how we could make that not coupled to jruby for future non-JRuby backends?

Anyone have an idea what the JRuby installer does there/how we could work around it? Is it a path issue? Do we have to push all that to the backend? Workarounds? I dunno. Will check for the behavior on my machine.

**Comment by jasonrclark** [comment]
Looked at my local Windows installation, and sure enough it doesn't include a `ruby` alias anywhere. Appears that is expects everyone to use `jruby` or use a Ruby switcher of some sort.

**Comment by PragTob** [comment]
Then we close this out and will reopen it/start a new issue if an issue with this pops up again. #closingmood
