### ISSUE TITLE
Guardfile fix after separating out shoes gems

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#950]
The changes from #949 have broken our Guardfile. Part of it is just the paths not matching anymore, but it didn't seem to be picking up changes when I edited the file to align with our relocated specs. Needs more investigation.

**Comment by jasonrclark** [comment]
Moved some things around, but seeing crashes with guard-rspec that I've logged over there as https://github.com/guard/guard-rspec/issues/341

**Comment by KCErb** [comment]
Oh wow, an *upstream* upstream issue. So now we wait on JRuby?

**Comment by jasonrclark** [comment]
Yup :ocean:

FWIW, 9k seemed to work in my testing repo, so I'm going to give that a kick when I get time and see if I can fix up the Guardfiles based on that. If we end up having to run 9k to get guard, that's probably acceptable since it's a development only thing.

**Comment by PragTob** [comment]
Also 9k is the future and while I still want to support 1.7.x 9k is definitely my major concern :)
