### ISSUE TITLE
Stray links kill app on hover

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#999]
```ruby
Shoes.app do
  link 'alone :('
end
```

Start it, hover it - boom! `NoMethodError: undefined method `visible?' for nil:NilClass`

That's due to the `#visible?` implementation: 

    def visible?
      @text_block.visible?
    end

`link` is not meant to be called alone. It needs to be part of a text block, therefore the app above is illegal to begin with. But this is not a nice way of letting people know that. It basically just happens because links automatically set up a click listener which then notices that it is not visible. 

It is hard to detect on instantiation, though - through the way of our DSL we have to create a `Link` object before we create a `TextBlock` object.

Possible fixes I can hink of:

1. change it to `@text_block && @text_block.visible?` and silently ignore it
2. have a guard in the beginning that prints a warning about a wrongly used link element

**Comment by PragTob** [comment]
SHIT :( I was in the train and accidentally pushed to master as I had to get out and wanted to push fast :cry: ... I knew this was gonna happen at some point :( I don't wanna force push... to master.

It's a small change but still... :( @jasonrclark can you please have a look at a52cf28ecf8d55f147ec82f and see if it's ok if we should go with a null object or something else?

In the meantime I promise to avoid hasty pushed and configure my terminal so that it shows me the current branch...

**Comment by jasonrclark** [comment]
No worries at all... I live and die by my prompt telling me my branch (and the git `push.default = none` option I set, so I always have to explicitly declare my branches to push).

Commit looks good. I think a null object would be overkill here, and my only comments were typos in comments and text.

**Comment by PragTob** [comment]
Okay thanks Jason! :)

I have my `push.default = current` which is nice for most use cases for me - if this happens again I'll have to revise :)

**Comment by jasonrclark** [comment]
Yeah, my work had a bit of a mandate about it, and I've just gotten used to spelling it all out. I think I might actually have shoes set differently so `rake release` can push tags, but my fingers are well trained to write it all down. YMMV.

**Comment by PragTob** [comment]
Fixed the remaining stuff
